HeapSort.java

Implemented HeapSort

---

LinearSearch.java
Quicksort.java

This pull request is to add the quick sort and linear search algorithms to the repo.

Implement Linear Search, and Quick Sort

---

data_structures/Stacks.java

ArrayList Implementation of stack has been added to stack folder.Please review.

Stack List Implementation

---

BinarySearch.java
BinaryToDecimal.java
BinaryToOctal.java
BubbleSort.java
DecimalToBinary.java
DecimalToOctal.java
Factorial.java
InsertionSort.java
InsertionSortInteger.java
LinearSearch.java
OctalToBinary.java
OctalToDecimal.java
Quicksort.java
ReverseString.java
SelectionSort.java
bfs.java
countwords.java
data_structures/CircleLinkedList.java
data_structures/Graphs.java
data_structures/heaps/MaxHeap.java
data_structures/heaps/MinHeap.java
dfs.java

- Closed all of the Scanners and BufferedReaders
- Added some Javadoc
- ReverseString - took space out of between each letter so "Zachary" to "yrahcaZ" instead of "y r a h c aZ"
- bfs - Trying to repair this class but need to research bfs more
- dfs - Trying to repair this class but need to research dfs more
- Added the data structure Graphs (Unfinished)
- Added new classes
1) OctalToBinary - Not Done
2) BinaryToOctal - Not Done
3) OctalToDecimal - Not Done
4) Graphs - Not Done

More Additions (Info below)

---

Dijkshtra.java

Dijkshtra's Shortest Path Implementation

Dijkshtra's Algorithm

---

Conversions/DecimalToHexaDecimal.java
Conversions/OctalToBinary.java
Conversions/OctalToDecimal.java

Finished some unfinished conversions in Octal system.
Added Decimal to HexaDecimal conversion.

Conversions Works

---

data_structures/Stacks.java

Added an if statement to:
- The push method to make sure the stack wasn't full.
- The pop method to make sure the stack wasn't empty.
- The peek method to make sure the stack wasn't empty.

Added a few edge cases in the stack class

---

Searches/BinarySearch.java

In this commit, I applied the EARLY RETURN. I very much hope to contribute to your repository. I hope you accept it!

Simplifies the readability of the static method BS

---

data_structures/Graphs/Graphs.java
data_structures/Graphs/makefile

Added a graph implementation, takes any object that extends comparable since it relies on that to determine if verticies with that data already exist in the graph in order to prevent duplicate verticies.

Add adjacency list graph implementation

---

Dynamic Programming/LongestIncreasingSubsequence.java

Add longest increasing subsequence

---

ciphers/ColumnarTranspositionCipher.java

Added Columnar Transposition Cipher with example usage

Columnar Transposition Cipher with example usage

---

README.md

- quick sort
- shell sort
- searches(linear,binary)
in reference to issue #96

adding new content to README

---

data_structures/Trees/TreeTraversal.java

1) Added level order traversal.
2) Added more nodes to example tree, to have a complete BST of height 2.
#103

Added level order traversal, and more nodes in main method

---

Dynamic Programming/Fibonacci.java
Dynamic Programming/Levenshtein_distance.java
Dynamic Programming/LongestIncreasingSubsequence.java

Some public methods could be set private. Furthermore the static keyword was missing in two cases.

turned some public methods private

---

Data Structures/Matrix/Matrix.java

Updated Matrix.java

---

Misc/PalindromicPrime.java

Palindromic Primes

---

Conversions/DecimalToBinary.java

This adds a (not pure) bitwise approach, which is more efficient than a conventional approach (it does not need any division operation), to convert from decimal to binary. It also creates an interface to ease the choose between conventional and bitwise methods.
I have a pure bitwise approach in another [branch](https://github.com/petersonddb/Java/blob/dec2bin-purebitwise/Conversions/DecimalToBinary.java) but it is less efficient (because the loops and method calls).

Add a bitwise conversion for DecimalToBinary.

---

Conversions/HexaDecimalToDecimal.java

added HexaDecimalToDecimal.java on conversions.
it converts Hexadecimal input to decimal.

Created HexaDecimalToDecimal.java

---

Data Structures/Graphs/BFS.java
Data Structures/Graphs/DFS.java
Data Structures/Graphs/PrimMST.java
Dynamic Programming/LevenshteinDistance.java
Others/SkylineProblem.java
SkylineProblem/SkylineProblem.java

implement Skyline Problem using Divide and Conquer
Skyline problem: drawing skylines without overlapping lines on 2-D plane in case the location(x, y) and height of building are given
input data is (x coordinate, height, y coordinate).
output data is List of (x, y) coordinates.

implement SkylineProblem

---

Dynamic Programming/CoinChange.java

for loop above if condition is starting from coin and operation is increment in loop
so value of i will be always >= coin 
hence if condition is redundant there

Removing redundant if condition

---

README.md

Removing the Travis CI badge as it points to a dead URL. As this repository has [very few tests](https://github.com/TheAlgorithms/Java/search?q=Test&unscoped_q=Test), maybe a CI build might be a bit too much.

Remove Tracis CI badge from README.md

---

DataStructures/Matrix/MatrixFastPower.java

Added MatrixFastPower.java
Other Matrix basic operator is based on @khalil2535

Added MatrixFastPower.java 

---

divideconquer/ClosestPair.java

Refactorized ClosestPair.java: adding commets, eliminating unuseful parameters, reorganizing code lines to be less than 80 characteres, each variable declaration in one line.
I've deleted txt file to provide input data.
I've created a unit test class. To complete the tests I've created a auxiliary type Location.

Refactorized ClosestPair.java in order to be compliant with java sun rules

---

Others/SJF.java

Scheduling Algorithm - Priority and Shortest job first which solves the starvation

added scheduling algorithm

---

DataStructures/Lists/Merge_K_SortedLinkedlist.java

Add new program which merge K sorted linkedList

Add Merge K sorted LinkedList

---

src/main/java/com/search/FibonacciSearch.java
src/test/java/com/search/FibonacciSearchTest.java

Fibonacci search is a method of searching a sorted array using a divide and conquer algorithm that narrows down possible locations with the aid of Fibonacci numbers. Compared to binary search where the sorted array is divided into two equal-sized parts, one of which is examined further, Fibonacci search divides the array into two parts that have sizes that are consecutive Fibonacci numbers.

Added the algorithm and test for Fibonacci Search

---

src/main/java/com/designpatterns/factorypattern/Pentagon.java
src/main/java/com/designpatterns/factorypattern/Polygon.java
src/main/java/com/designpatterns/factorypattern/PolygonFactory.java
src/main/java/com/designpatterns/factorypattern/Square.java
src/main/java/com/designpatterns/factorypattern/Triangle.java
src/test/java/com/designpatterns/factorypattern/PolygonFactoryTest.java

In class-based programming, the factory method pattern is a creational pattern that uses factory methods to deal with the problem of creating objects without having to specify the exact class of the object that will be created. This is done by creating objects by calling a factory method—either specified in an interface and implemented by child classes, or implemented in a base class and optionally overridden by derived classes—rather than by calling a constructor.

Added Factory pattern implementation in Java and its test

---

src/main/java/com/designpatterns/builderpattern/Desktop.java
src/test/java/com/designpatterns/builderpattern/DesktopBuilderTest.java

The Builder is a design pattern designed to provide a flexible solution to various object creation problems in object-oriented programming. The intent of the Builder design pattern is to separate the construction of a complex object from its representation.

Added Builder Design pattern implementation in Java and its test

---

src/main/java/com/designpatterns/creational/prototype/BlackColor.java
src/main/java/com/designpatterns/creational/prototype/BlueColor.java
src/main/java/com/designpatterns/creational/prototype/Color.java
src/main/java/com/designpatterns/creational/prototype/ColorStore.java
src/main/java/com/designpatterns/creational/prototype/RedColor.java
src/test/java/com/designpatterns/creational/prototype/PrototypeTest.java
src/test/java/com/generation/SimplexNoiseTest.java

The prototype pattern is used when the type of objects to create is determined by a prototypical instance, which is cloned to produce new objects.

Added the prototype pattern and its unit test

---

src/main/java/com/crypto/codec/Base64.java
src/main/java/com/generation/SimplexNoise.java
src/test/java/com/generation/SimplexNoiseTest.java

SonarQube showed these calls as probable minor bugs. Since Math.pow() accepts double type operands, the second operand should be type-casted explicitly for safety.

Cast the second operand of Math.pow to double - SonarQube analysis

---

src/main/java/com/designpatterns/creational/abstractfactory/AbstractShapeFactory.java
src/main/java/com/designpatterns/creational/abstractfactory/Circle.java
src/main/java/com/designpatterns/creational/abstractfactory/FactoryProvider.java
src/main/java/com/designpatterns/creational/abstractfactory/FactoryType.java
src/main/java/com/designpatterns/creational/abstractfactory/Line.java
src/main/java/com/designpatterns/creational/abstractfactory/Shape.java
src/main/java/com/designpatterns/creational/abstractfactory/ShapeType.java
src/main/java/com/designpatterns/creational/abstractfactory/Sphere.java
src/main/java/com/designpatterns/creational/abstractfactory/ThreeDShapeFactory.java
src/main/java/com/designpatterns/creational/abstractfactory/TwoDShapeFactory.java
src/test/java/com/designpatterns/creational/abstractfactory/AbstractShapeFactoryTest.java
src/test/java/com/others/FastPowerTest.java

The abstract factory pattern provides a way to encapsulate a group of individual factories that have a common theme without specifying their concrete classes.

Added the code for Abstract factory pattern implementation and JUnit

---

src/main/java/com/conversions/BinaryToHexadecimal.java
src/main/java/com/conversions/DecimalToHexadecimal.java
src/main/java/com/conversions/DecimalToOctal.java
src/main/java/com/designpatterns/structural/adapter/BugattiVeyron.java
src/main/java/com/designpatterns/structural/adapter/Movable.java
src/main/java/com/designpatterns/structural/adapter/MovableAdapter.java
src/main/java/com/designpatterns/structural/adapter/MovableAdapterImpl.java
src/test/java/com/designpatterns/structural/MovableAdapterTest.java
src/test/java/com/designpatterns/structural/adapter/MovableAdapterTest.java

An Adapter pattern acts as a connector between two incompatible interfaces that otherwise cannot be connected directly. An Adapter wraps an existing class with a new interface so that it becomes compatible with the client’s interface.

Added adapter pattern and its test case

---

DataStructures/Stacks/StackArray.java

The change of reference of member stackArray is unnecessarily in a loop.
This might be nice when it is out of the loop block

Fix StackArray.java resize()

---

DataStructures/Lists/MergeSortedArrayList.java

mergeSortedArrayList

---

DataStructures/Stacks/DecimalToAnyUsingStack.java

* Decimal convert to another radius using stack is important algorithm 
Please review @yanglbme

DecimalToAnyUsingStack

---

DataStructures/Queues/LinkedQueue.java

add `LinkedQueue.java`
Please review! @yanglbme

LinkedQueue

---

src/main/java/com/sorts/BubbleSort.java
src/main/java/com/types/DataStructure.java
src/main/java/com/types/Sort.java
src/test/java/com/sorts/BubbleSortTest.java

Fixed 'Generics' issue of bubble sort since Sort interface should accept only comparable datatype rather than just restricting sort method

Fixing 'Generics' issue in Sort

---

Conversions/DecimalToBinary.java
Conversions/DecimalToHexaDecimal.java
Conversions/DecimalToOctal.java
Conversions/HexaDecimalToBinary.java
Conversions/IntegerToRoman.java
Conversions/RomanToInteger.java
Maths/AbsoluteMax.java
Maths/AbsoluteMin.java
Maths/Factorial.java
Maths/Pow.java

Clarified what some files did with comments for future contributors

Comment revisions

---

src/main/java/com/designpatterns/structural/decorator/CompressingDecorator.java
src/main/java/com/designpatterns/structural/decorator/EmailSender.java
src/main/java/com/designpatterns/structural/decorator/EncodingDecorator.java
src/main/java/com/designpatterns/structural/decorator/Sender.java
src/main/java/com/designpatterns/structural/decorator/SenderDecorator.java
src/test/java/com/designpatterns/decorator/DecoratorDemo.java

I've implemented Decorator Pattern.
Here are the list of changes:
1. `EmailSender` class sends emails as plain text, it should be decorated (without modification) so that emails gets encoded and compressed.
2. `SenderDecorator` class implements `Sender` interface and provides a base class for decorator pattern.
3. `CompressingDecorator` and `EncodingDecorator` classes are two implementaions of `Sender` interface that compress and encode emails.
4. and finally `DecoratorDemo` class provides some tests for demonstrating the utilization of Decorator Patern.

Decorator pattern Implementation

---

Sorts/BogoSort.java
Sorts/BubbleSort.java
Sorts/CombSort.java
Sorts/RadixSort.java

Removed C-style looking array brackets and changed to appropriate Java convention brackets.

fix: removed warning for Sorts 'C-style array declaration of parameter 'array''

---

Sorts/MergeSort.java

* optimization by reducing function parameter
@yanglbme

optimization

---

.github/workflows/gradle.yml
.gitignore
build.gradle

Adds simple github on push gradle workflow for Development branch.

Add simple gradle workflow for Development

---

build.gradle
src/main/java/com/dataStructures/Stack.java

First commit updates a link in build.gradle, since the old one is not supported anymore.
Second commit rewrites Stack.java since it contained major design flaws.

Fix maven link and correct Stack implementation

---

Maths/AmicableNumber.java
Maths/VampireNumber.java

It's working. Nothing to say more. Have a great day :)
#1295

Implementing AmicableNumber and VampireNumbers in the Math class

---

DataStructures/Lists/DoublyLinkedList.java
DataStructures/Trees/AVLTree.java

implemented recursive search for key in a tree with a search helper

implement search in AVL tree

---

DataStructures/Heaps/GenericHeap

I m contributing first time any sugeestions then let me know Generic heap is very useful

Created GenericHeap

---

Others/RabinKarp.java
Others/StringMatchFiniteAutomata.java

String matching algorithms
- Rabin-Karp algorithm
- String matching using Finite Automata

Added Missing Algorithms

---

Others/3 sum.java
Others/Rotation of array without using extra space.java

I have added some missing codes:
- Array rotation
- 3 sum (to find triplets in efficient manner)
Pull request related to #1308  .
Further, I will add some more codes related to binary search(Lower/upper bound).

Missing Codes

---

Sorts/BucketSort.java

Added Bucket Sort

---

DynamicProgramming/Minimum sum partition

Given an array, the task is to divide it into two sets S1 and S2 such that the absolute difference between their sums is minimum.

Minimum sum partition

---

Sorts/BubbleSort.java
Sorts/SortUtils.java

1. According to method's comment, array elements must be sorted in ascending order. But they sorted in descreasing order.
2. Fixed some spelling mistakes. Order can be ascending and desceding, but not increasing and descreasing.

Fixed wrong order in BubbleSort, corrected spelling mistakes

---

Others/3 sum.java
Sorts/BucketSort.java
Sorts/SelectionSort.java

Fixing errors and warnings

---

DataStructures/Graphs/Kruskal.java

Kruskal algorithm was missing.
It is used to find the minimum spanning tree.
My code simplifies other implementations, the algorithm itself is just composed of one method with less than 25 lines of code commented.

Kruskal Implemented

---

DataStructures/Graphs/A_Star.java

A-Star is one of the most popular graph path-search algorithms.
Due to the fact that it uses a heuristic function to decide between the available paths, it is considered to be a smart algorithm.
I have included an example with the graph drawn, the output formatted, and comments to explain the code.
I hope you accept me, let me know if I have to change anything :)

A-Star Algorithm Included

---

Strings/ZFunction.java

Added z function and also created strings package.

z function added

---

DataStructures/Lists/DoublyLinkedList.java

the method public void deleteNode(Link z) deletes the passed node from the current linked list
closes #1358

Added deleteNode method

---

DataStructures/HashMap/Hashing/HashMapLinearProbing.java
DataStructures/HashMap/Hashing/MainLinearProbing.java

closes #1380 
The class HashMapLinearProbing implements a hash map with open addressing functionality, covering delete, find, insert, and display.
The class MainLinearProbing is a driver that allows testing of the HashMapLinearProbing class.

Add HashMapLinearProbing.java and MainLinearProbing.java

---

src/main/java/com/caching/LRUCache.java
src/test/java/com/caching/LRUCacheTest.java

closes #1370 
**Addresses the remaining half of issue #1370**
Added LRU cache implementation and test for the implementation.
_This is my first open source contribution, feel free to correct me if i am wrong. i'd be happy to learn :)_

Added LRU cache implementation.

---

DataStructures/HashMap/Hashing/HashMap.java

closes #1388 
the nested static classes linked list and node enable the functionality of the HashMap class, allowing users to run the main.java file and test the class. Previous implementations had a separate linked list class that was out of place in the "hashmap" folder

Add nested linked list and node class to HashMap.java

---

DataStructures/DynamicArray/DynamicArray.java

Javadoc comments allow the user to understand the purpose of each method within the DynamicArray class.
cleanup within the class covers:
Condense imports
Initialize fields in constructor
Change binary shifting to simple multiplication reassignment for better understanding
Add brackets to multi-line if statements
Change name of size() method to getSize() to reflect purpose of the method
remove extra white-space
remove 2 lines of unnecessary commented out code
closes #1400

Add javadoc comments and Cleanup DynamicArray.java

---

src/main/java/com/caching/LFUCache.java
src/main/java/com/caching/LRUCache.java
src/main/java/com/ciphers/CaesarBruteForce.java
src/main/java/com/conversions/HexadecimalToBinary.java
src/main/java/com/datastructures/BinaryTree.java
src/main/java/com/datastructures/DisjointSet.java
src/main/java/com/datastructures/GeneralQueue.java
src/main/java/com/datastructures/IntQueue.java
src/main/java/com/datastructures/SinglyLinkedList.java
src/main/java/com/datastructures/Stack.java
src/main/java/com/matchings/stablematching/GaleShapley.java
src/test/java/com/datastructures/BinaryTreeTest.java
src/test/java/com/datastructures/DisjointSetTest.java
src/test/java/com/datastructures/GeneralQueueTest.java
src/test/java/com/datastructures/IntQueueTest.java
src/test/java/com/datastructures/SinglyLinkedListTest.java
src/test/java/com/datastructures/StackTest.java
src/test/java/com/matchings/stablematching/GaleShapleyTest.java

Multiple code smells were found by [SonarQube](https://www.sonarqube.org/) on the project. Some of them were violations of the below rules:
- Local variable names in java must be with the  default regular expression ^[a-z][a-zA-Z0-9]*$ [RSPEC-117](https://rules.sonarsource.com/java/tag/convention/RSPEC-117)
- The diamond operator ("<>") should be used when the type of the maps are already defined [RSPEC-2293](https://rules.sonarsource.com/java/RSPEC-2293)
- Package names being camel cased is a code smell, all package names must be lowercase
- String literals should not be duplicated [RSPEC-1192](https://rules.sonarsource.com/java/RSPEC-1192)
- Generic types shouldn't be used raw (without type parameters) in variable declarations or return values. Doing so bypasses generic type checking, …

Fixed code smells after running sonarqube on the project

---

src/main/java/com/caching/LFUCache.java
src/main/java/com/caching/LRUCache.java
src/main/java/com/ciphers/CaesarBruteForce.java
src/main/java/com/conversions/HexadecimalToBinary.java
src/main/java/com/datastructures/BinaryTree.java
src/main/java/com/datastructures/DisjointSet.java
src/main/java/com/datastructures/GeneralQueue.java
src/main/java/com/datastructures/IntQueue.java
src/main/java/com/datastructures/SinglyLinkedList.java
src/main/java/com/datastructures/Stack.java
src/main/java/com/matchings/stablematching/GaleShapley.java
src/test/java/com/datastructures/BinaryTreeTest.java
src/test/java/com/datastructures/DisjointSetTest.java
src/test/java/com/datastructures/GeneralQueueTest.java
src/test/java/com/datastructures/IntQueueTest.java
src/test/java/com/datastructures/SinglyLinkedListTest.java
src/test/java/com/datastructures/StackTest.java
src/test/java/com/matchings/stablematching/GaleShapleyTest.java

Reverts TheAlgorithms/Java#1432

Revert "Revert "Fixed code smells after running sonarqube on the project""

---

DataStructures/HashMap/Hashing/HashMapLinearProbing.java
DataStructures/HashMap/Hashing/MainLinearProbing.java

The checkLoadFactor() method adds dynamic array functionality to HashTableLinearProbing.java
Through its use, it can be a powerful tool in avoiding collisions as the hash table fills. 
It calls the lengthenTable() method when load factor exceeds .7
I have updated MainLinearProbing.java to test this new method.
I've also made a change to the findHash() method to avoid NullPointerException at runtime and made code easier to read in some places

Add dynamic hash table functionality

---

DIRECTORY.md
ProjectEuler/Problem04.java

Created Problem04 in ProjectEuler

---

Others/PasswordGen.java
README.md

Used StringBuilder for the variable password instead of String as it was being modified with every iteration.

String to StringBuilder in Others/PasswordGen.java

---

src/main/java/com/string/ReverseWords.java
src/test/java/com/string/ReverseWordsTest.java

ReverseWord & ReverseWordsTest

---

.travis.yml
DIRECTORY.md

Travis CI: Fix build validation issues, add Xlint options

---

DIRECTORY.md
Maths/ConvolutionFFT.java
Misc/ColorContrastRatio.java

This implements the procedure documented on the W3 website to calculate the contrast ratio between two colors.  
https://www.w3.org/TR/WCAG20-TECHS/G17.html#G17-procedure
N/A

Added algorithm for color contrast ratio.

---

DynamicProgramming/LongestValidParentheses.java

Because in the future, the variable len is not used anywhere

improvement: Improved print format style 

---

DataStructures/Graphs/FloydWarshall.java

Arrays.fill() accepts single dimensional arrays, so fill one row at a time.
Fixes TheAlgorithms/Java#2009

Fix 2D array passed to Arrays.fill()

---

Searches/BinarySearch.java

">>> 1" is simply too obscure...

BinarySearch: clearer median computation

---

Maths/MagicSquare.java

Added MagicSquare.java  Fixes: #2383

---

DivideAndConquer/StrassenMatrixMultiplication.java

Add Strassen Matrix Multiplication algorithm

---

DataStructures/Graphs/MatrixGraphs.java

This simply adds the ability to return a `List<Integer>` ordered by either a breadth first search algorithm or depth first search algorithm from a `MatrixGraphs`.
- ~~Documentation change?~~

Add BFS/DFS ordering to matrix graphs

---

src/main/java/com/thealgorithms/others/HappyNumbersSeq.java
src/main/java/com/thealgorithms/searches/LinearSearchThread.java

Add Happy numbers problem in "others" category

---

src/main/java/com/thealgorithms/maths/JugglerSequence.java

#2841 Juggler Sequence Implementation

Add juggler sequence implementation

---

src/main/java/com/thealgorithms/maths/KaprekarNumbers.java
src/test/java/com/thealgorithms/maths/KaprekarNumbersTest.java

Added KaprekarNumbersTest

---

src/main/java/com/thealgorithms/maths/KaprekarNumbers.java

- [issue](https://github.com/TheAlgorithms/Java/issues/2890)
- Still working on it

Added kaprekarNumberInRange

---

DIRECTORY.md
src/main/java/com/thealgorithms/datastructures/trees/TreeRandomNode.java

Add algorithms_tree_random_node.java in trees section

---

src/main/java/com/thealgorithms/backtracking/Combination.java
src/main/java/com/thealgorithms/backtracking/Permutation.java
src/test/java/com/thealgorithms/backtracking/CombinationTest.java
src/test/java/com/thealgorithms/backtracking/PermutationTest.java

- [ x] Add an algorithm?
- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized.
- [ x] I know that pull requests will not be merged if they fail the automated tests.
- [ x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ x] All new Java files are placed inside an existing directory.
- [ x] All filenames are in all uppercase characters with no spaces or dashes.
- [ x] All functions and variable names follow Java naming conventions.
- [ x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ x] If this pull request resolves one or more open issues then the …

add permutation

---

src/main/java/com/thealgorithms/others/MemoryManagementAlgorithms.java
src/test/java/com/thealgorithms/others/BestFitCPUTest.java
src/test/java/com/thealgorithms/others/FirstFitCPUTest.java
src/test/java/com/thealgorithms/others/NextFitTest.java
src/test/java/com/thealgorithms/others/WorstFitCPUTest.java

Fixes: #3012 - Rename CPUalgorithms class to MemoryManagmentAlgorithms

---

src/main/java/com/thealgorithms/datastructures/lists/SkipList.java
src/test/java/com/thealgorithms/datastructures/lists/SkipListTest.java

There was a failed build: https://github.com/TheAlgorithms/Java/runs/6992142297?check_suite_focus=true
After some debugging I have found the problem. After removing some node all links for previous and next node should be reassigned. But current algorithm did not mentioned that next node could be null. For example (on this structure tests had failed in linked build):
```
[ ] --- --- --- --- --- --- --- --- --- --- --- 
[ ] --- --- --- --- --- --- --- --- --- --- --- 
[ ] [ ] --- --- --- --- --- --- --- --- --- --- 
[ ] [ ] --- --- --- --- --- --- --- --- --- --- 
[ ] [ ] --- --- --- --- --- --- --- [ ] --- --- 
[ ] [ ] --- --- [ ] --- [ ] --- --- [ ] --- --- 
[ ] [ ] [ ] --- [ ] --- [ ] --- --- [ ] --- --- 
[ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] 
H   0   1   2   3   4   5   6   7 …
```

Fix SkipList remove operation

---

src/test/java/com/thealgorithms/strings/ReverseStringTest.java

Adding ReverseStringTest for both implementations of reverse

---

src/main/java/com/thealgorithms/divideandconquer/BinaryExponentiation.java
src/main/java/com/thealgorithms/divideandconquer/StrassenMatrixMultiplication.java
src/test/java/com/thealgorithms/divideandconquer/BinaryExponentiationTest.java
src/test/java/com/thealgorithms/divideandconquer/StrassenMatrixMultiplicationTest.java

Added test cases for `StarssenMatrixMultiplication` and `BinaryExponrntiation` and did some refactoring.

Add two Test.java file for 2 Divide and conquer algorithm

---

src/main/java/com/thealgorithms/strings/Anagrams.java

removed the extra loop in Anagram.java by using the equals function and added a comment

Removed extra loop in Anagram.java

---

src/main/java/com/thealgorithms/ciphers/RSA.java
src/test/java/com/thealgorithms/ciphers/RSATest.java

Add unit test for RSA cipher

---

src/main/java/com/thealgorithms/backtracking/FloodFill.java

fixed minor typos

---

src/main/java/com/thealgorithms/strings/WordLadder.java
src/test/java/com/thealgorithms/strings/WordLadderTest.java

Added comments for Test Cases and rearranged code in WordLadderTest.java, 
And removed main() and formatted code in WordLadder.java

Updated WordLadderTest.java & WordLadder.java

---

src/main/java/com/thealgorithms/conversions/BinaryToDecimal.java
src/test/java/com/thealgorithms/conversions/BinaryToDecimalTest.java

Add Test case for BinaryToDecimal

---

src/test/java/com/thealgorithms/conversions/RomanToIntegerTest.java

Add test case for RomanToInteger

---

src/main/java/com/thealgorithms/datastructures/heaps/LeftistHeap.java
src/test/java/com/thealgorithms/datastructures/heaps/LeftistHeapTest.java

- [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized it.
- [x ] All filenames are in PascalCase.
- [x ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

Adding Leftist Heap data structure with test file

---

src/main/java/com/thealgorithms/backtracking/PowerSum.java

the above file had an unnecessary import that is scanner which is not required as per current scope of the class. hence removed the import and ensured no dependancies.

removed unnecessary import as user input is not required in class.

---

src/main/java/com/thealgorithms/datastructures/trees/ZigZagTraversal.java
src/main/java/com/thealgorithms/datastructures/trees/ZigzagTraversal.java
src/test/java/com/thealgorithms/datastructures/trees/ZigzagTraversalTest.java

Added Zigzag Traversal of a Binary Tree

---

src/main/java/com/thealgorithms/ciphers/SimpleSubstitutionCipher.java
src/test/java/com/thealgorithms/ciphers/SimpleSubstitutionCipherTest.java

Add SimpleSubstitutionCipherTest

---

src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
src/test/java/com/thealgorithms/datastructures/graphs/KosarajuTest.java

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized it.
- [ x] All filenames are in PascalCase.
- [ x] All functions and variable names follow Java naming conventions.

Adding Kosaraju Algorithm

---

src/main/java/com/thealgorithms/dynamicprogramming/OptimalJobScheduling.java
src/test/java/com/thealgorithms/dynamicprogramming/OptimalJobSchedulingTest.java

I have also added test classes.

Initial commit

---

src/main/java/com/thealgorithms/datastructures/queues/LinkedQueue.java
src/test/java/com/thealgorithms/datastructures/queues/LinkedQueueTest.java

(Other ticks dont apply)
#3908 Issue.

LinkedQue: Features and Improvements

---

.github/workflows/update_directory.yml

A simple fix to accelerate our GitHub Actions...
https://docs.python.org/3.11/whatsnew/3.11.html
> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.
@Boiarshinov Your review, please.

Python 3.11 is between 10-60% faster than Python 3.10

---

src/main/java/com/thealgorithms/maths/GCD.java
src/test/java/com/thealgorithms/maths/GCDTest.java

I have observed that the function [`GCD.gcd(int[])`](https://github.com/TheAlgorithms/Java/blob/36232a8373264319cdb893bf9da1615fea05999d/src/main/java/com/thealgorithms/maths/GCD.java#L41):
- is not tested,
- crashes when computing `GCD.gcd(new int[]{});`,
- `GCD.gcd(new int[]{-1});` returns `-1` (observe that GCD.gcd(-1, -1); [would throw](https://github.com/TheAlgorithms/Java/blob/36232a8373264319cdb893bf9da1615fea05999d/src/main/java/com/thealgorithms/maths/GCD.java#L20) `ArithmeticException()`).
In this PR, I:
- add missing tests 7e60a58be3ac3ec5de2c46bd28e5ae42b1f1e57e,
- make `GCD.gcd(new int[]{});` returns `0` a6b5d09bbf424d7cc142390ccf51c11088edc288 - this change also handles the case, when the input is of the type `{-1}`,
- update documentation …

fix: handle empty input for `GCD.gcd(int[])`

---

src/main/java/com/thealgorithms/maths/FindMax.java
src/test/java/com/thealgorithms/maths/FindMaxTest.java

This PR is analogous to #4205. The method [`FindMax.findMax`](https://github.com/TheAlgorithms/Java/blob/4f1514980495c4daaae2eb060228a87e14cbae11/src/main/java/com/thealgorithms/maths/FindMax.java#L32) crashes for empty input.
This PR:
- adds _missing_ test cases,
- makes `findMax` to throw `IllegalArgumentException` for empty input,
- updates the implementation and doc string to be consistent with [`FindMin.findMin`](https://github.com/TheAlgorithms/Java/blob/4f1514980495c4daaae2eb060228a87e14cbae11/src/main/java/com/thealgorithms/maths/FindMin.java#L33)

style: handle empty input array in `FindMax.findMax`

---

src/main/java/com/thealgorithms/others/CountWords.java
src/test/java/com/thealgorithms/others/CountWordsTest.java

The original implementation of [`secondaryWordCount`](https://github.com/TheAlgorithms/Java/blob/22002c9939fdeff1d7ef659a688ad7f396dd564a/src/main/java/com/thealgorithms/others/CountWords.java#L40) always returns `1` for non-empty input (note that the spaces are always removed).
This PR:
- fixes the mentioned issue,
- adds tests,
- does some basic refactoring.

fix: `CountWords.secondaryWordCount`

---

src/main/java/com/thealgorithms/others/cn/HammingDistance.java
src/test/java/com/thealgorithms/others/cn/HammingDistanceTest.java

I have found few problems with the implementation of [`HammingDistance`](https://github.com/TheAlgorithms/Java/blob/7a3273ae1db2a652b80a4b655e642f06331937cb/src/main/java/com/thealgorithms/others/cn/HammingDistance.java#L6), namely:
- unnecessary conversion from `String` to `byte[]`,
- I think that this implementation was aiming to handle only `String`s containing only `0`s and `1`s, but this is not checked anywhere.
This PR:
- makes a _proper utility_ class out of `HammingDistance` in 610def7764dee995373d0e7a6ded5e0a1af644ed,
- simplifies logic of some existing tests and adds tests against empty input and input of length `1` in 58f7da387e1916ca169b25a5c3547e5df56f1ffc,
- simplifies logic in class `HammingDistance`, updates naming and changes the behaviour for _non-binary strings_ in …

refactor: simplify `HammingDistance`

---

.gitpod.dockerfile
.gitpod.yml

When this project is opened in Gitpod, the created workspace does not directly work. This PR adds some basic configuration (i.e. now, in created workspace one can successfully run `mvn test`).
I could not force the the existing [docker image](https://github.com/TheAlgorithms/Java/blob/4effd28d80faa64087c2cbb94f106e5be61b7324/.devcontainer/Dockerfile) to work with Gitpod.

chore: configure gitpod

---

.gitpod.dockerfile
.gitpod.yml

This PR allows to use clang-format in gitpod's VS Code (cf. #4214). It is a _continuation_ of #4243.

chore: add clang-format to gitpod

---

src/main/java/com/thealgorithms/maths/SumOfArithmeticSeries.java
src/test/java/com/thealgorithms/maths/SumOfArithmeticSeriesTest.java

This PR adds test and _lints_ the class [`SumOfArithmeticSeries`](https://github.com/TheAlgorithms/Java/blob/e897a93166b7883f4abebf96b32f763e3f29f07c/src/main/java/com/thealgorithms/maths/SumOfArithmeticSeries.java#L13).

tests: add tests for `SumOfArithmeticSeries`

---

src/main/java/com/thealgorithms/datastructures/trees/BinaryTree.java

 redundant and duplicate lines fixed

---

src/main/java/com/thealgorithms/others/StackPostfixNotation.java
src/test/java/com/thealgorithms/others/StackPostfixNotationTest.java

After #4261 was merged, I have realized that the method [`StackPostfixNotation.postfixEvaluate`](https://github.com/vil02/Java/blob/44dcebb6996b39b5a1a67a8633f95b6e4c1bd0f0/src/main/java/com/thealgorithms/others/StackPostfixNotation.java#L11) still does not handle properly all of the inputs (e. g. `"2 +"` or `"+"`). This PR fixes that.

fix: handle inputs like `"2 +"` in `StackPostfixNotation`

---

DIRECTORY.md
pom.xml
src/main/java/com/thealgorithms/maths/AmicableNumber.java
src/test/java/com/thealgorithms/maths/AmicableNumberTest.java

Changes:
- AmicableNumber refactoring
- Added unit tests
- Added apache's `commons-lang3` dependency to `pom.xml`

AmicableNumber refactoring

---

src/main/java/com/thealgorithms/maths/Factorial.java
src/test/java/com/thealgorithms/maths/FactorialTest.java

Factorial refactoring, added unit tests

---

src/main/java/com/thealgorithms/maths/Factorial.java

Following @siriak [suggestion](https://github.com/TheAlgorithms/Java/pull/4266/files#r1278050924) in #4266, I create this PR, which:
- explicitly defines the default constructor of `Factorial` as `private` - it does not make sense to create any instances of this class (because it has only static method and no members),
- marks the class `Factorial` as `final` - it does not make sense to have any class extending it.

refactor: make `Factorial` a proper utility class

---

src/main/java/com/thealgorithms/maths/GenericRoot.java
src/test/java/com/thealgorithms/maths/GenericRootTest.java

This PR:
- adds tests for the class [`GenericRoot`](https://github.com/TheAlgorithms/Java/blob/087d523ed0e747adb9a681499f40d427c84358d2/src/main/java/com/thealgorithms/maths/GenericRoot.java#L7),
- does some refactoring if it.
I do not know about the general policy here: should I use the existing methods from [`SumOfDigits`](https://github.com/TheAlgorithms/Java/blob/087d523ed0e747adb9a681499f40d427c84358d2/src/main/java/com/thealgorithms/maths/SumOfDigits.java#L3)?

tests: add tests for `GenericRoot`

---

src/main/java/com/thealgorithms/scheduling/PreemptivePriorityScheduling.java
src/test/java/com/thealgorithms/scheduling/PreemptivePrioritySchedulingTest.java

Preemptive Priority Scheduling Algorithm added

---

.gitpod.dockerfile

This PR configures `clang-format-16` in gitpod (cf. #4343).

chore: configure `clang-format-16` in gitpod

---

src/main/java/com/thealgorithms/misc/PalindromeSinglyLinkedList.java
src/test/java/com/thealgorithms/misc/PalindromeSinglyLinkedListTest.java

As mentioned in #4327, the implementation of [`PalindromeSinglyLinkedList.isPalindrome`](https://github.com/TheAlgorithms/Java/blob/ea15f2bd98c24150b590fac800e386d2f98b203d/src/main/java/com/thealgorithms/misc/PalindromeSinglyLinkedList.java#L32) has unnecessarily high time complexity `O(n^2)`. Thanks to #4334, the implementation could be changed to optimal `O(n)`. This PR does that and makes `PalindromeSinglyLinkedList` a proper utility class.

style: cleanup `PalindromeSinglyLinkedList`

---

.github/workflows/build.yml
.github/workflows/clang-format-lint.yml

The `actions/checkout@v4` was recently [released](https://github.com/actions/checkout/releases/tag/v4.0.0). This PR makes a suitable update.
Please note the following inconsistency:
https://github.com/TheAlgorithms/Java/blob/09950d6097ea7b2590fb80336d144ee402e61226/.github/workflows/update_directory.yml#L27

chore: update `actions/checkout` to `v4`

---

src/main/java/com/thealgorithms/io/BufferedReader.java
src/main/java/com/thealgorithms/maths/AmicableNumber.java

Fixed a bit of typos in some files. Not that much of changes done, but I will make sure to fix all of them.

Fixed Small typos :-)

---

src/main/java/com/thealgorithms/backtracking/FloodFill.java
src/test/java/com/thealgorithms/backtracking/FloodFillTest.java

Fixed #4358 
Fixed case when both newColor and oldColor is passed as same integer causing infinite recursion by adding extra base condition.
Also added testcase for same and after that ran all testcase, which resulted as all passed.

#4358 Fix : Floodfill infinite recursion due to same color

---

src/main/java/com/thealgorithms/backtracking/FloodFill.java

As mentioned in #4359, here is a bit of _linting_ of `FloodFill`.

style: linting of `FloodFill`

---

src/main/java/com/thealgorithms/maths/ParseInteger.java
src/test/java/com/thealgorithms/maths/ParseIntegerTest.java

This PR simplifies method [`ParseInteger.parseInt`](https://github.com/TheAlgorithms/Java/blob/5bb54977fe63107c22116215023cb18fc5500113/src/main/java/com/thealgorithms/maths/ParseInteger.java#L12). It also does some _basic linting_ and adds a missing test case.

refactor: simplify `ParseInteger`

---

src/test/java/com/thealgorithms/maths/FactorialTest.java

This PR changes the way how `assertEquals` is imported.

style: avoid wildcard imports

---

src/main/java/com/thealgorithms/maths/FindMin.java
src/test/java/com/thealgorithms/maths/FactorialTest.java

This change schould make FindMin more efficient.

FindMin more efficient

---

src/main/java/com/thealgorithms/maths/FindMin.java

Makes the class [`FindMin`](https://github.com/TheAlgorithms/Java/blob/ad4be217d43fdaa38c994d7397ba5e732de26096/src/main/java/com/thealgorithms/maths/FindMin.java) a _proper utility class_ and does some basic linting.

style: make `FindMin` a proper utilty class

---

src/main/java/com/thealgorithms/maths/FindMaxRecursion.java

Adding so the base function does not need a second parameter len and removing Math.max function as it ruins the purpose of the algorithem

remove array len + Math.max

---

src/test/java/com/thealgorithms/maths/FindMinTest.java

#4388 has updated testcases in `FindMinTest`, but for all test arrays the minimal value is at index 0. This PR fixes that.
@siriak, @lukasb1b please have a look.

tests: add test case with minimum not at index 0

---

src/main/java/com/thealgorithms/strings/Pangram.java
src/test/java/com/thealgorithms/strings/PangramTest.java

A simple separate function isPangramOrNot(String s) has been created which implements the Pangram checking of a string using Java Collection Framework approach.

Update Pangram.java using Java Collections

---

src/main/java/com/thealgorithms/searches/RecursiveBinarySearch.java
src/test/java/com/thealgorithms/searches/RecursiveBinarySearchTest.java

Import Package into the RecursiveBinarySearchTest and RecursiveBinarySearch

Issue #4706 Solved

---

src/main/java/com/thealgorithms/datastructures/stacks/README.md

updated stack readme.md file

---

.github/pull_request_template.md
CONTRIBUTING.md

adding formatting steps in pull request template

---

src/main/java/com/thealgorithms/maths/MaxValue.java
src/test/java/com/thealgorithms/maths/MaxValueTest.java

Add MaxValueTest and remove main from MaxValue

---

src/main/java/com/thealgorithms/greedyalgorithms/FractionalKnapsack.java

Fixes one of the issues detected by merging #4966. Similar to #4970.

Use explicit cast to `int` in `FractionalKnapsack`

---

src/main/java/com/thealgorithms/maths/Armstrong.java

Fixes one of the issues detected by merging #4966. Similar to #4970 and #4971.

Explicitly cast result of `Math.pow` to `long` in `Armstrong`

---

DIRECTORY.md
src/main/java/com/thealgorithms/datastructures/crdt/GSet.java
src/test/java/com/thealgorithms/datastructures/crdt/GSetTest.java

Fixed bug in the `compare()` method where the subet check is not performed on the actual object.
from:
```java
public boolean compare(GSet<T> other) {
return elements.containsAll(other.elements);
}
```
to:
```java
public boolean compare(GSet<T> other) {
return other.elements.containsAll(elements);
}
```
See:
compare (S, T) : boolean b
let b = (S.A ⊆ T.A)
https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type

Fixed wrong compare() method for subset check (S.A ⊆ T.A)

---

DIRECTORY.md
src/main/java/com/thealgorithms/datastructures/crdt/TwoPSet.java
src/test/java/com/thealgorithms/datastructures/crdt/TwoPSetTest.java

This PR updates the `TwoPSet.java` and `TwoPSetTest.java` to use Generics `TwoPSet<T>` instead of `TwoPSet<String>` to make the class more flexible and to allow the use of custom objects with `TwoPSet`.
````java
public class TwoPSet<T> {
private final Set<T> setA;
private final Set<T> setR;
````

Updated TwoPSet to use Generics instead of Strings

---

src/main/java/com/thealgorithms/bitmanipulation/SetKthBit.java
src/test/java/com/thealgorithms/bitmanipulation/SetKthBitTest.java

Add Set Kth Bit

---

src/main/java/com/thealgorithms/maths/SumOfDigits.java
src/test/java/com/thealgorithms/maths/SumOfDigitsTest.java

This PR is a pretty straightforward cleanup of the `SumOfDigits`, namely it:
- uses `Math.abs`,
- makes `sumOfDigitsFast` more _functional_,
- rewrites tests as _parameterized test_.

Cleanup `SumOfDigits` and its tests

---

src/test/java/com/thealgorithms/others/BoyerMooreTest.java

This PR removed unused import from `BoyerMooreTest`. Similar to #5010.

Remove unused imports from `BoyerMooreTest`

---

src/main/java/com/thealgorithms/backtracking/MColoring.java
src/main/java/com/thealgorithms/ciphers/ProductCipher.java
src/main/java/com/thealgorithms/datastructures/graphs/BellmanFord.java
src/main/java/com/thealgorithms/datastructures/stacks/ReverseStack.java
src/main/java/com/thealgorithms/maths/NonRepeatingElement.java
src/main/java/com/thealgorithms/others/InsertDeleteInArray.java
src/main/java/com/thealgorithms/searches/RecursiveBinarySearch.java

Close `Scanner` to avoid resource leak

---

.gitpod.dockerfile
src/main/java/com/thealgorithms/conversions/IntegerToRoman.java
src/main/java/com/thealgorithms/conversions/RomanToInteger.java
src/main/java/com/thealgorithms/conversions/TurkishToLatinConversion.java
src/main/java/com/thealgorithms/dynamicprogramming/Fibonacci.java
src/main/java/com/thealgorithms/dynamicprogramming/MatrixChainMultiplication.java
src/main/java/com/thealgorithms/greedyalgorithms/ActivitySelection.java
src/main/java/com/thealgorithms/greedyalgorithms/CoinChange.java
src/main/java/com/thealgorithms/greedyalgorithms/FractionalKnapsack.java
src/main/java/com/thealgorithms/greedyalgorithms/JobSequencing.java
src/main/java/com/thealgorithms/searches/UnionFind.java
src/main/java/com/thealgorithms/sorts/DNFSort.java
src/main/java/com/thealgorithms/strings/Pangram.java

Cleaned up code for some packages

---

DIRECTORY.md
src/main/java/com/thealgorithms/backtracking/ParenthesesGenerator.java
src/test/java/com/thealgorithms/backtracking/ParenthesesGeneratorTest.java

Implement Parentheses Generator

---

.github/workflows/build.yml
pom.xml

With this change, one can generate a coverage report by calling any command like
```shell
mvn test
```
A html, csv and xml reports are generated (this is useful for local development in my opinion).
The xml is uploaded to [codecov](https://app.codecov.io/gh/TheAlgorithms/Java/).
Please note that this change still uses `codecov/codecov-action` in `v3` - the update requires adding a token, so it will be done in a separate PR.

chore: generate coverage report and upload it to codecov

---

.github/workflows/build.yml

Same as TheAlgorithms/Rust#670 - it contains the description of the problem.
~Before merging, please add the token from https://app.codecov.io/gh/TheAlgorithms/Java/settings as `CODECOV_TOKEN` into the repo secrets, including dependabot secrets.~ [Token is added](https://github.com/TheAlgorithms/Java/pull/5100#pullrequestreview-1984596033).
@siriak - your help will be needed here.
Continuation of #5098.

chore: update `codecov/codecov-action` to `v4`

---

.gitpod.dockerfile
DIRECTORY.md

After #5092 build of the gitpod image fails at installing `clang-format`. This PR fixes that by updating the `clang-format` tag. @BamaCharanChhandogi please have a look.

fix: update `clang-format` tag

---

src/main/java/com/thealgorithms/maths/NumberOfDigits.java
src/test/java/com/thealgorithms/maths/NumberOfDigitsTest.java

I added some tests for the class computing number of digits.

Added tests for NumberOfDigits

---

src/main/java/com/thealgorithms/maths/FactorialRecursion.java
src/test/java/com/thealgorithms/maths/FactorialRecursionTest.java

Added tests for `FactorialRecursion`.

Added tests for `FactorialRecursion`

---

src/test/java/com/thealgorithms/maths/NumberOfDigitsTest.java

I removed unused import following the suggestion.

Remove unused import.

---

src/main/java/com/thealgorithms/maths/Mode.java
src/test/java/com/thealgorithms/maths/ModeTest.java

This PR adds tests of the `Mode` class. It also _cleans it up_ by removing the `main` method, making it a _proper utility_ and marking the input argument of `Mode.mode` as `final`.

tests: add tests of `Mode`

---

checkstyle.xml
src/main/java/com/thealgorithms/sorts/CircleSort.java
src/test/java/com/thealgorithms/ciphers/DESTest.java

Related to #5119.
#5121 adds the missing tests for the `CircleSort`.

style: enable `EmptyStatement`

---

.github/workflows/build.yml
pom.xml
spotbugs-exclude.xml

This PR configures [`SpotBugs`](https://spotbugs.github.io/). Some of the _bugs_ are temporally excluded in `spotbugs-exclude.xml`.
Similar to #5110.
@siriak, @BamaCharanChhandogi please have a look.

chore: configure SpotBugs

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/dynamicprogramming/LongestIncreasingSubsequence.java
src/main/java/com/thealgorithms/misc/RangeInSortedArray.java
src/main/java/com/thealgorithms/sorts/BinaryInsertionSort.java
src/main/java/com/thealgorithms/sorts/SlowSort.java

This PR includes `IM_AVERAGE_COMPUTATION_COULD_OVERFLOW` SpotBugs rule.
Related to #5122.

style: include `IM_AVERAGE_COMPUTATION_COULD_OVERFLOW`

---

checkstyle.xml
src/main/java/com/thealgorithms/bitmanipulation/HighestSetBit.java
src/main/java/com/thealgorithms/others/CountWords.java
src/main/java/com/thealgorithms/others/EulersFunction.java
src/main/java/com/thealgorithms/others/LowestBasePalindrome.java
src/main/java/com/thealgorithms/others/SieveOfEratosthenes.java
src/main/java/com/thealgorithms/others/cn/HammingDistance.java

I enabled `ModifierOrder` in checkstyle.

style: enable `ModifierOrder` in checkstyle

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/sorts/MergeSortRecursive.java

This PR _includes_ the `UC_USELESS_OBJECT` SpotBugs rule. The removed `App` class was redundant.
Related to #5122.

style: include `UC_USELESS_OBJECT`

---

checkstyle.xml
src/main/java/com/thealgorithms/backtracking/KnightsTour.java
src/main/java/com/thealgorithms/ciphers/Polybius.java
src/main/java/com/thealgorithms/conversions/DecimalToHexaDecimal.java
src/main/java/com/thealgorithms/conversions/IntegerToRoman.java
src/main/java/com/thealgorithms/conversions/RomanToInteger.java
src/main/java/com/thealgorithms/datastructures/trees/LCA.java
src/main/java/com/thealgorithms/dynamicprogramming/Fibonacci.java
src/main/java/com/thealgorithms/dynamicprogramming/MatrixChainMultiplication.java
src/main/java/com/thealgorithms/maths/FindKthNumber.java
src/main/java/com/thealgorithms/matrixexponentiation/Fibonacci.java
src/main/java/com/thealgorithms/others/Conway.java
src/main/java/com/thealgorithms/others/RabinKarp.java
src/main/java/com/thealgorithms/searches/RabinKarpAlgorithm.java
src/main/java/com/thealgorithms/sorts/BogoSort.java
src/main/java/com/thealgorithms/sorts/SortUtilsRandomGenerator.java

style: enable `ConstantName` in checkstyle

---

src/main/java/com/thealgorithms/dynamicprogramming/LevenshteinDistance.java
src/test/java/com/thealgorithms/dynamicprogramming/LevenshteinDistanceTests.java

- Rewrite the original levenshtein distance implementation in functional style
- Add optimized version of levenshtein distance

Refactor Levenshtein distance implementation

---

pom.xml
spotbugs-exclude.xml

This PR configures [`fb-contrib`](https://central.sonatype.com/artifact/com.mebigfatguy.fb-contrib/fb-contrib).
Continuation of #5122.

chore: configure SpotBugs plugin `fb-contrib`

---

src/main/java/com/thealgorithms/sorts/CircleSort.java
src/test/java/com/thealgorithms/sorts/CircleSortTest.java

This PR adds tests for `CircleSort` and fixes the _infinite_ loop occurring for empty input.

fix: handle empty inputs in `CircleSort`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/sorts/LinkListSort.java
src/main/java/com/thealgorithms/sorts/MergeSort.java
src/main/java/com/thealgorithms/sorts/TimSort.java

This PR includes `ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD` SpotBugs rule.
Related to #5122.

style: include `ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD`

---

checkstyle.xml
src/main/java/com/thealgorithms/ciphers/DES.java
src/test/java/com/thealgorithms/bitmanipulation/NonRepeatingNumberFinderTest.java
src/test/java/com/thealgorithms/greedyalgorithms/ActivitySelectionTest.java
src/test/java/com/thealgorithms/greedyalgorithms/FractionalKnapsackTest.java

style: enable `ArrayTypeStyle` in checkstyle

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/ciphers/a5/CompositeLFSR.java
src/main/java/com/thealgorithms/datastructures/graphs/DIJSKSTRAS_ALGORITHM.java
src/main/java/com/thealgorithms/datastructures/graphs/PrimMST.java
src/main/java/com/thealgorithms/greedyalgorithms/JobSequencing.java
src/main/java/com/thealgorithms/sorts/CircleSort.java
src/test/java/com/thealgorithms/bitmanipulation/IsEvenTest.java
src/test/java/com/thealgorithms/dynamicprogramming/SumOfSubsetTest.java
src/test/java/com/thealgorithms/maths/PythagoreanTripleTest.java
src/test/java/com/thealgorithms/others/TwoPointersTest.java
src/test/java/com/thealgorithms/strings/ValidParenthesesTest.java

style: include `NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/heaps/EmptyHeapException.java
src/main/java/com/thealgorithms/datastructures/heaps/MaxHeap.java
src/main/java/com/thealgorithms/datastructures/heaps/MinHeap.java

style: include `LEST_LOST_EXCEPTION_STACK_TRACE`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMapCuckooHashing.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/MainCuckooHashing.java
src/main/java/com/thealgorithms/datastructures/lists/CreateAndDetectLoop.java
src/main/java/com/thealgorithms/others/TowerOfHanoi.java
src/main/java/com/thealgorithms/searches/MonteCarloTreeSearch.java
src/main/java/com/thealgorithms/sorts/InsertionSort.java

style: include `VA_FORMAT_STRING_USES_NEWLINE`

---

checkstyle.xml
src/main/java/com/thealgorithms/datastructures/bags/Bag.java
src/main/java/com/thealgorithms/datastructures/dynamicarray/DynamicArray.java
src/main/java/com/thealgorithms/datastructures/graphs/WelshPowell.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/Intersection.java
src/main/java/com/thealgorithms/datastructures/heaps/LeftistHeap.java
src/main/java/com/thealgorithms/datastructures/lists/CircleLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/Merge_K_SortedLinkedlist.java
src/main/java/com/thealgorithms/datastructures/trees/GenericTree.java
src/main/java/com/thealgorithms/datastructures/trees/TreeRandomNode.java
src/main/java/com/thealgorithms/geometry/GrahamScan.java
src/main/java/com/thealgorithms/others/RotateMatrixBy90Degrees.java

style: enable `FinalClass` in checkstyle

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/dynamicprogramming/SubsetCount.java
src/test/java/com/thealgorithms/dynamicprogramming/SubsetCountTest.java

This change will allow to _include_ `MS_SHOULD_BE_FINAL`. Continuation of #5122.

style: make `SubsetCount` a proper utility

---

pmd-exclude.properties
src/main/java/com/thealgorithms/maths/DudeneyNumber.java
src/test/java/com/thealgorithms/maths/DudeneyNumberTest.java

This PR _cleanups_ `DudeneyNumber` and its tests.

refactor: cleanup `DudeneyNumber`

---

checkstyle.xml
src/main/java/com/thealgorithms/datastructures/trees/KDTree.java

style: enable EqualsHashCode in checkstyle

---

src/main/java/com/thealgorithms/datastructures/trees/KDTree.java

Follows https://github.com/TheAlgorithms/Java/pull/5157#issuecomment-2106185497.

refactor: simplify logic of `Point::equals` in `KDTree`

---

checkstyle.xml
pmd-exclude.properties
src/main/java/com/thealgorithms/ciphers/ProductCipher.java
src/main/java/com/thealgorithms/datastructures/dynamicarray/DynamicArray.java
src/main/java/com/thealgorithms/datastructures/heaps/LeftistHeap.java
src/main/java/com/thealgorithms/datastructures/queues/CircularQueue.java
src/main/java/com/thealgorithms/datastructures/queues/LinkedQueue.java
src/main/java/com/thealgorithms/datastructures/trees/PrintTopViewofTree.java
src/main/java/com/thealgorithms/datastructures/trees/RedBlackBST.java
src/main/java/com/thealgorithms/dynamicprogramming/KnapsackMemoization.java
src/main/java/com/thealgorithms/dynamicprogramming/LongestAlternatingSubsequence.java
src/main/java/com/thealgorithms/dynamicprogramming/NewManShanksPrime.java
src/main/java/com/thealgorithms/maths/LeastCommonMultiple.java
src/main/java/com/thealgorithms/others/SieveOfEratosthenes.java
src/main/java/com/thealgorithms/searches/UnionFind.java

style: enabled `InnerAssignment` in checkstyle

---

src/main/java/com/thealgorithms/dynamicprogramming/LongestIncreasingSubsequence.java
src/test/java/com/thealgorithms/dynamicprogramming/LongestIncreasingSubsequenceTests.java

This PR adds missing tests, fixes `LongestIncreasingSubsequence::findLISLen` to handle constant and empty inputs and removes the `main` method from `LongestIncreasingSubsequence`.

fix: constant inputs in `LongestIncreasingSubsequence::findLISLen`

---

pom.xml

This PR enables the compiler warnings and treats them as errors. The goal is to remove all of the lines _suppressing_ some of the warnings, i.e.
```xml
<arg>-Xlint:-auxiliaryclass</arg>
<arg>-Xlint:-rawtypes</arg>
<arg>-Xlint:-serial</arg>
<arg>-Xlint:-try</arg>
<arg>-Xlint:-unchecked</arg>
```
In case of Java 21 (#5163) two additional warnings needs to be suppressed (Java 17 does not know them):
```xml
<arg>-Xlint:-lossy-conversions</arg>
<arg>-Xlint:-this-escape</arg>
```
Similar to:
- #5110
- #5122
- #5155

style: enable compiler warnings and treat them as errors

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/build.yml
.github/workflows/codeql.yml
.gitpod.dockerfile
pom.xml

This PR updates the used version of Java to 21. Similar to #2819.

chore: migrate to java 21

---

pmd-exclude.properties
spotbugs-exclude.xml

Thanks to #5157 we can enable these checks in SpotBugs and PMD.

style: enable `OverrideBothEqualsAndHashcode` like checks

---

pom.xml
src/main/java/com/thealgorithms/ciphers/RSA.java
src/main/java/com/thealgorithms/datastructures/heaps/MaxHeap.java
src/main/java/com/thealgorithms/datastructures/heaps/MinHeap.java
src/main/java/com/thealgorithms/datastructures/lists/DoublyLinkedList.java
src/main/java/com/thealgorithms/datastructures/trees/SegmentTree.java

This PR _includes_ `this-escape` into the active compiler warnings. The changes in the `*.java` files are _minimal_.
Continuation of #5165.

style: do not suppress `this-escape`

---

checkstyle.xml
src/main/java/com/thealgorithms/maths/DudeneyNumber.java
src/main/java/com/thealgorithms/sorts/SimpleSort.java

Enabled LocalFinalVariableName in Checkstyle

---

checkstyle.xml
src/main/java/com/thealgorithms/ciphers/DES.java
src/main/java/com/thealgorithms/dynamicprogramming/FordFulkerson.java
src/main/java/com/thealgorithms/others/RabinKarp.java
src/main/java/com/thealgorithms/others/StringMatchFiniteAutomata.java

style: enable `StaticVariableName` in checkstyle

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/ciphers/DES.java

style: include `SPP_TOSTRING_ON_STRING`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/scheduling/FCFSScheduling.java
src/main/java/com/thealgorithms/scheduling/RRScheduling.java

style: include `LII_LIST_INDEXED_ITERATING`

---

checkstyle.xml
src/main/java/com/thealgorithms/ciphers/Blowfish.java
src/main/java/com/thealgorithms/conversions/HexaDecimalToBinary.java
src/main/java/com/thealgorithms/datastructures/crdt/GCounter.java
src/main/java/com/thealgorithms/datastructures/crdt/PNCounter.java
src/main/java/com/thealgorithms/datastructures/graphs/FloydWarshall.java
src/main/java/com/thealgorithms/datastructures/graphs/HamiltonianCycle.java
src/main/java/com/thealgorithms/datastructures/graphs/MatrixGraphs.java
src/main/java/com/thealgorithms/datastructures/graphs/TarjansAlgorithm.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMapCuckooHashing.java
src/main/java/com/thealgorithms/datastructures/queues/GenericArrayListQueue.java
src/main/java/com/thealgorithms/datastructures/trees/FenwickTree.java
src/main/java/com/thealgorithms/datastructures/trees/RedBlackBST.java
src/main/java/com/thealgorithms/datastructures/trees/SegmentTree.java
src/main/java/com/thealgorithms/dynamicprogramming/OptimalJobScheduling.java
src/test/java/com/thealgorithms/divideandconquer/StrassenMatrixMultiplicationTest.java
src/test/java/com/thealgorithms/sorts/BinaryInsertionSortTest.java

style: enable `MemberName` in checkstyle

---

checkstyle.xml
src/main/java/com/thealgorithms/backtracking/PowerSum.java
src/main/java/com/thealgorithms/conversions/RomanToInteger.java
src/main/java/com/thealgorithms/datastructures/graphs/BipartiteGrapfDFS.java
src/main/java/com/thealgorithms/datastructures/graphs/FloydWarshall.java
src/main/java/com/thealgorithms/datastructures/graphs/TarjansAlgorithm.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArray.java
src/main/java/com/thealgorithms/datastructures/lists/Merge_K_SortedLinkedlist.java
src/main/java/com/thealgorithms/datastructures/trees/SegmentTree.java
src/main/java/com/thealgorithms/divideandconquer/BinaryExponentiation.java
src/main/java/com/thealgorithms/dynamicprogramming/BoundaryFill.java
src/main/java/com/thealgorithms/dynamicprogramming/BruteForceKnapsack.java
src/main/java/com/thealgorithms/dynamicprogramming/KadaneAlgorithm.java
src/main/java/com/thealgorithms/dynamicprogramming/NewManShanksPrime.java
src/main/java/com/thealgorithms/dynamicprogramming/SumOfSubset.java
src/main/java/com/thealgorithms/maths/Convolution.java
src/main/java/com/thealgorithms/maths/Gaussian.java
src/main/java/com/thealgorithms/maths/PronicNumber.java
src/main/java/com/thealgorithms/maths/VectorCrossProduct.java
src/main/java/com/thealgorithms/others/KMP.java
src/main/java/com/thealgorithms/others/PasswordGen.java
src/main/java/com/thealgorithms/scheduling/SJFScheduling.java
src/main/java/com/thealgorithms/sorts/BitonicSort.java

style: enable `ParameterName` in CheckStyle.

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/conversions/HexaDecimalToBinary.java
src/main/java/com/thealgorithms/datastructures/trees/RedBlackBST.java

style: include `SS_SHOULD_BE_STATIC`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/queues/LinkedQueue.java

style: include `IT_NO_SUCH_ELEMENT`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/others/BFPRT.java
src/main/java/com/thealgorithms/others/BankersAlgorithm.java
src/main/java/com/thealgorithms/others/ReturnSubsequence.java
src/main/java/com/thealgorithms/sorts/RadixSort.java

style: include `MAC_MANUAL_ARRAY_COPY`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/maths/SimpsonIntegration.java

style: include `IM_BAD_CHECK_FOR_ODD`

---

pom.xml
src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
src/test/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumberTest.java

refactor: redesign `LetterCombinationsOfPhoneNumber`

---

src/main/java/com/thealgorithms/others/StringMatchFiniteAutomata.java
src/test/java/com/thealgorithms/others/StringMatchFiniteAutomataTest.java

refactor: redesign `StringMatchFiniteAutomata`

---

src/main/java/com/thealgorithms/sorts/BitonicSort.java
src/main/java/com/thealgorithms/sorts/SortUtils.java
src/test/java/com/thealgorithms/sorts/BitonicSortTest.java

The previous sorting algorithm only worked with arrays whose sizes were powers of two. This issue has been fixed.
Additionally, the code has been refactored to follow a common approach, and tests for the sort function have been added.

Improving BitonicSort

---

src/main/java/com/thealgorithms/sorts/DualPivotQuickSort.java
src/main/java/com/thealgorithms/sorts/ExchangeSort.java
src/main/java/com/thealgorithms/sorts/IntrospectiveSort.java
src/main/java/com/thealgorithms/sorts/SelectionSort.java
src/main/java/com/thealgorithms/sorts/SimpleSort.java
src/main/java/com/thealgorithms/sorts/SlowSort.java
src/main/java/com/thealgorithms/sorts/SwapSort.java

In the sorting algorithms, there are several different swap methods that duplicate each other. However, the method already exists in SortUtils.swap. These changes consolidate the various methods into a single, common one.

Replace the various swap method variants with SortUtils.swap

---

src/main/java/com/thealgorithms/sorts/HeapSort.java

The HeapSort class had duplicated methods for less and swap, which already exist in SortUtils. 
It is better to use the common methods instead of the old ones. 
This pull request also includes some renaming for clarity.

Refactor: Replace Swap and Comparison Methods with SortUtils Utility Methods

---

src/main/java/com/thealgorithms/sorts/SwapSort.java
src/test/java/com/thealgorithms/sorts/SwapSortTest.java

There was an issue where this sorting implementation could enter an infinite loop, such as in the test shouldAcceptWhenArrayWithDuplicateValueIsPassed. 
The index variable was not being updated correctly.
The index may never reach len - 1 due to the flawed logic, leading to a potential infinite loop. 
This fix addresses the issue and adds the missing test for this sorting algorithm.
Fixes #5249.

fix: avoid infinite loop in `SwapSort`

---

checkstyle.xml
src/main/java/com/thealgorithms/dynamicprogramming/UniquePaths.java
src/test/java/com/thealgorithms/maths/MeansTest.java

style: enable `WhitespaceAround` in checktyle

---

spotbugs-exclude.xml

Continuation of #5122. The necessary code changes were probably done in:
- #5182
- #5214

style: include `NM_CLASS_NAMING_CONVENTION` and `NM_METHOD_NAMING_CONVENTION`

---

src/main/java/com/thealgorithms/sorts/SortUtils.java
src/test/java/com/thealgorithms/sorts/SortUtilsTest.java

Adding check if indeces are not equals, for swap method in SortUtils.
According to this suggestion https://github.com/TheAlgorithms/Java/pull/5265#discussion_r1659320131

feat: optimize `SortUtils.swap` by skipping operations for equal indices

---

src/main/java/com/thealgorithms/sorts/BeadSort.java
src/test/java/com/thealgorithms/sorts/BeadSortTest.java

Cleanup BeadSort and BeadSortTest, adding javadocs.

refactor: cleanup BeadSort

---

src/main/java/com/thealgorithms/sorts/ShellSort.java
src/test/java/com/thealgorithms/sorts/ShellSortTest.java

Improving ShellSort code readability
Refactor the code by moving parts of it into well-named methods to improve readability and maintainability.
Adopt a more general testing approach to ensure better test coverage.

refactor: cleanup `ShellSort`

---

src/main/java/com/thealgorithms/sorts/CombSort.java
src/test/java/com/thealgorithms/sorts/CombSortTest.java

Cleanup CombSort class, removing redundant code.
Improve code readability.
Removing redundant useless comments.
Refactoring test to common sort approach, it has more tests and will improve code coverage.

refactor: cleanup `CombSort`

---

src/main/java/com/thealgorithms/sorts/DutchNationalFlagSort.java
src/main/java/com/thealgorithms/sorts/GnomeSort.java
src/main/java/com/thealgorithms/sorts/HeapSort.java
src/main/java/com/thealgorithms/sorts/QuickSort.java
src/main/java/com/thealgorithms/sorts/SelectionSortRecursive.java
src/main/java/com/thealgorithms/sorts/StoogeSort.java
src/main/java/com/thealgorithms/sorts/StrandSort.java
src/main/java/com/thealgorithms/sorts/SwapSort.java
src/main/java/com/thealgorithms/sorts/TimSort.java

Some simple improvements were introduced:
- changing names of different naming of sorted array to just simple `array`
- making some variables like `final` to make them not editable and mark this
- and some minor other changes

refactor: simple improvements and cleanup for different sorts

---

src/main/java/com/thealgorithms/sorts/IntrospectiveSort.java
src/test/java/com/thealgorithms/sorts/IntrospectiveSortTest.java

Improving code readability, simplify in some places
Adding general sorting test as it provides better coverage
Adding Java docs with description of methods

refactor: `IntrospectiveSort`

---

src/main/java/com/thealgorithms/sorts/CycleSort.java

CycleSort cleanup
Code readability improvements

refactor: cleanup `CycleSort`

---

src/main/java/com/thealgorithms/conversions/DecimalToOctal.java
src/test/java/com/thealgorithms/conversions/DecimalToOctalTest.java

Refactoring BinaryToHexadecimal.
Adding tests for incorrect cases.

refactor: `DecimalToOctal`

---

src/main/java/com/thealgorithms/conversions/BinaryToHexadecimal.java
src/test/java/com/thealgorithms/conversions/BinaryToHexadecimalTest.java

Refactoring BinaryToHexadecimal.
Adding tests for incorrect cases.

refactor: `BinaryToHexadecimal`

---

src/main/java/com/thealgorithms/conversions/BinaryToDecimal.java
src/test/java/com/thealgorithms/conversions/BinaryToDecimalTest.java

Refactoring BinaryToDecimal.
Adding tests for incorrect cases.

refactor: `BinaryToDecimal`

---

src/main/java/com/thealgorithms/datastructures/queues/CircularQueue.java
src/test/java/com/thealgorithms/datastructures/queues/CircularQueueTest.java

Make CircularQueue generic.
Added tests.

refactor: `CircularQueue`

---

src/main/java/com/thealgorithms/datastructures/queues/Deque.java
src/test/java/com/thealgorithms/datastructures/queues/DequeTest.java

Make Deque generic.
Added tests.

refactor: `Deque`

---

src/test/java/com/thealgorithms/maths/GCDRecursionTest.java

test: `GCDRecursion`

---

src/test/java/com/thealgorithms/stacks/LargestRectangleTest.java

Added test for LargestRectangle, to improve code coverage

test: `LargestRectangle`

---

src/main/java/com/thealgorithms/datastructures/caches/LFUCache.java

Refactoring LFUCache.
Javadocs improvements.

refactor: `LFUCache`

---

src/main/java/com/thealgorithms/others/FloydTriangle.java
src/test/java/com/thealgorithms/others/FloydTriangleTest.java

Improving readability.
Adding tests.

refactor: `FloydTriangle`

---

src/main/java/com/thealgorithms/backtracking/NQueens.java
src/test/java/com/thealgorithms/backtracking/NQueensTest.java

test: `NQueensTest`

---

src/main/java/com/thealgorithms/conversions/HexToOct.java
src/test/java/com/thealgorithms/conversions/HexToOctTest.java

Improving readability.
Adding tests.

refactor: `HexToOct`

---

src/main/java/com/thealgorithms/others/PasswordGen.java
src/test/java/com/thealgorithms/others/PasswordGenTest.java

Refactor PasswordGen.
Adding tests.

refactor: `PasswordGen`

---

src/main/java/com/thealgorithms/others/GaussLegendre.java
src/main/java/com/thealgorithms/strings/Isomorphic.java

Fix few typos in GaussLegendre and Isomorphic classes, and removing redundant generics parameters.

refactor: fix typo

---

src/test/java/com/thealgorithms/maths/ReverseNumberTest.java

Cleanup ReverseNumberTest.
Change this it to @ParameterizedTest and @CsvSource.

test: cleanup `ReverseNumberTest`

---

src/test/java/com/thealgorithms/maths/PrimeFactorizationTest.java

Class cleanup.
Added more test cases.

test: cleanup `PrimeFactorizationTest`

---

src/main/java/com/thealgorithms/others/ReverseStackUsingRecursion.java
src/test/java/com/thealgorithms/others/ReverseStackUsingRecursionTest.java

refactor: `ReverseStackUsingRecursion`

---

src/main/java/com/thealgorithms/others/RemoveDuplicateFromString.java
src/test/java/com/thealgorithms/others/RemoveDuplicateFromStringTest.java

refactor: `RemoveDuplicateFromString`

---

src/main/java/com/thealgorithms/others/EulersFunction.java
src/test/java/com/thealgorithms/others/EulersFunctionTest.java

Javadocs improvements.
Tests improvements.

refactor: cleanup `EulersFunction`

---

src/main/java/com/thealgorithms/others/ArrayLeftRotation.java
src/test/java/com/thealgorithms/others/ArrayLeftRotationTest.java

refactor: `ArrayLeftRotationTest`

---

src/main/java/com/thealgorithms/stacks/BalancedBrackets.java
src/test/java/com/thealgorithms/stacks/BalancedBracketsTest.java

Some improvements.
Added tests.

refactor: `BalancedBrackets`

---

src/main/java/com/thealgorithms/dynamicprogramming/LongestAlternatingSubsequence.java
src/test/java/com/thealgorithms/dynamicprogramming/LongestAlternatingSubsequenceTest.java

test: `LongestAlternatingSubsequenceTest`

---

src/main/java/com/thealgorithms/others/LineSweep.java
src/test/java/com/thealgorithms/others/LineSweepTest.java

Class cleanup.
New tests added.
Tests refactored.

refactor: `LineSweep`

---

src/main/java/com/thealgorithms/others/BoyerMoore.java
src/test/java/com/thealgorithms/others/BoyerMooreTest.java

refactor: `BoyerMoore`

---

src/main/java/com/thealgorithms/stacks/StackPostfixNotation.java
src/test/java/com/thealgorithms/stacks/StackPostfixNotationTest.java

Change Map.ofEntries test to Parametrized tests.
Documentation changes.

refactor: `StackPostfixNotation`

---

src/main/java/com/thealgorithms/stacks/InfixToPostfix.java
src/test/java/com/thealgorithms/stacks/InfixToPostfixTest.java

Refactor InfixToPostfix
Added tests.
BalancedBrackets.isBalanced works only with "(){}[]<>", to use it need to remove other characters and check.

refactor: `InfixToPostfix`

---

src/main/java/com/thealgorithms/dynamicprogramming/RegexMatching.java
src/test/java/com/thealgorithms/dynamicprogramming/RegexMatchingTest.java

Added javadocs.
Added RegexMatchingTest.

test: `RegexMatchingTest`

---

src/main/java/com/thealgorithms/strings/LongestPalindromicSubstring.java
src/test/java/com/thealgorithms/strings/LongestPalindromicSubstringTest.java

Added test LongestPalindromicSubstringTest

test: `LongestPalindromicSubstring`

---

src/main/java/com/thealgorithms/stacks/NextGreaterElement.java
src/test/java/com/thealgorithms/stacks/NextGreaterElementTest.java

refactor: `NextGreaterElement`

---

src/main/java/com/thealgorithms/strings/StringCompression.java
src/test/java/com/thealgorithms/strings/StringCompressionTest.java

refactor: `StringCompression`

---

src/main/java/com/thealgorithms/datastructures/lists/CircleLinkedList.java
src/test/java/com/thealgorithms/datastructures/lists/CircleLinkedListTest.java

test: `CircleLinkedListTest`

---

src/main/java/com/thealgorithms/dynamicprogramming/LongestPalindromicSubstring.java
src/test/java/com/thealgorithms/dynamicprogramming/LongestPalindromicSubstringTest.java

Class cleanup.
Refactored javadocs.
Added tests.

refactor: `LongestPalindromicSubstring`

---

src/main/java/com/thealgorithms/others/CountChar.java
src/test/java/com/thealgorithms/others/CountCharTest.java

test: `CountCharTest`

---

src/main/java/com/thealgorithms/dynamicprogramming/PalindromicPartitioning.java
src/test/java/com/thealgorithms/dynamicprogramming/PalindromicPartitioningTest.java

Class cleanup.
Refactoring javadocs.
Adding tests.

refactor: `PalindromicPartitioning`

---

src/main/java/com/thealgorithms/others/QueueUsingTwoStacks.java
src/test/java/com/thealgorithms/others/QueueUsingTwoStacksTest.java

refactor: `QueueUsingTwoStacks`

---

src/test/java/com/thealgorithms/maths/FindKthNumberTest.java

In some cases, this code generates incorrect arrays, causing the test to not pass. 
The issue happens due to improper constraints on the generated arrays. This was identified in a few previous builds. 
This PR addresses the issue and has been thoroughly tested.

fix: `FindKthNumberTest`

---

src/main/java/com/thealgorithms/others/BFPRT.java
src/test/java/com/thealgorithms/others/BFPRTTest.java

refactor: `BFPRT`

---

src/main/java/com/thealgorithms/misc/InverseOfMatrix.java
src/test/java/com/thealgorithms/misc/InverseOfMatrixTest.java

refactor: `InverseOfMatrix`

---

src/main/java/com/thealgorithms/devutils/entities/ProcessDetails.java
src/main/java/com/thealgorithms/scheduling/PreemptivePriorityScheduling.java
src/test/java/com/thealgorithms/scheduling/PreemptivePrioritySchedulingTest.java

Removed internal Process class from PreemptivePriorityScheduling
Updated PreemptivePriorityScheduling to use ProcessDetails from com.thealgorithms.devutils.entities
Modified PreemptivePrioritySchedulingTest to work with ProcessDetails
Updated ProcessDetails to include a priority field and relevant constructor
This change brings PreemptivePriorityScheduling in line with other scheduling algorithms in the project (FCFSScheduling, RRScheduling, SJFScheduling, SRTFScheduling) which all use the common ProcessDetails class. This improves consistency across the codebase and makes it easier to maintain and extend the scheduling algorithms.
Implementation Details
The Process class previously defined within PreemptivePriorityScheduling has been removed.
PreemptivePriorityScheduling now uses …

Refactor ProcessDetails and PreemptivePriorityScheduling

---

src/main/java/com/thealgorithms/datastructures/hashmap/hashing/MajorityElement.java

This PR simplifies the logic inside the `majority` method.
The background story is that I was experimenting with [`infer`](https://github.com/facebook/infer) and it was reporting a _potential_ [Null dereference](https://fbinfer.com/docs/all-issue-types/#nullptr_dereference) (there are about 29 left). In this case it will not happen, but the code can be written _better_ (as in this PR). I am considering including infer into our CI. I will keep you updated.

style: use `getOrDefault` in `MajorityElement`

---

src/main/java/com/thealgorithms/misc/ColorContrastRatio.java
src/test/java/com/thealgorithms/misc/ColorContrastRatioTest.java

Formatted Javadocs.
Tests moved from class to standard test.

refactor: `ColorContrastRatio`

---

.github/workflows/run_infer.yml
.gitignore
.inferconfig

This PR configures [infer](https://github.com/facebook/infer). When looking on the current _ignore list_ in `.inferconfig`, I must stay that the majority of the warnings look reasonable and having this tool in our CI might _enforce_ better codding standards (cf. #5454). Please have a look below, for the _hidden text_ - it contians all of the warnings without ignoring any of the files.
~Currently marked as a draft, because the `Build infer` step takes too long~. I need to build it from the source, because the versions 1.2.0 and 1.1.0 do not work with this project. Infer build is cached. The key of the used to caching used the number of the week, so infer has to be rebuild every week (updates in the infer repository happen [quite often](https://github.com/facebook/infer/commits/main/)). I …

chore: add `run_infer.yml`

---

.github/workflows/infer.yml

Follows this suggestion: https://github.com/TheAlgorithms/Java/pull/5456#pullrequestreview-2319899388
@siriak please have a look.

style: use consistent workflow naming

---

.inferconfig
src/main/java/com/thealgorithms/conversions/UnitsConverter.java
src/test/java/com/thealgorithms/conversions/UnitsConverterTest.java

fix: handle Null Dereference in `UnitsConverter`

---

.inferconfig
src/main/java/com/thealgorithms/conversions/RomanToInteger.java
src/test/java/com/thealgorithms/conversions/RomanToIntegerTest.java

fix: handle Null Dereference in `RomanToInteger`

---

.inferconfig
src/main/java/com/thealgorithms/maths/NthUglyNumber.java

fix: handle Null Dereference in `NthUglyNumber`

---

src/main/java/com/thealgorithms/maths/Volume.java
src/test/java/com/thealgorithms/maths/VolumeTest.java

Hey I've implemented FrustumOfCone Algorithm in **src/main/java/com.thealgorithms/maths/Volume.java**
with the test class in the test package
for enhancement https://github.com/TheAlgorithms/Java/issues/5478
**Algorithm Overview:**
1. Input Parameters: The method accepts three parameters:
- r1: radius of the top circular base 
- r2: radius of the bottom circular base 
- height: height of the frustum
2. Volume Calculation: The method calculates the volume using the defined formula and returns the computed value as a double.
3. Unit Testing: Comprehensive unit tests have been implemented to validate the correctness of the calculation. The tests cover various scenarios to ensure that the function behaves as expected.
**Performance:**
- The time complexity of the volume calculation is O(1), …

Add Volume "Algorithm Frustum Of Cone" Then Test It.

---

pom.xml
src/main/java/com/thealgorithms/dynamicprogramming/ClimbingStairs.java

The comment improvements for the `ClimbingStairs` class enhance clarity and adherence to Java documentation standards. The initial comment succinctly explains the problem and provides a detailed example of climbing combinations for five steps. The method-level comment for `numberOfWays` clearly outlines its purpose, input parameters, and return values, including special cases for `n = 0` and `n = 1`. Inline comments within the method further clarify variable roles and loop logic, resulting in more readable and maintainable code.

Improve comments & readability in ClimbingStairs.java

---

src/main/java/com/thealgorithms/ciphers/HillCipher.java
src/test/java/com/thealgorithms/ciphers/HillCipherTest.java

- [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized it.
- [x ] All filenames are in PascalCase.
- [x ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`
Refactored HillCipher.java to remove Scanner dependency and make it testable

Add Tests for HillCipher.java

---

src/main/java/com/thealgorithms/ciphers/a5/CompositeLFSR.java

Strengthen class & function documentation in `CompositeLFSR.java`

---

src/main/java/com/thealgorithms/strings/ValidParentheses.java
src/test/java/com/thealgorithms/strings/ValidParenthesesTest.java

Added another method to check valid parentheses in ValidParentheses.java. Also added related testcases.

Added another method to check valid parentheses in ValidParentheses.java

---

DIRECTORY.md
src/main/java/com/thealgorithms/maths/QuadraticEquationSolver.java
src/test/java/com/thealgorithms/maths/QuadraticEquationSolverTest.java

feat: add QuadraticEquationSolver and test cases

---

src/main/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCount.java
src/test/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCountTest.java

feat : new dp algo added `UniqueSubsequenceCount.java`

---

src/main/java/com/thealgorithms/dynamicprogramming/BruteForceKnapsack.java
src/main/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCount.java
src/test/java/com/thealgorithms/dynamicprogramming/BruteForceKnapsackTest.java
src/test/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCountTest.java

Add tests, remove `main`, improve docs in `BruteForceKnapsack`

---

src/main/java/com/thealgorithms/dynamicprogramming/DiceThrow.java
src/main/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCount.java
src/test/java/com/thealgorithms/dynamicprogramming/DPTest.java
src/test/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCountTest.java

Add tests, remove `main` in `DiceThrow/DP.java`

---

src/main/java/com/thealgorithms/dynamicprogramming/Fibonacci.java
src/main/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCount.java
src/test/java/com/thealgorithms/dynamicprogramming/FibonacciTest.java
src/test/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCountTest.java

Add tests, remove `main`, add negativity test in `Fibonacci.java`

---

src/main/java/com/thealgorithms/dynamicprogramming/KadaneAlgorithm.java
src/main/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCount.java
src/test/java/com/thealgorithms/dynamicprogramming/KadaneAlgorithmTest.java
src/test/java/com/thealgorithms/dynamicprogramming/UniqueSubsequencesCountTest.java

Add tests, enhance docs in `KadaneAlgorithm.java`

---

src/main/java/com/thealgorithms/ciphers/ColumnarTranspositionCipher.java
src/test/java/com/thealgorithms/ciphers/ColumnarTranspositionCipherTest.java

fix columnarTranspositionCipher and typos in Test

---

src/main/java/com/thealgorithms/bitmanipulation/SwapAdjacentBits.java
src/test/java/com/thealgorithms/bitmanipulation/SwapAdjacentBitsTest.java

Adds algorithm support for aglorithm 2 at #5628

Add `SwapAdjacentBits.java` new algorithm

---

src/main/java/com/thealgorithms/searches/BM25InvertedIndex.java
src/test/java/com/thealgorithms/searches/BM25InvertedIndexTest.java

Add smoothing constant to IDF formula in BM25 to prevent negative scores

---

DIRECTORY.md
src/main/java/com/thealgorithms/searches/SearchInARowAndColWiseSortedMatrix.java
src/test/java/com/thealgorithms/searches/SearchInARowAndColWiseSortedMatrixTest.java

Add tests in `SearchInARowAndColWiseSortedMatrix`

---

DIRECTORY.md
src/main/java/com/thealgorithms/searches/UnionFind.java
src/test/java/com/thealgorithms/searches/UnionFindTest.java

Add tests, remove `main` in `UnionFind`

---

DIRECTORY.md
src/main/java/com/thealgorithms/bitmanipulation/BcdConversion.java
src/test/java/com/thealgorithms/bitmanipulation/BcdConversionTest.java

feat: Add BcdConversion algo with JUnit tests

---

DIRECTORY.md
src/main/java/com/thealgorithms/bitmanipulation/Xs3Conversion.java
src/test/java/com/thealgorithms/bitmanipulation/Xs3ConversionTest.java

feat: Add Xs3Conversion algo with JUnit tests

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/backtracking/CrosswordSolver.java
src/main/java/com/thealgorithms/datastructures/graphs/AStar.java
src/main/java/com/thealgorithms/datastructures/graphs/EdmondsBlossomAlgorithm.java
src/main/java/com/thealgorithms/datastructures/lists/MergeSortedArrayList.java
src/main/java/com/thealgorithms/geometry/ConvexHull.java
src/main/java/com/thealgorithms/maths/CircularConvolutionFFT.java
src/main/java/com/thealgorithms/maths/ConvolutionFFT.java
src/main/java/com/thealgorithms/maths/FFT.java
src/main/java/com/thealgorithms/maths/FFTBluestein.java
src/main/java/com/thealgorithms/maths/Gaussian.java
src/main/java/com/thealgorithms/maths/NthUglyNumber.java
src/main/java/com/thealgorithms/misc/MedianOfMatrix.java
src/main/java/com/thealgorithms/misc/PalindromeSinglyLinkedList.java
src/main/java/com/thealgorithms/others/KochSnowflake.java
src/main/java/com/thealgorithms/scheduling/PreemptivePriorityScheduling.java
src/main/java/com/thealgorithms/scheduling/SJFScheduling.java
src/main/java/com/thealgorithms/scheduling/diskscheduling/SSFScheduling.java
src/main/java/com/thealgorithms/sorts/BucketSort.java
src/main/java/com/thealgorithms/sorts/PatienceSort.java
src/main/java/com/thealgorithms/sorts/PigeonholeSort.java
src/main/java/com/thealgorithms/sorts/TreeSort.java
src/main/java/com/thealgorithms/strings/WordLadder.java
src/test/java/com/thealgorithms/datastructures/graphs/BoruvkaAlgorithmTest.java
src/test/java/com/thealgorithms/datastructures/graphs/EdmondsBlossomAlgorithmTest.java
src/test/java/com/thealgorithms/misc/WordBoggleTest.java
src/test/java/com/thealgorithms/scheduling/PreemptivePrioritySchedulingTest.java
src/test/java/com/thealgorithms/searches/QuickSelectTest.java

style: include `OCP_OVERLY_CONCRETE_PARAMETER`

---

src/main/java/com/thealgorithms/dynamicprogramming/RodCutting.java
src/test/java/com/thealgorithms/dynamicprogramming/RodCuttingTest.java

Add edge case to handle negative rod length in RodCutting algorithm

---

DIRECTORY.md
src/main/java/com/thealgorithms/maths/KrishnamurthyNumber.java
src/test/java/com/thealgorithms/maths/KrishnamurthyNumberTest.java

refactor: removed main function, improved docstring, written JUnit tests for `KrishnamurthyNumber`.

---

src/main/java/com/thealgorithms/conversions/UnitConversions.java
src/test/java/com/thealgorithms/conversions/UnitConversionsTest.java

refactor: Enhance docs in `UnitConversions`

---

src/main/java/com/thealgorithms/conversions/UnitsConverter.java
src/test/java/com/thealgorithms/conversions/UnitsConverterTest.java

refactor: Enhance docs, add more tests in `UnitsConverter`

---

src/main/java/com/thealgorithms/datastructures/bags/Bag.java
src/test/java/com/thealgorithms/datastructures/bag/BagTest.java

refactor: Enhance docs, add more tests in `Bag`

---

src/main/java/com/thealgorithms/datastructures/caches/MRUCache.java
src/test/java/com/thealgorithms/datastructures/caches/MRUCacheTest.java

refactor: Enhance docs, add more tests in `MRUCache`

---

src/main/java/com/thealgorithms/datastructures/dynamicarray/DynamicArray.java
src/test/java/com/thealgorithms/datastructures/dynamicarray/DynamicArrayTest.java

refactor: Enhance docs, add more tests in `DynamicArray`

---

src/main/java/com/thealgorithms/datastructures/graphs/FordFulkerson.java
src/test/java/com/thealgorithms/datastructures/graphs/FordFulkersonTest.java

refactor: Enhance docs, add more tests in `FordFulkerson`

---

src/main/java/com/thealgorithms/datastructures/caches/LRUCache.java
src/test/java/com/thealgorithms/datastructures/caches/LRUCacheTest.java

refactor: Enhance docs, add more tests in `LRUCache`

---

src/main/java/com/thealgorithms/datastructures/caches/LFUCache.java
src/test/java/com/thealgorithms/datastructures/caches/LFUCacheTest.java

refactor: Enhance docs, add more tests in `LFUCache`

---

src/main/java/com/thealgorithms/datastructures/graphs/JohnsonsAlgorithm.java
src/test/java/com/thealgorithms/datastructures/graphs/JohnsonsAlgorithmTest.java

refactor: Enhance docs, add more tests in `JohnsonsAlgorithm`

---

src/main/java/com/thealgorithms/datastructures/graphs/HamiltonianCycle.java
src/test/java/com/thealgorithms/datastructures/graphs/HamiltonianCycleTest.java

refactor: Enhance docs, add more tests in `HamiltonianCycle`

---

src/main/java/com/thealgorithms/datastructures/caches/LFUCache.java
src/main/java/com/thealgorithms/datastructures/graphs/KahnsAlgorithm.java
src/test/java/com/thealgorithms/datastructures/caches/LFUCacheTest.java
src/test/java/com/thealgorithms/datastructures/graphs/KahnsAlgorithmTest.java

refactor: Enhance docs, add tests in KahnsAlgorithm

---

src/main/java/com/thealgorithms/datastructures/caches/LFUCache.java
src/main/java/com/thealgorithms/datastructures/graphs/Kruskal.java
src/test/java/com/thealgorithms/datastructures/caches/LFUCacheTest.java
src/test/java/com/thealgorithms/datastructures/graphs/KruskalTest.java

refactor: Enhance docs, add tests in `Kruskal`

---

src/main/java/com/thealgorithms/datastructures/lists/QuickSortLinkedList.java
src/test/java/com/thealgorithms/datastructures/lists/QuickSortLinkedListTest.java

refactor: Enhance docs, add tests in `QuickSortLinkedList`

---

DIRECTORY.md
src/main/java/com/thealgorithms/datastructures/lists/MergeKSortedLinkedList.java
src/test/java/com/thealgorithms/datastructures/lists/MergeKSortedLinkedListTest.java

refactor: Enhance docs, add tests in MergeKSortedLinkedList

---

src/main/java/com/thealgorithms/conversions/IntegerToRoman.java
src/main/java/com/thealgorithms/datastructures/lists/CursorLinkedList.java
src/test/java/com/thealgorithms/conversions/IntegerToRomanTest.java
src/test/java/com/thealgorithms/datastructures/lists/CursorLinkedListTest.java

refactor: Enhance docs, add tests in `CursorLinkedList`

---

src/main/java/com/thealgorithms/datastructures/lists/CircleLinkedList.java
src/test/java/com/thealgorithms/datastructures/lists/CircleLinkedListTest.java

refactor: Enhance docs, add tests in `CircleLinkedList`

---

src/main/java/com/thealgorithms/audiofilters/EMAFilter.java
src/test/java/com/thealgorithms/audiofilters/EMAFilterTest.java

Added Exponential Moving Average Filter for audio signals , EMAFilter.java & EMAFilterTest.java

---

src/main/java/com/thealgorithms/ciphers/AES.java
src/main/java/com/thealgorithms/ciphers/AffineCipher.java
src/main/java/com/thealgorithms/ciphers/Blowfish.java
src/main/java/com/thealgorithms/conversions/AnyBaseToAnyBase.java
src/main/java/com/thealgorithms/conversions/HexaDecimalToBinary.java
src/main/java/com/thealgorithms/datastructures/graphs/FloydWarshall.java
src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java
src/main/java/com/thealgorithms/datastructures/trees/GenericTree.java
src/main/java/com/thealgorithms/graph/StronglyConnectedComponentOptimized.java
src/main/java/com/thealgorithms/maths/NthUglyNumber.java
src/main/java/com/thealgorithms/maths/VampireNumber.java
src/main/java/com/thealgorithms/scheduling/NonPreemptivePriorityScheduling.java
src/test/java/com/thealgorithms/backtracking/NQueensTest.java
src/test/java/com/thealgorithms/bitmanipulation/GenerateSubsetsTest.java
src/test/java/com/thealgorithms/datastructures/graphs/AStarTest.java
src/test/java/com/thealgorithms/dynamicprogramming/AllConstructTest.java
src/test/java/com/thealgorithms/dynamicprogramming/AssignmentUsingBitmaskTest.java
src/test/java/com/thealgorithms/graph/StronglyConnectedComponentOptimizedTest.java
src/test/java/com/thealgorithms/greedyalgorithms/ActivitySelectionTest.java
src/test/java/com/thealgorithms/greedyalgorithms/CoinChangeTest.java
src/test/java/com/thealgorithms/maths/ChineseRemainderTheoremTest.java
src/test/java/com/thealgorithms/maths/MeansTest.java
src/test/java/com/thealgorithms/misc/MedianOfMatrixTest.java
src/test/java/com/thealgorithms/others/FloydTriangleTest.java
src/test/java/com/thealgorithms/scheduling/diskscheduling/CircularLookSchedulingTest.java
src/test/java/com/thealgorithms/scheduling/diskscheduling/CircularScanSchedulingTest.java
src/test/java/com/thealgorithms/scheduling/diskscheduling/LookSchedulingTest.java
src/test/java/com/thealgorithms/scheduling/diskscheduling/ScanSchedulingTest.java
src/test/java/com/thealgorithms/strings/WordLadderTest.java

1- Replaced single element lists with java's singletonList to conserve memory. 
2- Replaced empty lists with java's emptyList() to conserve memory. 
3- Removed commented code.
4- Fixed classes without set package.
5- Replaced string concatenations with StringBuilders'. 
6- Other minor improvements.

General performance improvement:

---

src/main/java/com/thealgorithms/Recursion/FibonacciSeries.java
src/test/java/com/thealgorithms/Recursion/FibonacciSeriesTest.java

adding the fibonacci series to the Recursion package

---

src/main/java/com/thealgorithms/datastructures/graphs/DijkstraOptimizedAlgorithm.java
src/test/java/com/thealgorithms/datastructures/graphs/DijkstraOptimizedAlgorithmTest.java

Speed up Dijkstra Algorithm by using another Dijkstra variant that is generally faster.

Add optimized version of DijkstraAlgorithm

---

src/main/java/com/thealgorithms/maths/VampireNumber.java
src/test/java/com/thealgorithms/maths/VampireNumberTest.java

Several improvements to maths/VampireNumber code:
1. Fixes a bug in same length of fangs detection for pseudo vampire numbers. Now it is done in the most straight-forward way.
2. Adds tests for the VampireNumber class.
3. Fixed several typos in code and comments.
4. Generally simplifies code and improves readability.

Improvements to Vampire Number

---

src/main/java/com/thealgorithms/strings/zigZagPattern/ZigZagPattern.java
src/test/java/com/thealgorithms/strings/zigZagPattern/ZigZagPatternTest.java

- Simplified the logic by using row-by-row traversal with direct index calculations for efficiency
- Added Javadoc documentation for clarity.

improve zig-zag-pattern

---

src/main/java/com/thealgorithms/sorts/DarkSort.java
src/test/java/com/thealgorithms/sorts/DarkSortTest.java

This pull request adds the DarkSort algorithm, a randomized sorting algorithm based on the quicksort strategy. The algorithm divides the array around a pivot element, recursively sorts the partitions, and leverages randomization for efficiency. It offers an average-case time complexity of O(n log n) and is useful in scenarios requiring fast sorting with large data sets.

Adding DarkSort Algorithm

---

src/main/java/com/thealgorithms/maths/AbsoluteMax.java
src/test/java/com/thealgorithms/maths/AbsoluteMaxTest.java

The AbsoluteMax class contains a bug in the getMaxValue method. When two numbers have the same absolute value (e.g., 5 and -5), the method returns the number that appears later in the array. This behavior is inconsistent and may lead to unexpected results.
Explanation with Example.
Before Fix
5, -5 returns -5 
-5, 5 returns  5
After Fix
5, -5 returns  5 
-5, 5 returns  5
Thanks

Fix absolute max bug

---

src/main/java/com/thealgorithms/backtracking/ArrayCombination.java

Fix: Replaced removeLast() with remove(current.size() - 1) for compatibility with Array List

Fix: Replaced removeLast() with remove(current.size() - 1) 

---

pom.xml

This should fix the failing CI in #6174 and #6177.
Use BOM to align the version of `junit-jupiter` and `junit-jupiter-api`.

chore: use BOM to manage junit dependencies

---

pom.xml

There is not need to have an explicit dependency to `junit-jupiter-api`, becasue `junit-jupiter` aggregates all Jupiter modules. Should be done in #6178.

chore: remove explicit dependency to `junit-jupiter-api`

---

src/main/java/com/thealgorithms/matrix/SolveSystem.java
src/test/java/com/thealgorithms/matrix/SolveSystemTest.java

Added a linear system solver

---

DIRECTORY.md
src/main/java/com/thealgorithms/conversions/WordsToNumber.java
src/test/java/com/thealgorithms/conversions/WordsToNumberTest.java

- **Accurate Word-to-Number Conversion:** Converts English word representations of numbers into their numeric form, supporting values from small fractions to trillions.
- **Handles Decimals and Negatives:** Properly interprets decimal numbers (e.g., "three point one four" → 3.14) and negative values.
- **Robust Input Validation:** Detects invalid phrases, incorrect formatting, and duplicate words (e.g., "one hundred hundred" → Invalid).
- **BigDecimal Support:** Provides a method to directly convert word-based numbers into BigDecimal, ensuring precision for financial and scientific calculations.
- **Optimized for Readability:** Modular design ensures clean, maintainable, and extensible code.
Here’s how you can use the WordsToNumber class in your Java application:
```java
import …
```

Add feature to convert numeric words to their number representation

---

src/main/java/com/thealgorithms/datastructures/lists/CountSinglyLinkedListRecursion.java
src/main/java/com/thealgorithms/datastructures/lists/MergeSortedSinglyLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/QuickSortLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/ReverseKGroup.java
src/main/java/com/thealgorithms/datastructures/lists/RotateSinglyLinkedLists.java
src/main/java/com/thealgorithms/datastructures/lists/SearchSinglyLinkedListRecursion.java
src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedListNode.java
src/test/java/com/thealgorithms/datastructures/lists/ReverseKGroupTest.java
src/test/java/com/thealgorithms/datastructures/lists/RotateSinglyLinkedListsTest.java
src/test/java/com/thealgorithms/datastructures/lists/SinglyLinkedListTest.java

This is a step towards not suppressing `auxiliaryclass`:
https://github.com/TheAlgorithms/Java/blob/22098c7d1ef06df65ccfcd33bd17d8ad9783dafc/pom.xml#L78
This PR moves the `Node` class outside `SinglyLinkedList.java`.
The name `SinglyLinkedListNode` has the advantage that it is unique. I am open for suggestions here.

refactor: introduce `SinglyLinkedListNode`

---

src/main/java/com/thealgorithms/randomized/RandomizedQuickSort.java
src/test/java/com/thealgorithms/randomized/RandomizedQuickSortTest.java

Randomize Quick Sort Addition

---

.github/workflows/infer.yml

The current build of facebook/infer is failing ([see](https://github.com/facebook/infer/commit/dc195a4eae2859d6367bb4afd1495ce1cdadd07e)) , which causes our GitHub Actions workflow to fail as well. To temporarily stabilize our CI pipeline, this PR pins facebook/infer to the last known working commit.
Once the upstream issue is resolved and the build is stable again, I will update our workflow to use the latest version and open a new Pull Request accordingly.

fix: use last known working commit for infer to avoid build failure

---

pom.xml
src/main/java/com/thealgorithms/backtracking/AllPathsFromSourceToTarget.java
src/main/java/com/thealgorithms/datastructures/bloomfilter/BloomFilter.java
src/main/java/com/thealgorithms/datastructures/graphs/Kruskal.java
src/main/java/com/thealgorithms/datastructures/graphs/WelshPowell.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArray.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMap.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/LinearProbingHashMap.java
src/main/java/com/thealgorithms/datastructures/lists/CircleLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/CursorLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/SkipList.java
src/main/java/com/thealgorithms/dynamicprogramming/LongestArithmeticSubsequence.java
src/main/java/com/thealgorithms/misc/PalindromeSinglyLinkedList.java
src/main/java/com/thealgorithms/searches/FibonacciSearch.java
src/main/java/com/thealgorithms/sorts/MergeSort.java
src/main/java/com/thealgorithms/sorts/SortAlgorithm.java
src/main/java/com/thealgorithms/sorts/SpreadSort.java
src/main/java/com/thealgorithms/sorts/TimSort.java
src/test/java/com/thealgorithms/datastructures/graphs/KruskalTest.java
src/test/java/com/thealgorithms/maths/NumberOfDigitsTest.java

This PR includes `rawtypes` into the active compiler warnings and suppresses it for the classes causing problems.
I see the following advantages:
- all remaining code (including potential new code) will be compiled with this warning enabled,
- it allows to split the task of resolving all of these warnings into reasonable chunks.
If this will be merged, I will create similar pull requests for the remaining warnings, i.e. `auxiliaryclass` and `unchecked`.
Continuation of #5165.

chore: suppress `rawtypes` in selected classes

---

.github/workflows/codeql.yml

This PR configures the CodeQL scan to take care of the potential vulnerabilities in the github actions. When this will be merged, 5 _security alerts_ will be created in [`security/code-scanning`](https://github.com/TheAlgorithms/Java/security/code-scanning). I will take cake of them (they are all related to setting permissions, the fix is similar to vil02/adv_2024#184).
Continuation of #4966.

chore: perform CodeQL scan on actions

---

src/main/java/com/thealgorithms/randomized/RandomizedMatrixMultiplicationVerification.java
src/test/java/com/thealgorithms/randomized/RandomizedMatrixMultiplicationVerificationTest.java

Added **Freivalds' Algorithm** under the `randomized` category as part of issue [#6219]
This algorithm offers a fast, probabilistic method to verify whether matrix multiplication `A × B = C` holds true, avoiding full recomputation of the product.
---
- Generate a random binary vector `r`
- Perform matrix-vector multiplications and check if:  
`A × (B × r) ≟ C × r`
- Repeat this process `k` times to reduce the probability of error
- Probability of false positives becomes **≤ 1/2^k**
---
- **Per iteration:** O(n²)
- **Total expected time:** O(k × n²)  
(significantly faster than recomputing A × B, which is O(n³))
---
- Verifying matrix multiplication in:
- Scientific computing workflows
- Distributed computing systems
- Cloud infrastructure and audit pipelines
- Faster correctness checks …

Added Freivalds' Algorithm for randomized matrix multiplication verification

---

.github/workflows/update-directorymd.yml
src/main/java/com/thealgorithms/datastructures/caches/FIFOCache.java
src/test/java/com/thealgorithms/datastructures/caches/FIFOCacheTest.java

This PR adds a reusable FIFOCache implementation with the following features:
- Fixed size FIFO eviction policy using `LinkedHashMap`
- Time to live (TTL)
- Thread-safe operations using ReentrantLock
- Pluggable EvictionStrategy to control expired entry cleanup
- Eviction listener callback support for observing removals
- Hit and miss statistics tracking
-  Builder for flexible configuration

Add cache with FIFO replacement policy

---

src/main/java/com/thealgorithms/bitmanipulation/BitSwap.java
src/test/java/com/thealgorithms/bitmanipulation/BitSwapTest.java

Added parameterized tests covering:
- Different bit cases
- Same bit cases
- Edge positions
- Invalid positions
- Original test cases

refactor: add parameterized tests for BitSwap

---

src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java
src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java

Refactored the abstract class `MedianOfRunningArray` to improve clarity, extensibility, and maintainability.
Changes made:
- Renamed `median()` → `getMedian()` for clearer naming convention.
- Improved JavaDoc comments for class and methods to enhance code documentation and readability.
- Extracted heap balancing logic into a dedicated private method `balanceHeapsIfNeeded()` to reduce code duplication.
- Changed method access modifiers:
- Made `insert()` and `getMedian()` final to prevent override and preserve consistency.
- Changed heap fields to `final`.
- Added detailed exception message and `@throws` tag when median is requested on an empty data set.
- General formatting and naming improvements for consistency and readability.

refactor: improve median calculator class design and readability

---

src/main/java/com/thealgorithms/strings/ValidParentheses.java
src/test/java/com/thealgorithms/strings/ValidParenthesesTest.java

- Simplified stack-based logic for better readability and efficiency
- Combined similar validation approaches into clearer methods
- Added parameterized tests covering diverse valid and invalid cases
- Improved error handling for unexpected characters with informative exceptions

refactor: optimize ValidParentheses methods and add parameterized tests

---

src/main/java/com/thealgorithms/bitmanipulation/BitwiseGCD.java
src/test/java/com/thealgorithms/bitmanipulation/BitwiseGCDTest.java

I created a new branch and have added the BitwiseGCD algorithm or Stein's Algorithm in the Bit manipulation folder also I have added the Test cases of the same in the file named BItwiseGCDTest.java. These test cases contain all the types of test cases from normal testcases of the range 1 - 1000 and also all the edge cases containing Long.min and Long.max thus all the testcases are covered closing #6542

Added BitwiseGCD.java and BitwiseGCDTest.java

---

src/main/java/com/thealgorithms/strings/AlternativeStringArrange.java
src/test/java/com/thealgorithms/strings/AlternativeStringArrangeTest.java

DEV: Implementing Alternative String Arrange

---

src/main/java/com/thealgorithms/others/MiniMaxAlgorithm.java
src/test/java/com/thealgorithms/others/MiniMaxAlgorithmTest.java

- Fix bug in setScores method where scores.length % 1 == 0 always returned true
- Add isPowerOfTwo helper method to properly validate array length
- Add comprehensive unit tests covering edge cases and algorithm correctness
- Tests include validation for power of 2 check, minimax logic, and error handling
Fixes #6563
Fixes issue with incorrect validation logic in MiniMaxAlgorithm.setScores()

Fix MiniMaxAlgorithm setScores bug and add comprehensive tests

---

src/main/java/com/thealgorithms/conversions/CoordinateConverter.java
src/test/java/com/thealgorithms/conversions/CoordinateConverterTest.java

Dev: Added CoordinateConverter for Cartesian and Polar coordinate conversions

---

pom.xml
src/main/java/com/thealgorithms/dynamicprogramming/PartitionProblem.java
src/main/java/com/thealgorithms/geometry/Haversine.java
src/test/java/com/thealgorithms/geometry/HaversineTest.java

Hello! This PR adds the Haversine formula algorithm and also includes two small fixes for issues I found while setting up the development environment.
This implementation is of the `Haversine` formula to calculate the distance between two points on a sphere
---
* Added the **Haversine formula** implementation (`Haversine.java`) to the `geometry` package. This algorithm calculates the great-circle distance between two points on a sphere using their latitude and longitude.
* Included a corresponding unit test file (`HaversineTest.java`) with multiple test cases to ensure correctness.
To get the project to build and run tests successfully, I also made the following corrections:
1.  **`pom.xml`:** Updated the Maven compiler plugin configuration from `<source>`/`<target>` to the modern …

FEAT(geometry): Add Haversine formula and fix build issues

---

src/main/java/com/thealgorithms/dynamicprogramming/DamerauLevenshteinDistance.java
src/test/java/com/thealgorithms/dynamicprogramming/DamerauLevenshteinDistanceTest.java

feat: add damerau-levenshtein distance algorithm
