Bubble Sort.java

This would decrease the number of comparisons in the loop used for sorting.

Changes in for loop for sorting

---

Binary Search.java

I wanted to see if you would like me to add to your repository with Javadoc.

Added JavaDoc to BinarySearch.java

---

data_structures/CircleLinkedList.java

Uses a dummy node and generics…. this implementation of a singly linked
list eliminates need to use tail reference

CircleLinkedList

---

Sorts/BubbleSort.java

Updated to a more efficient version of bubble sort by adding decrements after loop and changing loop type.

Bubble sort updated to efficient version

---

Misc/Palindrome.java
data_structures/Lists/SinglyLinkedList.java

- added Palindrome class
- changed LinkforLinkedList class name to Node, for understandability
- replaced displayLink method with getValue instead, more usable in other applications

added class for Palindrome and re-edited SinglyLinkedList

---

Misc/CountChar.java

Tried to generally clean up code

Updated syntax / whitespace

---

insert_delete_in_array.java

Insertion and deleting of an element into a java array. Please review and check it out.

Inserting and deleting an element in java array

---

data_structures/Trees/TreeTraversal.java

A program which describes all the three tree traversals (InOrder, PreOrder & PostOrder)

Created TreeTraversal.java

---

Conversions/HexaDecimalToBinary.java

contribution HexaDecimal To Binary conversion created.

HexaDecimal To Binary conversion created

---

Conversions/DecimalToAnyBase.java
Searches/LinearSearch.java

Converted integer linear search to a generic linear search and added faster input method

Updated LinearSearch.java

---

Sorts/BubbleSort.java

Updated BubbleSort.java to its generic version

Updated BubbleSort.java

---

Sorts/BubbleSort.java
Sorts/InsertionSort.java

Updated Insertion Sort to its Generic version
Related to #65

Updated Insertion Sort

---

data_structures/Lists/SinglyLinkedList.java

Added a function to insert a node at a specified position in linked list. This is my first pull request, will continue to contribute more to this repository. There's a mistake in the function the field would be 'value' ,not 'data'. I will surely correct it in my next commit.

Added function to insert a node at specified position in linked list

---

Sorts/ShellSort.java

Added Shell Sort

---

Dynamic Programming/Levenshtein_distance.java

added levenshtein distance dp implementation

---

Misc/ReverseStackUsingRecursion.java

Added algorithm to reverse a stack

---

Misc/TowerOfHanoiUsingRecursion

Tower of Hanoi using Recursion

---

data_structures/Trees/BinaryTree.java

#104 
Note: The amount of lines changed is because of indentation (auto-formatting) fixes, not actual code changes.

BinaryTree find(int key) fix

---

Dynamic Programming/Knapsack.java

Very frequently asked DP problem in interviews.

add 0-1 knapsack

---

Misc/crc32.java

calculate crc32 checksum for string or byte array

Added crc32 implementation

---

Dynamic Programming/Fibonacci.java

There is a compiler error. So, corrected method call.

Corrected method call

---

Misc/ReturnSubsequence.java

Algorithm to Return Subsequences

---

Dynamic Programming/rod_cutting.java

A Dynamic Programming solution for Rod cutting problem

Rodcuting dp approach in java

---

data_structures/Trees/TreeTraversal.java

Prints each level of the bst.
I.e., Root -> its children -> its children's children -> and so on...

Add: level order traversal.

---

Conversions/AnyBaseToAnyBase.java

validForBase() ensures that the entered number is valid for the beginning base. Additionally, constant fields for the minimum/maximum bases you want to accept from the user were added; however, max base should not exceed 36 (after which its unclear how to represent digits >36)

Add validForBase() and min/max base constants

---

Dynamic Programming/LongestCommonSubsequence.java

Added Longest Common Subsequence (LCS) algorithm under Dynamic Programming in Java

Add Longest Common Subsequence algorithm (DP)

---

Sorts/CountingSort.java
Sorts/CountingSortIntegers.java

Implemented the Counting Sort Algorithm for sorting integers that are within the range [0:10^8].
It sorts only integer arrays especially positive integers since it uses array elements as indexes in the frequency array.

Created new file in Sorts directory, CountingSortIntegers.java

---

data_structures/Graphs/Kruskal's Algorithm.java
data_structures/Graphs/prim.java

Added prim's and kruskal's Algorithms

Prim's And kruskal's Algorithms

---

Others/QueueUsingTwoStacks.java

QueueUsingTwoStacks.java implements the Queue data structure using two Stacks. Implementation and runtime explained in the comments.

Added QueueUsingTwoStacks.java class in Other folder

---

Sorts/CocktailShakerSort.java

I will start contributing to this repository with my version of cocktail shaker sort...

Adding cocktail shaker sort

---

ciphers/RSA.java

RSA encryption

---

Searches/TernarySearch.java

Added Ternary Search.

---

data_structures/Trees/TrieImp.java

Trie Data structure implementation without any libraries

Trie Data structure

---

data_structures/Bags/Bag.java

Added a sample implementation of a Bag-Datastructure for Hacktoberfest

added Bag-datastructure

---

data_structures/Buffers/CircularBuffer.java

data structure used for producer consumer situations. Allows reading and
writing so long as there is data and the buffer is not full,
respectively.

Add: circular buffer implementation.

---

data_structures/Queues/GenericArrayListQueue.java

Uses an arraylist its underlying datastructure.

Add: generic queue implementation.

---

Dynamic Programming/EggDropping.java

Dynamic Programming solution for the popular Egg Dropping Puzzle

Add Eggdroping puzzle

---

data_structures/Lists/CircleLinkedList.java

To comply with international standards.
https://www.hongkiat.com/blog/source-code-comment-styling-tips/

Coding standards

---

Data Structures/Graphs/MatrixGraphs.java

I create Adjacency Matrix Graph using Integer Array.

Add MatrixGraphs

---

Data Structures/Graphs/MatrixGraphs.java

Hi,
minor change - merge if you like or close it.

changed t to T

---

Searches/SaddlebackSearch.java

#96 efficient algorithm to perform search in a sorted 2D array

Added SaddlebackSearch

---

Conversions/DecimalToHexaDecimal.java

Updated DecimalToHexaDecimal.java

---

Conversions/HexToOct.java

Program that converts Hexadecimal numbers to Octal.

Add Hexadecimal to Octal

---

Data Structures/Graphs/MatrixGraphs.java

While checking the graph, I found a typo and corrected it.

verticies to vertices

---

Conversions/HexaDecimalToBinary.java

Modifying HexaDecimalToBinary.java

---

Conversions/OctalToDecimal.java

Updated OctalToDecimal.java

---

Data Structures/Graphs/MatrixGraphs.java

change the comment spelling
verticies ->vertices

modify comment verticies to vertices

---

Others/krishnamurthy.java

Modified errors in the code.
Because the fact method is not static, it generates a error when used in main.

Updated krishnamurthy.java

---

Others/Dijkshtra.java
Others/InsertDeleteInArray.java
Others/RootPrecision.java
Others/StackPostfixNotation.java

Matched the .java file in the Others folder with the class name.
I will update other folders soon.

Modified Others folder .java file name and class name

---

Data Structures/Graphs/BFS.java
Data Structures/Graphs/DFS.java
Data Structures/Graphs/PrimMST.java

Matched the .java file in the Data Structures/Graphs folder with the class name.
Modified error in PrimMST.
1.  Constructor error.

Modified Data Structures/Graphs folder .java file name and class name

---

Data Structures/Trees/AVLTree.java
Data Structures/Trees/LevelOrderTraversal.java
Data Structures/Trees/LevelOrderTraversalQueue.java
Data Structures/Trees/PrintTopViewofTree.java
Data Structures/Trees/ValidBSTOrNot.java

Matched the .java file in the Data Structures/Graphs folder with the class name.

Modified Data Structures/Trees folder .java file name and class name

---

Dynamic Programming/LevenshteinDistance.java

Matched the .java file in the Dynamic Programming folder with the class name.

Modified Data Dynamic Programming folder .java file name and class name

---

Dynamic Programming/LevenshteinDistance.java
Misc/heap_sort.java

Matched the .java file in the Misc folder with the class name.

Modified Data Misc folder .java file name and class name

---

Others/countwords.java

The file's name is counterwords, but class name is CounterWords.
And not public.

add public and change class_name

---

Others/countwords.java

In the code of Others/countwords.java, if the user enter no sentence as input then the code was the giving the number of words to be -1 and also the method used for it was public.
So, I thought to correct it.
Thanks for you time 👍

Fix a logical error and set a method to private

---

README.md

Solves issue #304

---

Others/Palindrome.java

There was original Palindrome.java then somebody wanted to improve its algo but their PR resulted in a conflict. PR was #146 .
So, I let the original code there with a changed method name (now, "FirstWay") and added the method of the PR with that conflict with the name "SecondWay".
PS. I had been updating my local master with the TheAlgorithms/Java master and now, when I have made a new branch "palindrome" for the PR, it includes all the merges of TheAlgorithms/Java master. I hope it doesn't cause any problem.
I am open for any suggestion.
Thanks for your time.

Resolve the conflict of closed PR #146

---

Sorts/QuickSort.java

Change to List<E> for any type of array.
Change value of pivot to value of middle index of unsorted array.

QuickSortAlgo.java

---

Data Structures/Graphs/ConnectedComponent.java

Program that counts the number of different connected components in a graph.

Add connected components algorithm

---

Data Structures/CSVFile/src/CSVFile.java

Remove code redundancy.
Use try with resource.

Updates in CSVFile.java

---

Sorts/CombSort.java

Comb Sort is mainly an improvement over Bubble Sort. Bubble sort always compares adjacent values. So all inversions are removed one by one. Comb Sort improves on Bubble Sort by using gap of size more than 1. The gap starts with a large value and shrinks by a factor of 1.3 in every iteration until it reaches the value 1. Thus Comb Sort removes more than one inversion counts with one swap and performs better than Bubble Sort.
The shrink factor has been empirically found to be 1.3 (by testing CombSort on over 200,000 random lists) [Source: Wiki]
Although, it works better than Bubble Sort on average, worst case remains O(n2).

CombSort.java

---

Sorts/src/sort/MergeSort.java

This is my first time to create pull request, if I did something wrong, I'll apologize.
The next is why a create pull request.
If "i" reaches "mid" , but "j" doesn't reach "right", the left of "j" should also be add to arr. 
Thanks.

 the second array may have residual elements.

---

DataStructures/Lists/CircleLinkedList.java

Regarding #436 
I have fixed the issue and also fixed remove method which doesn't work properly in decreasing list size after deletion. Please kindly review and let me know your feedback :)

Fix #436 - CircleLinkedList malfunction

---

README.md

- elaborated on the insert sorting figure.
fixes #459

update insertion sorting part

---

Data Structures/Stacks/StackOfLinkedList.java

just a basic change, i'm starting with open source contributions

added peek() method and stack is now printed vertically

---

Dynamic Programming/CoinChange.java

@varunu28 can you please review this?
Thanks in advance.

Add method for minimum number of coins required for given amount

---

src/main/com/java/conversions/AnyBaseToDecimal.java
src/test/com/java/conversions/AnyBaseToDecimalTest.java

Add test just like this? If it is, I'll continue to do some of the rest and would commit a PR with not only one Java file.

add a Test about AnyBaseToDecimal.java

---

src/main/com/java/sorts/BubbleSort.java
src/main/com/java/sorts/HeapSort.java
src/main/com/java/sorts/QuickSort.java
src/main/com/java/sorts/SelectionSort.java
src/main/com/java/sorts/ShellSort.java
src/main/com/java/sorts/SortUtils.java
src/test/com/java/sorts/BubbleSortTest.java
src/test/com/java/sorts/HeapSortTest.java
src/test/com/java/sorts/QuickSortTest.java
src/test/com/java/sorts/SelectionSortTest.java
src/test/com/java/sorts/ShellSortTest.java

Add some tests for Sort, and then modify some functions in these class.

add some tests for Sort

---

DataStructures/Trees/GenericTree.Java

Bring fileName into correspondence with className which is marked as public

className is error

---

Others/Dijkshtra.java

Tested and should be working the same way although a lot easier to read

Improved readability

---

Others/FibToN.java

Now the user can quickly understand what the algorithm is about.

Updated comments for the Fibonacci sequence

---

Others/Huffman.java
Others/KMP.java

- Fixed several compiler warnings.
- "Scanner in" was never closed. Now it is closed properly.
- Fixed a few typos such as "frequncy" --> "frequency"

Fixed Compiler warnings, closed the scanner and fixed some typos

---

Searches/src/search/BinarySearch.java

Cleans the implementation of the binary search to be more consistent with styles and to avoid unnecessary boxing of int types

Clean BinarySearch

---

src/main/java/com/sorts/StoogeSort.java
src/test/java/com/sorts/StoogeSortTest.java

I have added the StoogeSort algorithm and JUnit Test, and removed the other files has stated.

Added StoogeSort algorithm and JUnit Test

---

DataStructures/Trees/BinaryTree.java

Sorry for opening a new pull request because I'm not skilled enough in squash the commits.
#644

fix BinaryTree.java put method

---

src/main/java/com/search/InterpolationSearch.java
src/test/java/com/search/InterpolationSearchTest.java

Due to git issues, had to make new pull request.

Added Interpolation Search and JUnit test.

---

src/main/java/com/search/BinarySearch.java
src/main/java/com/search/LinearSearch.java
src/test/java/com/search/BinarySearchTest.java
src/test/java/com/search/LinearSearchTest.java

-Linear Search was added.
-Made Both searches final and static ( There is no reason to have to instantiate them). Also Changed the tests to include the new static methods.
-Added a new test, searching an empty array.

Added Linear Search, changed Binary search

---

Dynamic Programming/Ford_Fulkerson.java
Others/Armstrong.java

I actually opened one PR but closed due to one additional file. please check and merge

one new Dynamic Programming Algorithm and a modification adding recommanding input method

---

src/main/java/src/main/java/com/sorts/CountingSort.java
src/main/java/src/main/java/com/sorts/CycleSort.java
src/test/java/src/test/java/com/sorts/CountingSortTest.java
src/test/java/src/test/java/com/sorts/CycleSortTest.java

1. Added algorithm class CountingSort and its corresponding test class CountingSortTest
2. Added algorithm class CycleSort and its corresponding test class CycleSortTest

Added Counting Sort and Cycle Sort

---

src/main/java/com/crypto/hash/Sha2.java
src/test/java/com/crypto/hash/Sha2Test.java

Implementation of the specification RFC 6234 (SHA-2) for educational purposes.

Secure Hash Algorithm 2 (SHA-224, SHA-256, SHA-384, SHA-512)

---

DataStructures/Trees/AVLTree.java

For more than one command, must have curly brackets.

Correction of a RuntimeException Uncompilable source code

---

src/main/java/com/matchings/stableMatching/GaleShapley.java
src/test/java/com/matchings/stableMatching/GaleShapleyTest.java

Let me know if there's anything I can do to ease the reviewing process!
The definition of a stable matching and the Gale Shapley algorithm are described here: [Stable marriage problem (Wikipedia)](https://en.wikipedia.org/wiki/Stable_marriage_problem).

add the Gale Shapley algorithm and its test

---

src/main/java/com/conversions/BinaryToHexadecimal.java
src/test/java/com/conversions/BinaryToHexadecimalTest.java

conversion binary to hexadecimal

conversion binary to hexadecimal

---

DataStructures/Lists/CursorLinkedList.java

added CursorLinkedList basic implementation

CursorLinkedList

---

src/main/java/com/conversions/DecimalToHexadecimal.java
src/test/java/com/conversions/DecimalToHexadecimalTest.java

convert decimal number to hexadecimal

Conversion

---

Dynamic Programming/Fibonacci.java

o fixed function "fibMemo" according to acceptance criteria in #708
o fixed function "fibBotUp" according to acceptance criteria in #708

#708 (bugfix for fibonacci sequence function)

---

DataStructures/Stacks/StackOfLinkedList.java

I made the code shorter and less prone to mistakes by removing the "size" variable altogether from the LinkedList class. I found that after each push/pop operation, changing the value of size did make the code more efficient, but made it more prone to mistakes. So, for empty stack, a simple "head == null" was enough, which has been incorporated.

Updated StackOfLinkedList.java

---

src/main/java/com/dataStructures/GeneralQueue.java
src/main/java/com/types/DataStructure.java
src/main/java/com/types/Queue.java
src/test/java/com/dataStructures/GeneralQueueTest.java

Adding Linked List based General queue implementation
This could further be used to create more queue implementations

Adding Linked List based General queue implementation

---

DataStructures/Lists/SinglyLinkedList.java

- The **count** variable made the code more prone to errors, so I removed and replaced it with another **getSize()** function. 
- The value of **next** was initialized to null.
- Major improvements of code were given to **insertNth()** and **deleteHead()** functions for efficiency.
- A new function **deleteNth()** was defined, increasing the usefulness of the program.

Major Updates in SinglyLinkedList.java

---

src/main/java/com/dataStructures/DisjointSet.java
src/test/java/com/dataStructures/DisjointSetTest.java

Disjoint-set operations:
1. quickly unites two sets into a new set, requiring O(1) time.
2. quickly query two elements whether contained in the same set, requiring about O(1) time.

I added an implementation of disjoint-set

---

Conversions/RomanToInteger.java

Add new program  which converts  Roman number int Integer

Add Roman To Integer conversion

---

DataStructures/Matrix/Matrix.java

Made Matrix equality comparison deep.

---

DataStructures/Lists/DoublyLinkedList.java

Changes made in Insert and Delete functions.

Updated DoublyLinkedList.java

---

README.md

Fixed current link that lead to _400 Bad Request_

fix: fix link in README

---

src/main/java/com/dataStructures/BinaryTree.java
src/test/java/com/dataStructures/BinaryTreeTest.java

Binary tree implemented for general type of comparable data

Add binary tree implementation with test

---

src/main/java/com/search/ExponentialSearch.java
src/test/java/com/search/ExponentialSearchTest.java

Exponential search (also called doubling search or galloping search or Struzik search) is an algorithm which finds the position of a target value within an array. It works by determining a range that the search key resides in and performing a binary search within that range.

Added the algorithm and test cases for Exponential Search

---

src/main/java/com/conversions/BinaryToGray.java
src/test/java/com/conversions/BinaryToGrayTest.java

Conversion from binary to gray code

Added Binary to Gray code conversion

---

ciphers/Caesar.java

Just two small things that in case the number was very big could be helpful.

Efficiency

---

src/main/java/com/Others/FastPower.java
src/main/java/com/Others/FastPowerTest.java

Added FastPower
We may calculate power with loops, but what if the index is too large ?
FastPower aims to calculate quickly in this circumstances with time complexity O(log k), where k is the index.

Added FastPower

---

src/main/java/com/search/DepthFirstSearch.java
src/test/java/com/search/DepthFirstSearchTest.java

Implemented the DepthFirstSearch in Java by creating a Binary Tree class and adding appropriate 'add' and 'get' methods. Also added a JUnit test :)

Added DepthFirstSearch.java and DepthFirstTestSearch.java

---

src/main/java/com/designpatterns/singletonpattern/Singleton.java
src/test/java/com/designpatterns/singletonpattern/SingletonTest.java

The singleton pattern is a design pattern that restricts the instantiation of a class to one "single" instance.
This is useful when exactly one object is needed to coordinate actions across the system. The term comes from the mathematical concept of a singleton.

Added Singleton Design pattern implementation in Java and its test

---

src/main/java/com/designpatterns/creational/builder/Desktop.java
src/main/java/com/designpatterns/creational/factory/Pentagon.java
src/main/java/com/designpatterns/creational/factory/Polygon.java
src/main/java/com/designpatterns/creational/factory/PolygonFactory.java
src/main/java/com/designpatterns/creational/factory/Square.java
src/main/java/com/designpatterns/creational/factory/Triangle.java
src/main/java/com/designpatterns/creational/singleton/Singleton.java
src/test/java/com/designpatterns/creational/builder/DesktopBuilderTest.java
src/test/java/com/designpatterns/creational/factory/PolygonFactoryTest.java
src/test/java/com/designpatterns/creational/singleton/SingletonTest.java

Added a sub package "creational" for creational type patterns. Planning to create other types of patterns such as structural, behavioral, etc.. A separate package for each type makes the code organized and look more professional.

Added a sub-package for "creational" in order to organize the code

---

Conversions/IntegerToRoman.java

Integer To Roman

---

Conversions/BinaryToOctal.java

The old version converts binary to decimal. This version fixes it.

Fix binary to octal conversion

---

README.md

Links in the dynamic programming column were **not pointing** to the right files so I fixed it in the Readme.md file.

Updated Dynamic Programming Links in Readme.md

---

README.md

Links in the miscellaneous column were not pointing to the right files.

Updated Miscellaneous Links in README.md

---

README.md

:hand: Hi! There :slightly_smiling_face: 
This PR adds a suggestion to use gitpod.io for contributing and generally playing around with the algorithms.
The goal of Gitpod to lower friction for collaboration on GitHub and other code hosting platforms by skipping the local setup, maintenance of such and automating workflows. It's free for open-source.
We could configure Gitpod with a Dockerfile so it pre-installs certain tools or packages, but it looked like most algorithms worked out of the box so I skipped additional configuration.

Lowers the barrier and friction for contributions and learning

---

Others/CountWords.java
Others/Palindrome.java

added a new method that counts words in a string. As per issue [#816](https://github.com/TheAlgorithms/Java/issues/816#issue-485845732), the method ignores all non-alphanumeric characters when counting words

Word count

---

Others/Palindrome.java

Added a new method that checks for palindrome while ignoring all non-alphanumeric characters. Just like the other methods, it all ignores case

ignore non-alphanumeric

---

DataStructures/Queues/Queues.java

Remove at front of queue
* `front = (front + 1) % maxSize;`
Insert at rear of queue
* `rear = (rear + 1) % maxSize;`

optimization

---

Maths/FindMaxRecursion.java
Maths/FindMinRecursion.java

Get max or min value using **divide and conquer** algorithm

Find max and min value by recursion

---

Others/CountChar.java

Now it is simplified without sacrificing accuracy.

The code was very verbose.

---

DynamicProgramming/Fibonacci.java
DynamicProgramming/RodCutting.java

The result has vbeen stored in tha different variable and then printed

Result print

---

DataStructures/Lists/SinglyLinkedList.java

* add `clear()` function to clear all nodes in list
Please review! @yanglbme

clear list

---

Maths/ParseInteger.java

parseInteger

---

DynamicProgramming/Fibonacci.java

https://github.com/TheAlgorithms/Java/issues/1008

Correction of iteration limit of fibOptimized

---

LICENSE

added license to the repository.

---

DataStructures/Lists/SinglyLinkedList.java

Add merge two sorted LinkedList algorithm
@yanglbme Please review. Thanks in advance.

upate SinglyLinkedList

---

Conversions/AnyBaseToDecimal.java
DataStructures/Lists/SinglyLinkedList.java
DataStructures/Stacks/BalancedBrackets.java

update AnyBaseToDecimal and optimization

---

Searches/JumpSearch.java

* add jump search algorithm
@yanglbme Please review!

add jump search algorithm

---

Others/BestFit.java
Others/FirstFit.java
Others/WorstFit.java

@stepfencurryxiao Here is my pull request. Could you please review it? :) Thanks.

Added Best/First/Worst Fit algorithm implementation

---

ciphers/AESEncryption.java

This library is deprecated with OpenJdk 11. Related issue https://github.com/TheAlgorithms/Java/issues/792

bytesToHex function is changed

---

Sorts/ShellSort.java

The test output is [4, 23, 23, 78, 78, 78, 231, 231, 231], I think it has a problem，
After changing，
Test data output [1, 4, 6, 9, 12, 23, 54, 78, 231]

I find a problem

---

src/main/java/com/search/TernarySearch.java
src/test/java/com/search/TernarySearchTest.java

Implement ternary search and tests.
This PR tries to help #474 . The algorithm is mainly from the master branch.

Implement ternary search

---

src/main/java/com/dataStructures/SinglyLinkedList.java
src/test/java/com/dataStructures/SinglyLinkedListTest.java

I added a singly linked list with test-driven development which is a powerful data structure when it comes to doing insertions and deletions. 
My code allows the user to add and remove nodes at any index and prints this data structure in the console for more readability.
**### NB: I am new to the software engineering community and it is my first commit. I did my best and if anything is wrong with my code I can change it anytime, I am eager to learn more.**

Add singly linked list

---

Sorts/BitonicSort.java

#1297
I added a new algorithm to the code. the BitonicSort to the package Sort.
i hope you can accept my pull request.
Kind regards

Add a new sort algorithm, Sort/BitonicSort

---

DIRECTORY.md

Add prime factorization algorithm in /maths

---

Maths/Factorial.java

I have added scanner in the factorial program to make finding factorial easy

Added scanner in the factorial program to make finding factorial easy

---

src/main/java/com/ciphers/CaesarBruteForce.java
src/test/java/com/ciphers/CaesarBruteForceTest.java

Recursively brute-force Caesar cipher.

CaesarBruteForce

---

Maths/Factorial.java

Adding try/catch and recursion to optimize the code

Using Try/catch and recursion

---

src/main/java/com/conversions/HexadecimalToBinary.java
src/main/java/com/conversions/HexadecimalToDecimal.java
src/test/java/com/conversions/HexadecimalToBinaryTest.java
src/test/java/com/conversions/HexadecimalToDecimalTest.java

I have noticed that some conversions are missing, so I started by adding the hexadecimal to decimal and the hexadecimal to binary ones, if you approve it I can work on the other ones.
My code converts a hexadecimal number to a decimal one.
**NB: I am new to the software engineering community. I did my best and if anything is wrong with my code I can change it anytime, I am eager to learn more.**

Add hexadecimal to binary and hexadecimal  to decimal conversions

---

Conversions/DecimalToBinary.java
Conversions/OctalToHexadecimal.java
DataStructures/DynamicArray/DynamicArray.java
DataStructures/Graphs/BellmanFord.java
DataStructures/Graphs/MatrixGraphs.java
DataStructures/Heaps/HeapElement.java
DataStructures/Heaps/MaxHeap.java
DataStructures/Heaps/MinHeap.java
DataStructures/Lists/CircleLinkedList.java
DataStructures/Lists/DoublyLinkedList.java
DataStructures/Stacks/NodeStack.java
DataStructures/Trees/LevelOrderTraversal.java
DataStructures/Trees/LevelOrderTraversalQueue.java
DataStructures/Trees/ValidBSTOrNot.java
DynamicProgramming/LongestIncreasingSubsequence.java
DynamicProgramming/MatrixChainMultiplication.java
Maths/GCD.java
Others/Dijkstra.java
Others/TopKWords.java
Others/TowerOfHanoi.java
Searches/IterativeBinarySearch.java
Sorts/QuickSort.java
ciphers/Caesar.java
ciphers/ColumnarTranspositionCipher.java
divideconquer/ClosestPair.java

Hello!
I fixed  8XCorrectness_Bugs + 10XBad_Practice_Bugs + 14XDodgy_Code_Bugs after i used SpotBugs on this project. Hope it will help you.
Thx!

Fixed 8XCorrectness_Bugs + 10XBad_Practice_Bugs + 14XDodgy_Code_Bugs

---

build.gradle

it doesn't buid correctly because no junit dependency。fix it

add junit for test paass

---

Maths/CountDigit.java

Added a program that will **count the number of digits** of a user given number.

Added Count Digit program

---

src/main/java/com/caching/LFUCache.java
src/test/java/com/caching/LFUCacheTest.java

Addresses issue #1370 partially.
Added new LFU Cache 
Added test for the implementation
Implements cache with Least Frequently Used algorithm

Added LFU Cache implementation

---

Maths/FindMax.java
Maths/FindMaxRecursion.java
Maths/FindMin.java
Maths/FindMinRecursion.java

* add function overriding
* update test
* reduce code

Update max and findMax function

---

DIRECTORY.md
Sorts/BubbleSortRecursion.java

Bubble sort algorithm implements using recursion

BubbleSort Recursion

---

DIRECTORY.md
Maths/NumberOfDigits.java
Others/Armstrong.java

* fix armstrong number
* add NumberOfDigits

update armstrong number and add NumberOfDigits

---

DataStructures/Lists/ListAddnFun.java

Updates include:
add no-args constructor
add whitespace
use public class LinkedList
use private fields

Update and rename ListAddnFun to ListAddnFun.java

---

Maths/AbsoluteMax.java
Maths/AbsoluteMin.java
Maths/AbsoluteValue.java
Maths/MaxValue.java
Maths/MinValue.java
Maths/PythagoreanTriple.java

PythagoreanTriple.java is a function that determines whether its inputs, a,b,c are a Pythagorean triple.
returns true if a^2 + b^2 = c^2 and all are positive non-zero values, false otherwise
Adding assert statements to AbsoluteMax, AbsoluteMin, AbsoluteValue, MinValue, and MaxValue helps for testing

Add PythagoreanTriple.java and Add assert statements

---

DataStructures/Lists/DoublyLinkedList.java

I have added two methods:
1. insertElementByIndex - add an element to specified position.
2. clearList - clears the DoublyLinkedList.
Fixed some errors
closes issue #1378

Added insert element by index and clearList to DoublyLinkedList.java

---

DIRECTORY.md
DataStructures/Trees/BSTIterative.java
DataStructures/Trees/BSTRecursive.java

Any changes/suggestions is welcome.

DS: Binary Search Tree added Closes #1420

---

src/main/java/com/caching/LFUCache.java
src/main/java/com/caching/LRUCache.java
src/main/java/com/ciphers/CaesarBruteForce.java
src/main/java/com/conversions/HexadecimalToBinary.java
src/main/java/com/dataStructures/BinaryTree.java
src/main/java/com/dataStructures/DisjointSet.java
src/main/java/com/dataStructures/GeneralQueue.java
src/main/java/com/dataStructures/IntQueue.java
src/main/java/com/dataStructures/SinglyLinkedList.java
src/main/java/com/dataStructures/Stack.java
src/main/java/com/matchings/stableMatching/GaleShapley.java
src/test/java/com/dataStructures/BinaryTreeTest.java
src/test/java/com/dataStructures/DisjointSetTest.java
src/test/java/com/dataStructures/GeneralQueueTest.java
src/test/java/com/dataStructures/IntQueueTest.java
src/test/java/com/dataStructures/SinglyLinkedListTest.java
src/test/java/com/dataStructures/StackTest.java
src/test/java/com/matchings/stableMatching/GaleShapleyTest.java

Reverts TheAlgorithms/Java#1429 because of build failed

Revert "Fixed code smells after running sonarqube on the project"

---

DIRECTORY.md
strings/CharactersSame.java
strings/CheckAnagrams.java
strings/Lower.java
strings/Pangram.java
strings/Upper.java

Added more algorithms to strings folder

---

Maths/PrimeFactorization.java

Prevent this memory leak. Add ` scanner.close();`

Fix memory leak

---

DynamicProgramming/MinimumSumPartition.java

Modify to prevent memory leaks.

Modify to prevent memory leaks.

---

DIRECTORY.md
strings/Rotation.java

Added rotation string

---

Sorts/BucketSort.java

Updated BucketSort

---

DIRECTORY.md
Maths/Area.java
Maths/PowRecursion.java
Maths/SumOfArithmeticSeries.java

Added Arithmetic Series

---

DataStructures/Stacks/StackArrayList.java

Updated StackArrayList

---

DIRECTORY.md
ProjectEuler/Problem06.java

Created Problem06 in Project Euler

---

.github/workflows/gradle.yml

Fixed actions on pull requests

Fixed actions on pull requests

---

.github/workflows/gradle.yml

Fixed syntax error

---

src/main/java/com/others/RoundRobin.java
src/test/java/com/others/RoundRobinTest.java

Added an implementation of Round Robin algorithm with tests. Round Robin algorithm is an process scheduling algorithm.

Implementation for Round Robin Algorithm in Java with tests

---

DIRECTORY.md
ProjectEuler/Problem07.java

Created Problem07 in Project Euler

---

DIRECTORY.md
DataStructures/Lists/MergeSortedSinglyLinkedList.java
DataStructures/Lists/SinglyLinkedList.java
ProjectEuler/Problem09.java
ProjectEuler/Problem10.java

* Update SinglyLinkedList
* Refactor MergeSortedSinglyLinkedList to single file
* Create Problem09 and Problem10 in Project Euler
Previous version of SinglyLinkedList does not store value. We should use head pointer instead of head node.

Updated SinglyLinkedList

---

DynamicProgramming/SubsetSum.java

Created SubsetSum.java

---

DataStructures/Lists/SinglyLinkedList.java

Add comment above parameterised constructor

---

divideconquer/ClosestPair.java

Remove unnecassary variable usage.

Hacktoberfest: Remove unnecassary variable usage.

---

DynamicProgramming/LongestPalindromicSubsequence.java
DynamicProgramming/LongestPalindromicSubsequenceTests.java

I added the Longest Palindromic Subsequence algorithm
Issue #1709

Fixes: #1709 Longest palindromic subsequence 

---

.github/workflows/prettier.xml

Add prettier

---

src/main/java/com/string/Alphabetical.java
src/test/java/com/string/AlphabeticalTest.java

Incorporate the class Alphabetical from string package

---

.github/workflows/build.yml
.github/workflows/checkstyle.yml

fixed checkstyle action

---

Maths/BinaryPow.java

Added Binary Exponentiation Fixes:#1943

---

Sorts/ShellSort.java

Update shell sort documentation

---

.github/workflows/checkstyle.yml
Sorts/BubbleSort.java
Sorts/ShellSort.java

Fixed BubbleSort Docs

---

.github/workflows/checkstyle.yml
Sorts/BubbleSort.java

Fixed checkstyle and docs

---

src/main/java/com/string/Interleave.java

Add New String Interleave Class and Tests

---

src/main/java/com/others/Ackermann.java
src/test/java/com/others/AckermannTest.java

Added Ackermann function 

---

src/main/java/com/string/Upper.java
src/test/java/com/string/UpperTest.java

Incorporate the class Upper from string package

---

ProjectEuler/Problem03.java

Solution to Euler Project Problem03

---

src/main/java/com/string/ReverseWords.java
src/test/java/com/string/ReverseWordsTest.java

Fix ReverseWords class and test

---

DynamicProgramming/MinimumPathSum.java

add MinimumPathSum DynamicProgramming

---

DataStructures/Graphs/BellmanFord.java

Fixes: #2057

---

DataStructures/Graphs/BellmanFord.java

Fixes: #2056

---

DataStructures/Graphs/BellmanFord.java

Fixed a typo in 'distance' spelling in line 51.
Fixes: #2055

Fixed Spelling error. Fixes: #2055

---

strings/CheckAnagrams.java

**The original solution** works. but **runs at complexity of O(N*log(N))**
whereas N := max(s1.length(), s2,length) [maximum length of two Strings]
the complexity of N*log(N) is due to sorting the character array.
**my solution runs at a linear complexity, O(N).**
instead of sorting, I use an HashMap, and 3 successive loops.
1. I initialize the hash map.
2.  **first loop:** I count the number of appearances in the first String and update the hashmap. I do that by iterating through the characters. if a character has not appeared yet, I put the value of 1. otherwise I add 1 to its value.
3. **second loop**: I iterate through each character in the second string. if a character does not appear in the hashmap. I return false. Otherwise, I reduce its value by 1.
4. **third loop**: I iterate …

reducing complexity to linear complixity

---

CONTRIBUTING.md

first time trying this so forgive me if I've made some errors but I noticed some spelling errors on the document and wanted to amend them for you whilst getting some practice with GitHub.

fix spelling errors on CONTRIBUTING.md

---

REVIEWER.md

Added Guildelines for Reviewers and Maintainers.

added reviewers and maintainers guidelines

---

Sorts/SelectionSort.java

Fixes the sort order

---

DynamicProgramming/RodCutting.java

- [ x] Fix a bug or typo in an existing algorithm?
- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized.
- [ x] I know that pull requests will not be merged if they fail the automated tests.
- [ x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ x] All new Java files are placed inside an existing directory.
- [ x] All filenames are in all uppercase characters with no spaces or dashes.
- [ x] All functions and variable names follow Java naming conventions.
- [ x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ x] If this pull request resolves one or …

Var size is redunant

---

README.md

I removed the Development branch instructions as stated in issue number #2116

Removed Development part from README.md file

---

Sorts/InsertionSort.java

udpate insertion sort

---

Sorts/SelectionSort.java

selection sort

---

Searches/BinarySearch.java

Finding median using the previous formula may carry the median value out of range. Therefore, updated the formula with a better one.

Formula to find median in Binary Search changed

---

DataStructures/Graphs/BellmanFord.java

fixed typo vertes to vertex Fixes: #{2189}

---

Maths/EulerMethod.java

I'm trying to avoid to prettier-check-error by making the commit from the master-branch. It's the same algorithm as in #2130

Add Euler method (from master)

---

Others/KochSnowflake.java

add Koch snowflake

---

README.md

- Add Discord badge in `README.md`.

feat: Add Discord badge in `README.md`

---

Sorts/MergeSort.java

fixed merge sort

---

strings/HorspoolSearch.java
strings/matching/Horspool.java

I missed the email for #1397 asking for the PR in master. I have cleaned up the code a bit 
recently and tested it with the same tests.
#1397 first PR that was accepted

Add Horspool string matching algorithm (#1397 old accepted PR on Development)

---

ciphers/Vigenere.java

- Fixed recreation of multiple String Objects

Replaced String with StringBuilder.

---

DataStructures/DynamicArray/DynamicArray.java

fix issue 2251

---

CONTRIBUTING.md

Fixing broken contributing link

---

DataStructures/Stacks/README.md

create Readme.md for stacks

---

Maths/PiNilakantha.java

class which calculates Pi using Nilakanthas infinite series
https://github.com/TheAlgorithms/Java/issues/2323

Added class that calculated Pi

---

Others/RotateMatriceBy90Degree.java

Algorithm to rotate a matrix of order n by 90 degree

Rotate matrix by 90 degree

---

strings/CheckVowels.java

CheckVowels Algorithm added

---

Maths/Area.java

add surfaceAreaCylinder (hacktoberfest)

---

Maths/KrishnamurthyNumber.java

This is a program to check if a number is a Krishnamurthy number or not.
A number is a Krishnamurthy number if the sum of the factorials of the digits of the number is equal to the number itself.
For example, 1, 2 and 145 are Krishnamurthy numbers.

Adding KrishnamurthyNumber.java (hacktoberfest)

---

Conversions/IntegerToRoman.java
Misc/PalindromePrime.java
Misc/WordBoggle.java

Made a few minor enhancements in the comments and fixed a few typos.

Fixed a few minor typos in comments

---

DataStructures/Lists/detect_and_create_loop.jav

Detect a loop in linked list

---

Maths/AutomorphicNumber.java

Automorphic Number

---

DataStructures/Graphs/KahnsAlgorithm.java

Added Kahn's Algorithm for topological sorting of a DAG(Directed Acyclic graph).

Kahn's Algorithm for topological sorting of a graph(HacktoberFest2021)

---

Others/Implementing_auto_completing_features_using_trie.java
Others/Sudoku.java
Strings/List_all_Possible_Words_From_Phone_Digits.java

Add "Implement auto completing features using trie " in "OTHER" section

Implement_auto_completing_features_using_trie

---

DynamicProgramming/RegexMatching.java

WildCard Pattern Matching- Dynamic Programming #2419

WildCard Pattern Matching- Dynamic Programming #2419

---

Searches/howManyTimesRotated.java

Added the script in Searches Folder

Added script in JAVA for how many times an array has been rotated in O(log N) 

---

Conversions/OctalToHexadecimal.java
DynamicProgramming/RegexMatching.java
Sorts/BitonicSort.java
Sorts/PancakeSort.java

Fix typos in comments

---

DataStructures/Stacks/MaximumMinimumWindow.java

Features : 
1. Added a class `MaximumMinimumWindow` which has the logic of calculating Maximum of minimum for every window size.
2. The function `calculateMaxOfMin` uses Stack data structure.
3. Code Reformatted to make it look clean.
4. Documentation added.

Implemented MinMax solution using Stack

---

DivideAndConquer/BinaryExponentiation.java

Resolves issue [2355](https://github.com/TheAlgorithms/Java/issues/2355)

Added BinaryExponentiation.java

---

DataStructures/Graphs/DIJSKSTRAS_ALGORITHM.java

issue : https://github.com/TheAlgorithms/Java/issues/2470
Djikstra's algorithm: https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/
Fixes: #2470 .

Dijskstra's Algorithm for shortest path added(Fixes: #2470)

---

DataStructures/HashMap/Readme.md

Replace html syntax by markdown equivalent. 
All text isn't changed.
https://github.com/TheAlgorithms/Java/issues/2499

Fixes: #2499: replace html syntax by markdown equivalent

---

Maths/NonRepeatingElement.java

Two non repeating elements in an array

---

DataStructures/Queues/README.md

Create README.md for Queue

---

Sorts/OddEvenSort.java

Odd even sort

---

DIRECTORY.md

Update directory. Fixes #2785.

---

Maths/Area.java

Finally, Added surface area of Cone and Hemisphere

---

DataStructures/Lists/DoublyLinkedList.java

- ~~Documentation change?~~
- ~~All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.~~
- ~~If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.~~

Create a method to reverse a doubly linked list

---

Maths/MatrixUtil.java

Add MatrixUtil for matrix operations add, subtract and multiply

Add MatrixUtil for matrix operations

---

Searches/DepthFirstSearch.java

Add simple DepthFirstSearch with Java Streams

Add DepthFirstSearch with Java Streams

---

DataStructures/Lists/DoublyLinkedList.java

- ~~Documentation change?~~
- ~~All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.~~
- ~~If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.~~

Allow printing of a doubly linked list in reverse order

---

Maths/Area.java

Fixed typo

---

Sorts/BubbleSort.java

update bubble sort

---

DataStructures/Graphs/MatrixGraphs.java

Simply adds some missing documentation for the class `MatrixGraphs` data structure.
- ~~Add an algorithm?~~
- ~~All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.~~
- ~~If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.~~

Improve documentation for `MatrixGraphs`

---

Maths/Area.java
Searches/BreadthFirstSearch.java

Add BreadthFirstSearch

---

DataStructures/Queues/Deques.java

This adds a double ended queue (deque) to the data structures under queues. A deque is effectively a doubly-linked list/queue/stack combination that only allows adding, removing, and peeking from the beginning and end. Because of the name, I chose to put this in the queue section (I don't believe it is large/important enough to warrant its own section)
- ~~Documentation change?~~
- ~~If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.~~

Add double ended queue (deque) to queues data structures

---

Others/Damm.java

Add Damm algorithm implementation
https://github.com/TheAlgorithms/Java/issues/2814

Fixes: #2814 Add Damm algorithm implementation

---

src/main/java/com/thealgorithms/datastructures/queues/CircularQueue.java

Fixes: NoClassDefFoundError in CircularQueue.java

---

src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
src/main/java/com/thealgorithms/datastructures/lists/README.md
src/main/java/com/thealgorithms/datastructures/lists/RandomNode.java

Add algorithms_random_node.java in lists section

---

src/main/java/com/thealgorithms/datastructures/stacks/NextGraterElement.java
src/main/java/com/thealgorithms/datastructures/stacks/NextSmallerElement.java

Fixes Issue : [#2854](https://github.com/TheAlgorithms/Java/issues/2854)

Added Next-Grater , Next-Smaller Elements using Stack

---

src/main/java/com/thealgorithms/others/ArrayLeftRotation.java
src/test/java/com/thealgorithms/others/ArrayLeftRotationTest.java

Added Array Left Rotation.
A left rotation operation on an array shifts each of the array's elements given integer n unit to the left.

Added Array Left Rotation

---

src/main/java/com/thealgorithms/maths/PascalTriangle.java
src/test/java/com/thealgorithms/maths/PascalTriangleTest.java
src/test/java/com/thealgorithms/others/ArrayLeftRotationTest.java

My Commit for the Issue #2864 Pascal's Triangle

---

DIRECTORY.md
src/main/java/com/thealgorithms/maths/PronicNumber.java
src/test/java/com/thealgorithms/maths/PronicNumberTest.java

Pronic Number Implemenation #2856

Add Pronic Number Implementation

---

src/main/java/com/thealgorithms/ciphers/Caesar.java

added bruteforce to the caesar ciphers

---

DIRECTORY.md

I have edited the formatting for the project structure under the `test` folder so that it is consistent with the rest of the file.

Correct the formatting errors in DIRECTORY.md

---

src/main/java/com/thealgorithms/maths/Volume.java

Added volume of prism and pyramid

---

src/test/java/com/thealgorithms/maths/PascalTriangleTest.java

updates in indentation

---

src/main/java/com/thealgorithms/maths/KaprekarNumbers.java
src/test/java/com/thealgorithms/maths/KaprekarNumbersTest.java

Fixes [Issue 2890](https://github.com/TheAlgorithms/Java/issues/2890)

Added BigInteger to karprekar number

---

src/main/java/com/thealgorithms/strings/LongestPalindromicSubstring.java

Removing unnecessary semi-colon ';'

Fixing Typo in LongestPalindromicSubstring - ';'

---

src/main/java/com/thealgorithms/maths/SquareRootWithBabylonianMethod.java
src/test/java/com/thealgorithms/maths/SquareRootwithBabylonianMethodTest.java

added java code of babylonian method

---

src/main/java/com/thealgorithms/maths/Gaussian.java
src/test/java/com/thealgorithms/maths/GaussianTest.java

Refactored the algorithm. Took all the code out from main and put it in 3 different functions, thus lowering the CC. Changed the code so it does not take the input data from the console, rather it takes it from an ArrayList. Changed the output of the answer, instead of getting and system.out.println, I return an ArrayList with the answers. 
Added one Junit test to test the function and to see that all the code had 100% coverage from it.

Issue/2959 - Refactoring algorithm & added Junit test

---

src/main/java/com/thealgorithms/maths/FFT.java
src/main/java/com/thealgorithms/maths/Gaussian.java
src/test/java/com/thealgorithms/maths/GaussianTest.java

Issue/2961 - small bug FFT.java

---

src/main/java/com/thealgorithms/datastructures/stacks/PostfixToInfix.java

Issue https://github.com/TheAlgorithms/Java/issues/2339

Add Postfix to Infix using Stack (#2339)

---

src/main/java/com/thealgorithms/datastructures/graphs/Graphs.java

The spelling of vertices was wrong its fixed now!

renamed "verticies" as "vertices"

---

.gitignore

fix:removed white spaces

---

src/main/java/com/thealgorithms/backtracking/FloodFill.java
src/test/java/com/thealgorithms/backtracking/FloodFillTest.java

Fixes: #2836

---

DIRECTORY.md

Fix outdated directory.md

---

src/test/java/com/thealgorithms/strings/PalindromeTest.java

[TEST] adds test for Palindrome

---

src/test/java/com/thealgorithms/strings/UpperTest.java

[TEST] adds test for Upper

---

src/main/java/com/thealgorithms/strings/Anagrams.java
src/test/java/com/thealgorithms/strings/AnagramsTest.java

[TEST] adds test for Anagrams

---

src/main/java/com/thealgorithms/strings/CheckVowels.java

Fix CheckVowels (#2990)

---

src/main/java/com/thealgorithms/strings/Upper.java

Fix Null Pointer Exception in strings/Upper

---

.github/workflows/build.yml
.github/workflows/prettify.yml
.github/workflows/update_directory.yml

Change some Actions workflow to run only if code related files changes

Run Actions only if code related files changes

---

src/main/java/com/thealgorithms/maths/AbsoluteMin.java
src/test/java/com/thealgorithms/maths/AbsoluteMinTest.java

See: https://github.com/TheAlgorithms/Java/issues/3021

Code refactor for AbsoluteMin improvements

---

src/main/java/com/thealgorithms/maths/ADTFraction.java
src/test/java/com/thealgorithms/maths/ADTFractionTest.java

See: https://github.com/TheAlgorithms/Java/issues/3015

Code refactor for ADTFraction improvements

---

src/main/java/com/thealgorithms/maths/AliquotSum.java
src/test/java/com/thealgorithms/maths/AliquotSumTest.java

See: https://github.com/TheAlgorithms/Java/issues/3026

Code refactor for AliquotSum improvements

---

src/main/java/com/thealgorithms/maths/AbsoluteMax.java

See: https://github.com/TheAlgorithms/Java/issues/3028

Code refactor for AbsoluteMax improvements 2

---

src/main/java/com/thealgorithms/maths/AbsoluteMin.java

See: https://github.com/TheAlgorithms/Java/issues/3030

Code refactor for AbsoluteMin improvements 2

---

src/main/java/com/thealgorithms/sorts/PigeonholeSort.java

Add pigeonhole sort (#2992)

---

src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMap.java

https://github.com/TheAlgorithms/Java/issues/3007

Added else clause for node deletion

---

src/main/java/com/thealgorithms/sorts/WiggleSort.java
src/test/java/com/thealgorithms/sorts/WiggleSortTest.java

Wigglesort

---

src/main/java/com/thealgorithms/sorts/DutchNationalFlagSort.java
src/test/java/com/thealgorithms/sorts/DutchNationalFlagSortTest.java

merges #3024
improves upon src/main/java/com/thealgorithms/sorts/DNFSort.java (might possibly replace it)

Dutch national flag sort

---

src/main/java/com/thealgorithms/maths/HeronsFormula.java
src/test/java/com/thealgorithms/maths/HeronsFormulaTest.java

Added tests for Heron's Formula + removed main()

---

src/main/java/com/thealgorithms/ciphers/Blowfish.java
src/test/java/com/thealgorithms/ciphers/BlowfishTest.java

Implementation of blowfish algorithm https://github.com/TheAlgorithms/Java/issues/3041

Blowfish algorithm implementation

---

src/main/java/com/thealgorithms/sorts/TimSort.java

[Modify]: Changed bugs in TimSort to run it correctly

---

src/test/java/com/thealgorithms/maths/GCDTest.java
src/test/java/com/thealgorithms/maths/PrimeCheckTest.java

[TEST] Add tests for GCD algorithm based on MC/DC standard and PrimeCheck algorithm based on All-DU-Paths standard

---

src/test/java/com/thealgorithms/maths/PythagoreanTripleTest.java

Add Test for PythagoreanTriple

---

src/test/java/com/thealgorithms/maths/FindMinTest.java
src/test/java/com/thealgorithms/maths/TestFindMin.java

Creat Test Case for FindMin func()

---

src/test/java/com/thealgorithms/maths/FindMinTest.java

Add tests for findMin

---

src/test/java/com/thealgorithms/maths/TestArmstrong.java

Add test function for Armstrong

---

src/main/java/com/thealgorithms/datastructures/bloomfilter/BloomFilter.java

[Related Issue](https://github.com/TheAlgorithms/Java/issues/3114)

Fixes: #3114 Reduce memory usage of bloom filter

---

src/main/java/com/thealgorithms/datastructures/lists/SkipList.java
src/test/java/com/thealgorithms/datastructures/lists/SkipListTest.java

[Related Issue](https://github.com/TheAlgorithms/Java/issues/3153)

Add skip list

---

.github/workflows/update_directory.yml
DIRECTORY.md

https://github.com/TheAlgorithms/Java/issues/3155

Fix update dir job

---

src/main/java/com/thealgorithms/strings/HammingDistance.java
src/test/java/com/thealgorithms/strings/HammingDistanceTest.java

Add Hamming Distance 

---

src/main/java/com/thealgorithms/sorts/QuickSort.java
src/test/java/com/thealgorithms/sorts/QuickSortTest.java

[#3008](https://github.com/TheAlgorithms/Java/issues/3008)

Add quick sort tests

---

src/main/java/com/thealgorithms/strings/CheckVowels.java

This change has shortened the code for the hasVowels() method and made it more understandable
Signed-off-by: Arthita Paul <arthitapaul958@gmail.com>

add checkVowels-modifications

---

src/main/java/com/thealgorithms/datastructures/trees/TreeRandomNode.java

- [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized.
- [x ] I know that pull requests will not be merged if they fail the automated tests.
- [x ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new Java files are placed inside an existing directory.
- [ x] All filenames are in all uppercase characters with no spaces or dashes.
- [ x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ x] If this pull request resolves one or more open issues then the commit message contains …

Fix TreeRandomNode Algorithm

---

src/main/java/com/thealgorithms/maths/BinaryPow.java
src/test/java/com/thealgorithms/maths/BinaryPowTest.java

- [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized.
- [ x] I know that pull requests will not be merged if they fail the automated tests.
- [x ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new Java files are placed inside an existing directory.
- [ x] All filenames are in all uppercase characters with no spaces or dashes.
- [x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x ] If this pull request resolves one or more open issues then the commit message contains …

Add test case to BinaryPow Algorithm

---

src/main/java/com/thealgorithms/maths/BinomialCoefficient.java
src/test/java/com/thealgorithms/maths/BinomialCoefficientTest.java

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized.
- [x ] I know that pull requests will not be merged if they fail the automated tests.
- [x ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new Java files are placed inside an existing directory.
- [x ] All filenames are in all uppercase characters with no spaces or dashes.
- [x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x ] If this pull request resolves one or more open issues then the commit message contains …

Add test case to Binomial Coefficient Algorithm

---

src/main/java/com/thealgorithms/datastructures/lists/CircleLinkedList.java

fix CircleLinkedList toString

---

src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArray.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArrayList.java
src/test/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArrayListTest.java
src/test/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArrayTest.java

- Implementation of generic hashmaps #3193

implementation of generic hashmaps

---

src/main/java/com/thealgorithms/datastructures/heaps/GenericHeap.java

Fix missing package paths (#3196)

---

src/main/java/com/thealgorithms/maths/DistanceFormula.java
src/test/java/com/thealgorithms/maths/DistanceFormulaTest.java

Three new distance formula:
-Manhattan Distance
-Hamming Distance
-Minkowski Distance
*Test cases are provided
Renaming a function:
-distance to euclideanDistance to make more specific
[4 Distance Measures for Machine Learning](https://machinelearningmastery.com/distance-measures-for-machine-learning/)

Added three new distance formula and renamed a function

---

src/main/java/com/thealgorithms/searches/KMPSearch.java
src/test/java/com/thealgorithms/searches/KMPSearchTest.java

An important issue in computer science is pattern searching. Pattern searching methods display the search results when we do a string search in a database, browser, or notepad/word file.
[Knuth–Morris–Pratt algorithm](https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm)

Create a new KMP Algorithm

---

src/main/java/com/thealgorithms/sorts/StrandSort.java
src/test/java/com/thealgorithms/sorts/StrandSortTest.java

[Strand sort algorithm](https://en.wikipedia.org/wiki/Strand_sort)

Create a new Strand Sort Algorithm

---

src/main/java/com/thealgorithms/sorts/BinaryInsertionSort.java
src/test/java/com/thealgorithms/sorts/BinaryInsertionSortTest.java

[Binary Insertion Sort](https://www.geeksforgeeks.org/binary-insertion-sort/)

Create a new Binary Insertion Sort Algorithm

---

src/main/java/com/thealgorithms/datastructures/trees/LazySegmentTree.java
src/test/java/com/thealgorithms/datastructures/trees/LazySegmentTreeTest.java

Add new Lazy Segment Tree with range updating feature.

Add Lazy Segment Tree Algorithm

---

CONTRIBUTING.md

grammatical correction in CONTRIBUTING.md

---

src/main/java/com/thealgorithms/maths/JosephusProblem.java
src/test/java/com/thealgorithms/maths/JosephusProblemTest.java

Fixes: #3207 
https://en.wikipedia.org/wiki/Josephus_problem

Add Josephus Problem Recursive Solution

---

src/main/java/com/thealgorithms/datastructures/trees/KDTree.java
src/test/java/com/thealgorithms/datastructures/trees/KDTreeTest.java

K-D Tree implementation

---

src/main/java/com/thealgorithms/backtracking/Permutation.java
src/main/java/com/thealgorithms/maths/Ceil.java
src/main/java/com/thealgorithms/maths/DigitalRoot.java
src/main/java/com/thealgorithms/maths/PascalTriangle.java
src/main/java/com/thealgorithms/maths/SquareRootWithBabylonianMethod.java
src/test/java/com/thealgorithms/backtracking/CombinationTest.java
src/test/java/com/thealgorithms/sorts/DutchNationalFlagSortTest.java

Remove unused imports from source codes

Remove unused imports

---

src/main/java/com/thealgorithms/datastructures/trees/RedBlackBST.java
src/main/java/com/thealgorithms/maths/SquareRootWithNewtonRaphsonMethod.java
src/test/java/com/thealgorithms/maths/SquareRootWithNewtonRaphsonTestMethod.java

***Newton-Raphson Method***
The formula is used to calculate the square root of a number. Added the program in the maths directory and also added the documentation for it in the code.
Let me know if any changes has to be made.

Adding the program to calculate square root using Newton Raphson method

---

src/main/java/com/thealgorithms/searches/BreadthFirstSearch.java

...because it's more efficient while still giving the correct result.

Replace List in BFS with Queue

---

src/main/java/com/thealgorithms/searches/BinarySearch2dArray.java
src/test/java/com/thealgorithms/searches/BinarySearch2dArrayTest.java

Added the program to search for the target element using **Binary Search** in the provided **2D array**. The program is modified but uses the same approach as it is built on top of binary search.

Binary Search in 2D Array

---

src/main/java/com/thealgorithms/maths/MobiusFunction.java
src/test/java/com/thealgorithms/maths/MobiusFunctionTest.java

[#3232](https://github.com/TheAlgorithms/Java/issues/3232)

Implement mobius function

---

src/main/java/com/thealgorithms/searches/BinarySearch.java

Fixes: #3248

---

pom.xml
src/main/java/com/thealgorithms/maths/Perimeter.java
src/test/java/com/thealgorithms/maths/perimeterTest.java

I went through the Maths section of the repository and found programs for volume and area but not perimeter. So this is a program to calculate perimeter of geometrical objects.

Perimeter Calculator

---

src/main/java/com/thealgorithms/others/countSetBits.java
src/test/java/com/thealgorithms/others/countSetBitsTest.java

I have used Brian Kernighans algorithm to count set bits of a number . I have add this file in others folder and the test file in the corresponding folder in test folder.

Added file to calculate set bits in a number

---

src/main/java/com/thealgorithms/strings/Pangram.java
src/test/java/com/thealgorithms/strings/PangramTest.java

Reimplemented the pangram check to be more performant and readable, fix some typos in the file aswell
\-

Fix some typos, reimplement pangram check

---

src/main/java/com/thealgorithms/maths/PollardRho.java
src/test/java/com/thealgorithms/maths/PollardRhoTest.java

Add pollard rho algorithm

---

DIRECTORY.md

The Directory.md was kind of messed up as the structure was not accurate.
Fixes: Issue #3271

Fixed the errors in Directory.md

---

src/main/java/com/thealgorithms/sorts/BubbleSort.java
src/test/java/com/thealgorithms/sorts/BubbleSortTest.java

Added unit tests for the [BubbleSort](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/sorts/BubbleSort.java) algorithm and removed assert statements from the algorithm class.
Closes #3274

Closes #3274 Add BubbleSort unit tests

---

src/main/java/com/thealgorithms/datastructures/caches/LRUCache.java
src/main/java/com/thealgorithms/datastructures/caches/MRUCache.java
src/test/java/com/thealgorithms/datastructures/caches/LRUCacheTest.java
src/test/java/com/thealgorithms/datastructures/caches/MRUCacheTest.java

- Added tests for LRUCache and MRUCache
- Removed main methods

#3263 LRUCacheTest and MRUCacheTest

---

src/main/java/com/thealgorithms/maths/PrimeFactorization.java
src/test/java/com/thealgorithms/maths/PrimeFactorizationTest.java

[#3276](https://github.com/TheAlgorithms/Java/issues/3276)

fix: Prime factorization algorithm

---

src/main/java/com/thealgorithms/maths/LiouvilleLambdaFunction.java
src/test/java/com/thealgorithms/maths/LiouvilleLambdaFunctionTest.java

algorithm: Liouville lambda function implementation

---

pom.xml

Fixes #3287 Duplicate artifact maven-compiler-plugin in pom.xml

Fixes #3287 Duplicate artifact maven-compiler-plugin in pom.xml

---

src/main/java/com/thealgorithms/maths/CollatzConjecture.java
src/test/java/com/thealgorithms/maths/CollatzConjectureTest.java

algorithm: Collatz Conjecture

---

src/main/java/com/thealgorithms/datastructures/buffers/CircularBuffer.java
src/test/java/com/thealgorithms/datastructures/buffers/CircularBufferTest.java

1. Fix the bug of overflowing the fields _write_index and _read_index.
2. Refactor the code to follow Java naming conventions.
3. Make the data structure generic.
4. Remove redundant code.
5. Add unit tests (including concurrency case with Producers and Consumers).

CircularBuffer: Bug fix, Refactoring + add unit tests

---

src/main/java/com/thealgorithms/devutils/searches/MatrixSearchAlgorithm.java
src/main/java/com/thealgorithms/searches/RowColumnWiseSorted2dArrayBinarySearch.java
src/test/java/com/thealgorithms/searches/RowColumnWiseSorted2dArrayBinarySearchTest.java

Added an interface for search algorithms that use matrixes and formatted the classes that implement the interface.
Closes #3461

Closes #3461 Add an interface for matrix search algorithms

---

src/main/java/com/thealgorithms/maths/SumWithoutArithmeticOperators.java
src/test/java/com/thealgorithms/maths/SumWithoutArithmeticOperatorsTest.java

Added an algorithm to sum two numbers without using any mathematical operators
This PR is in reference to #3435

Code for #3435 - Sum numbers without using any mathematical operators

---

src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMap.java

- Improved methods `findEnd(Node)` and `findKey(int key)`
Using loops instead of recursive function calls to maximize the efficiency and speed.

Optimize Hashmap implementation

---

src/main/java/com/thealgorithms/dynamicprogramming/SubsetCount.java
src/test/java/com/thealgorithms/dynamicprogramming/SubsetCountTest.java

Contribution with reference to Issue #3553

DP Solution to Subset Count

---

src/main/java/com/thealgorithms/backtracking/PowerSum.java
src/test/java/com/thealgorithms/backtracking/PowerSumTest.java

#3594: Need test cases for many of the Algorithms

Create tests for PowerSum.java

---

src/main/java/com/thealgorithms/dynamicprogramming/LongestValidParentheses.java
src/test/java/com/thealgorithms/dynamicprogramming/LongestValidParenthesesTest

#3594: Need test cases for many of the Algorithms

Creating LongestValidParenthesesTest

---

src/test/java/com/thealgorithms/datastructures/trees/CeilInBinarySearchTreeTest.java
src/test/java/com/thealgorithms/datastructures/trees/TreeTestUtils.java

https://github.com/TheAlgorithms/Java/issues/3395

Fixes #3395: Adding unit test for CeilInBinarySearchTree file

---

src/main/java/com/thealgorithms/maths/Average.java
src/test/java/com/thealgorithms/maths/AverageTest.java

migrate tests to AverageTest

---

src/main/java/com/thealgorithms/ciphers/Vigenere.java
src/test/java/com/thealgorithms/ciphers/VigenereTest.java

Add unit tests for Vigenere cipher

---

src/main/java/com/thealgorithms/ciphers/Caesar.java
src/test/java/com/thealgorithms/ciphers/CaesarTest.java

Add unit tests for Caesar cipher

---

src/test/java/com/thealgorithms/strings/CheckVowelsTest.java

Test case for vowels check

---

src/test/java/com/thealgorithms/searches/HowManyTimesRotatedTest.java

Test cases for HowManyTimesRotated

---

src/test/java/com/thealgorithms/strings/WordLadderTest.java

Test case for WordLadder

---

src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
src/test/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumberTest.java

Renamed List_all_Possible_Words_From_Phone_Digits.java  to LetterCombinationsOfPhoneNumber.java and Created LetterCombinationsOfPhoneNumberTest.java for JUnit Tests. Also changed the access specifier of functions in LetterCombinationsOfPhoneNumber.java from private to protected for JUnit Tests.

Created LetterCombinationsOfPhoneNumberTest.java

---

src/test/java/com/thealgorithms/conversions/IntegerToRomanTest.java

test case for IntegerToRoman

---

src/test/java/com/thealgorithms/conversions/HexToOctTest.java

Test case for HexToOct

---

src/test/java/com/thealgorithms/dynamicprogramming/CatalanNumberTest.java

Test case for CatalanNumber

---

src/test/java/com/thealgorithms/conversions/BinaryToHexadecimalTest.java

Test case for BinaryToHexadecimal

---

src/test/java/com/thealgorithms/conversions/HexaDecimalToDecimalTest.java

Added test cases for hexadecimal to decimal

---

src/main/java/com/thealgorithms/conversions/HexaDecimalToBinary.java
src/test/java/com/thealgorithms/conversions/HexaDecimalToBinaryTest.java

Add Test case for HexaDecimalToBinary

---

src/main/java/com/thealgorithms/dynamicprogramming/EggDropping.java
src/test/java/com/thealgorithms/dynamicprogramming/EggDroppingTest.java

Add Test case for EggDropping

---

src/main/java/com/thealgorithms/strings/Pangram.java
src/test/java/com/thealgorithms/strings/PangramTest.java

Added new isPangramIndexOf() function in Pangram.java and updated its JUnit Tests in PangramTest.java

Added function in Pangram.java

---

src/main/java/com/thealgorithms/strings/Palindrome.java
src/test/java/com/thealgorithms/strings/PalindromeTest.java

Fixed error in Palindrome.java and gave semantic names to functions

---

src/main/java/com/thealgorithms/maths/Volume.java
src/test/java/com/thealgorithms/maths/VolumeTest.java

Created VolumeTest.java
And In Volume.java, Fixed Calculation error in volumeSphere() and volumeHemisphere() functions and removed main() and changed functions access specifier from private to public

Created VolumeTest.java & Fixed Bugs in Volume.java

---

src/main/java/com/thealgorithms/maths/PerfectCube.java
src/test/java/com/thealgorithms/maths/PerfectCubeTest.java

Added another function to PerfectCube.java and fixed a testing mistake in line number 9

Added function and fixed bug in PerfectCube.java

---

src/main/java/com/thealgorithms/maths/PerfectNumber.java
src/test/java/com/thealgorithms/maths/PerfectNumberTest.java

Created PerfectNumberTest.java
Added isPerfectNumber2() and removed main() in PerfectNumber.java

Created PerfectNumberTest.java & Added function in PerfectNumber.java

---

src/main/java/com/thealgorithms/sorts/BeadSort.java
src/test/java/com/thealgorithms/sorts/BeadSortTest.java

Create Bead sort and testcase

---

src/main/java/com/thealgorithms/maths/AliquotSum.java
src/test/java/com/thealgorithms/maths/AliquotSumTest.java

Added function in AliquotSum.java

---

src/test/java/com/thealgorithms/sorts/CocktailShakerSortTest.java

Added test cases to CocktailShakerSort.

---

src/test/java/com/thealgorithms/sorts/CocktailShakerSortTest.java
src/test/java/com/thealgorithms/sorts/OddEvenSortTest.java

- [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x ] This pull request is all my own work -- I have not plagiarized it.
- [ x ] All filenames are in PascalCase.
- [ x ] All functions and variable names follow Java naming conventions.
- [ x ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
#3594

Added test cases to OddEvenSort.

---

src/test/java/com/thealgorithms/datastructures/queues/PriorityQueuesTest.java

JUnit tests for priority queue data structure

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
DIRECTORY.md

docs: improve the issue forms

---

src/main/java/com/thealgorithms/maths/DudeneyNumber.java
src/main/java/com/thealgorithms/sorts/LinkListSort.java
src/main/java/com/thealgorithms/strings/Anagrams.java

Simplifying boolean returns

---

src/main/java/com/thealgorithms/datastructures/trees/PreOrderTraversal.java
src/test/java/com/thealgorithms/datastructures/trees/PreOrderTraversalTest.java

Added recursive&iterative preorder binary tree traversal

---

src/main/java/com/thealgorithms/datastructures/trees/ValidBSTOrNot.java
src/test/java/com/thealgorithms/datastructures/trees/ValidBSTOrNotTest.java

Valid BST: refactoring + added unit test

---

src/test/java/com/thealgorithms/searches/BinarySearch2dArrayTest.java

Additional tests for 2D array binary search

---

src/main/java/com/thealgorithms/geometry/GrahamScan.java
src/test/java/com/thealgorithms/geometry/GrahamScanTest.java

Graham scan algorithm

---

src/main/java/com/thealgorithms/datastructures/trees/InorderTraversal.java
src/test/java/com/thealgorithms/datastructures/trees/InorderTraversalTest.java

Added recursive&iterative inorder binary tree traversal

---

src/main/java/com/thealgorithms/backtracking/ArrayCombination.java
src/test/java/com/thealgorithms/backtracking/ArrayCombinationTest.java

feat: Backtracking algorithms (All combinations) #3912

---

src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java
src/test/java/com/thealgorithms/datastructures/lists/SinglyLinkedListTest.java

Add method to get middle node for SinglyLinkedList and unit test for SinglyLinkedList

---

src/main/java/com/thealgorithms/strings/StringCompression.java
src/test/java/com/thealgorithms/strings/StringCompressionTest.java

Added the String Compression Algorithm #3911

---

.github/workflows/update_directory.yml

fix DIRECTORY.md is not properly formatted. #3922

---

src/main/java/com/thealgorithms/conversions/BinaryToDecimal.java
src/test/java/com/thealgorithms/conversions/BinaryToDecimalTest.java

Refactored BinaryToDecimal class 

---

src/main/java/com/thealgorithms/maths/LeonardoNumber.java
src/main/java/com/thealgorithms/maths/LucasSeries.java
src/main/java/com/thealgorithms/maths/Median.java
src/test/java/com/thealgorithms/maths/LeonardoNumberTest.java
src/test/java/com/thealgorithms/maths/LucasSeriesTest.java
src/test/java/com/thealgorithms/maths/MedianTest.java

What's New :
**Modified:**
- **_src/main/java/com/thealgorithms/maths/LeonardoNumber.java_** added a link to Wikipedia and description.
- **_src/main/java/com/thealgorithms/maths/LeonardoNumber.java_** main method removed.
- **_src/main/java/com/thealgorithms/maths/LucasSeries.java_** main method removed.
- **_src/main/java/com/thealgorithms/maths/Median.java_** main method removed.
**Added:**
- **_src/test/java/com/thealgorithms/maths/LeonardoNumberTest.java_** LeonardoNumber JUnit test cases.
- **_src/test/java/com/thealgorithms/maths/LucasSeriesTest.java_** LucasSeries JUnit test cases.
- **_src/test/java/com/thealgorithms/maths/MedianTest.java_** Median JUnit test cases.
**Updates:**
- **_src/main/java/com/thealgorithms/maths/LeonardoNumber.java_** ArithmeticException added to …

JUnit Tests Added

---

src/main/java/com/thealgorithms/others/MemoryManagementAlgorithms.java

Refactor Code (MemoryManagementAlgorithms): Pull Up Variable

---

src/main/java/com/thealgorithms/datastructures/trees/BSTIterative.java
src/test/java/com/thealgorithms/datastructures/trees/BSTIterativeTest.java

- added usage of BinaryTree.Node
- removed redundant code
- added unit tests

BSTIterative refactoring

---

src/main/java/com/thealgorithms/dynamicprogramming/ClimbingStairs.java
src/test/java/com/thealgorithms/dynamicprogramming/climbStairsTest.java

Added optimised solution for climbing Stairs  Algorithm with edge test cases

---

src/main/java/com/thealgorithms/ciphers/DES.java

Add link to DES Algorithm on Wikipedia
Missed updating the wiki link in the previous MR (#4172 ), hence updating it.

Add wiki link for DES

---

src/main/java/com/thealgorithms/datastructures/trees/BSTRecursive.java
src/test/java/com/thealgorithms/datastructures/trees/BSTRecursiveTest.java

- added usage of BinaryTree.Node
- removed redundant code
- added unit tests

BSTRecursive refactoring:

---

src/main/java/com/thealgorithms/dynamicprogramming/PartitionProblem.java
src/main/java/com/thealgorithms/dynamicprogramming/SubsetSum.java
src/test/java/com/thealgorithms/dynamicprogramming/PartitionProblemTest.java

Partition Problem using Dynamic Programming

---

src/main/java/com/thealgorithms/scheduling/RRScheduling.java
src/test/java/com/thealgorithms/scheduling/RRSchedulingTest.java

add Round Robin Scheduling

---

src/main/java/com/thealgorithms/maths/Average.java

Add Null/Empty check for param in average method

---

src/main/java/com/thealgorithms/backtracking/WordSearch.java
src/test/java/com/thealgorithms/backtracking/WordSearchTest.java

Add WordSearch as a backtracking problem

---

src/main/java/com/thealgorithms/datastructures/trees/CreateBinaryTreeFromInorderPreorder.java
src/test/java/com/thealgorithms/datastructures/trees/CreateBinaryTreeFromInorderPreorderTest.java

- code refactoring in main class
- removed redundant code
- added unit tests

CreateBinaryTreeFromInorderPreorder refactoring

---

src/main/java/com/thealgorithms/maths/FindMin.java
src/test/java/com/thealgorithms/maths/FindMinTest.java

The current implementation of the method [`findMin`](https://github.com/TheAlgorithms/Java/blob/e14b30b88c0de95186fe1937f795b7d8fd3fa8aa/src/main/java/com/thealgorithms/maths/FindMin.java#L32) has some issues:
- all of the [existing test cases](https://github.com/TheAlgorithms/Java/blob/e14b30b88c0de95186fe1937f795b7d8fd3fa8aa/src/test/java/com/thealgorithms/maths/FindMinTest.java) have the minimum at index 0,
- it crashed for empty input.
In this PR, I:
- added missing test cases 982b296e1ffffb5042c05d018f2a94743d8c88ff,
- make `findMin` throw `IllegalArgumentException` when input is empty 548e1aa1043b337da160974403ab03a0ad9c9c67,
- do some minor style changes and update the documentation.
As in #4199 I decided not to create a separate issue for this - I hope this is not a problem.

style: handle empty input array in `FindMin.findMin`

---

src/main/java/com/thealgorithms/others/LowestBasePalindrome.java
src/test/java/com/thealgorithms/others/LowestBasePalindromeTest.java

The class [`LowestBasePalindrome`](https://github.com/TheAlgorithms/Java/blob/96c1a96647c947f8f0c531ade3bc18967359e0ea/src/main/java/com/thealgorithms/others/LowestBasePalindrome.java#L17) has several problems:
- it is not tested,
- the method [`LowestBasePalindrome::lowestBasePalindrome`](https://github.com/TheAlgorithms/Java/blob/96c1a96647c947f8f0c531ade3bc18967359e0ea/src/main/java/com/thealgorithms/others/LowestBasePalindrome.java#LL49C23-L49C43) falls into an _infinite loop_ for inputs `2` and `3`,
- does not work properly for [_large_ bases](https://github.com/TheAlgorithms/Java/blob/96c1a96647c947f8f0c531ade3bc18967359e0ea/src/main/java/com/thealgorithms/others/LowestBasePalindrome.java#L72),
- has some [dead code](https://github.com/TheAlgorithms/Java/blob/96c1a96647c947f8f0c531ad …

refactor: `LowestBasePalindrome`

---

src/main/java/com/thealgorithms/maths/ReverseNumber.java
src/test/java/com/thealgorithms/maths/ReverseNumberTest.java

This PR:
- refactors the class [`ReverseNumber`](https://github.com/TheAlgorithms/Java/blob/b6e78a45ac007570df4da7574b111a05000204d3/src/main/java/com/thealgorithms/maths/ReverseNumber.java#L7),
- adds tests for it.

refactor: `ReverseNumber`

---

src/main/java/com/thealgorithms/maths/NthUglyNumber.java
src/test/java/com/thealgorithms/maths/NthUglyNumberTest.java

This PR:
- refactors the [`NthUglyNumber`](https://github.com/TheAlgorithms/Java/blob/4bbc4bd69f2a68963ba733df744c6ea356aba109/src/main/java/com/thealgorithms/maths/NthUglyNumber.java#L18),
- adds tests.

refactor: generalise `NthUglyNumber`

---

src/main/java/com/thealgorithms/others/EulersFunction.java
src/test/java/com/thealgorithms/others/EulersFunctionTest.java

This PR:
- adds tests for [`EulersFunction`](https://github.com/TheAlgorithms/Java/blob/e29a22770ba4b89be32df07448868379682d50f0/src/main/java/com/thealgorithms/others/EulersFunction.java#L9),
- updates `EulersFunction.getEuler` to throw an `IllegalArgumentException` for non-positive inputs, 
- makes `EulersFunction` a proper _utility_ class,
- updates the documentation.

tests: add tests for `EulersFunction`

---

src/main/java/com/thealgorithms/others/SieveOfEratosthenes.java
src/test/java/com/thealgorithms/others/SieveOfEratosthenesTest.java

This PR:
- adds tests for `SieveOfEratosthenes`, cf. 61a901f9e1fbb2d8f6705084322046605597ace5,
- updates `SieveOfEratosthenes.findPrimesTill` to throw an IllegalArgumentException for non-positive inputs, cf. a6072b8303bbe487594fef385a260a3bb579bd57,
- refactors `SieveOfEratosthenes.findPrimesTill`, cf. c4ba10442c33185ae591cf7da2c6c83ba893e57f,
- makes a _proper utility_ class out of `SieveOfEratosthenes`, cf. e193f849cde3f3dc8fb76a25b6a9f2dc608de559,
- updates doc-strs, cf. 22fd4e56319b807a3415e8e0ff313bb08cc47ab4.

tests: add tests for `SieveOfEratosthenes`

---

src/main/java/com/thealgorithms/maths/Area.java
src/test/java/com/thealgorithms/maths/AreaTest.java

---changing the function's identifier from **surfaceAreaTriangleRectangle** to **surfaceAreaTriangle**.

surfaceAreaTriangle(fn_name_modified)

---

DIRECTORY.md
src/main/java/com/thealgorithms/maths/ParseInteger.java
src/test/java/com/thealgorithms/maths/ParseIntegerTest.java

Changes:
- added unit tests
- minor refactoring

Added unit tests for ParseInteger class

---

src/test/java/com/thealgorithms/dynamicprogramming/MinimumPathSumTest.java

Add unit tests for Minimum Path Sum algorithms

Add unit tests for Minimum Path Sum algorithm

---

src/main/java/com/thealgorithms/audiofilters/IIRFilter.java
src/main/java/com/thealgorithms/backtracking/AllPathsFromSourceToTarget.java
src/main/java/com/thealgorithms/backtracking/ArrayCombination.java
src/main/java/com/thealgorithms/backtracking/Combination.java
src/main/java/com/thealgorithms/backtracking/FloodFill.java
src/main/java/com/thealgorithms/backtracking/KnightsTour.java
src/main/java/com/thealgorithms/backtracking/MazeRecursion.java
src/main/java/com/thealgorithms/backtracking/NQueens.java
src/main/java/com/thealgorithms/backtracking/Permutation.java

Some Java naming Conventions and better structures replacing loops to to direct frame collection

---

src/main/java/com/thealgorithms/maths/NthUglyNumber.java

This PR removes some redundant import (i.e. `java.lang.IllegalArgumentException`) and does some other _basic linting_.

style: basic linting of `NthUglyNumber`

---

src/main/java/com/thealgorithms/maths/ReverseNumber.java

This PR:
- removes an unused import,
- fixes the order of the of the _modifiers_ in the definition of the class `ReverseNumber`.

style: lint `ReverseNumber`

---

src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java
src/test/java/com/thealgorithms/datastructures/lists/SinglyLinkedListTest.java

Recursive Reverse of Linked List

---

src/main/java/com/thealgorithms/bitmanipulation/ReverseBits.java
src/test/java/com/thealgorithms/bitmanipulation/ReverseBitsTest.java

Add Reverse Bits Algo in Bit-Manipulation

---

src/main/java/com/thealgorithms/bitmanipulation/IsEven.java
src/test/java/com/thealgorithms/bitmanipulation/IsEvenTest.java

Is Even Algo added

---

src/test/java/com/thealgorithms/sorts/GnomeSortTest.java
src/test/java/com/thealgorithms/sorts/PancakeSortTest.java

Added Tests for PancakeSort + fixed typo in GnomeSortTest

---

src/main/java/com/thealgorithms/bitmanipulation/IndexOfRightMostSetBit.java
src/test/java/com/thealgorithms/bitmanipulation/IndexOfRightMostSetBitTest.java

Add Index Of Right Most Set Bit Test

---

src/main/java/com/thealgorithms/maths/MillerRabinPrimalityCheck.java
src/main/java/com/thealgorithms/maths/MillerRabinPrimalityTest.java
src/test/java/com/thealgorithms/maths/MillerRabinPrimalityCheckTest.java

Miller-Rabin primality test implementation

---

.gitpod.dockerfile

chore: update gitpod/workspace-java-17 to 2023-08-30-14-07-38

---

.github/workflows/build.yml

chore: update `actions/setup-java` to `v3`

---

src/main/java/com/thealgorithms/bitmanipulation/SetBit
src/main/java/com/thealgorithms/bitmanipulation/SetBit.java
src/test/java/com/thealgorithms/bitmanipulation/SetBit.java

Adding SetBit to bitmanipulation

---

src/main/java/com/thealgorithms/bitmanipulation/ClearBit.java
src/test/java/com/thealgorithms/bitmanipulation/ClearBitTest.java

Adding Clear bit

---

src/main/java/com/thealgorithms/dynamicprogramming/MinimumSumPartition.java
src/test/java/com/thealgorithms/dynamicprogramming/MinimumSumPartitionTest.java

Resolves [4387](https://github.com/TheAlgorithms/Java/issues/4387)
Testcase cover 100% code

#4387 Enhance Minimum sum partition problem implementation

---

src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java
src/main/java/com/thealgorithms/misc/MedianOfRunningArrayByte.java
src/main/java/com/thealgorithms/misc/MedianOfRunningArrayDouble.java
src/main/java/com/thealgorithms/misc/MedianOfRunningArrayFloat.java
src/main/java/com/thealgorithms/misc/MedianOfRunningArrayInteger.java
src/main/java/com/thealgorithms/misc/MedianOfRunningArrayLong.java
src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java

Make `MedianOfRunningArray` Generic

---

src/main/java/com/thealgorithms/maths/FindMax.java

Same as #4397 but for  [`FindMax`](https://github.com/TheAlgorithms/Java/blob/ad4be217d43fdaa38c994d7397ba5e732de26096/src/main/java/com/thealgorithms/maths/FindMax.java).

style: make `FindMax` a proper utilty class

---

src/main/java/com/thealgorithms/dynamicprogramming/MinimumPathSum.java
src/test/java/com/thealgorithms/dynamicprogramming/MinimumPathSumTest.java

Resolves #4395 
Test cases cover 100% of code

Enhance MinimumPathSum

---

src/test/java/com/thealgorithms/maths/FindMinTest.java

Changing FindMinTest so it tests for negativ numbers

negative FindMinTest

---

src/main/java/com/thealgorithms/maths/FindMinRecursion.java

Changes similar to  #4401. Just on min now

remove array len + Math.min

---

src/test/java/com/thealgorithms/maths/FindMaxTest.java

Changing MaxFindTest like #4388

Changing MaxFindTest

---

.github/pull_request_template.md

docs: kindly ask contributors to create drafts

---

src/main/java/com/thealgorithms/datastructures/lists/ReverseKGroup.java
src/test/java/com/thealgorithms/datastructures/lists/ReverseKGroupTest.java

add reverse k group LinkedList

---

src/main/java/com/thealgorithms/misc/MedianOfMatrix.java
src/test/java/com/thealgorithms/misc/MedianOfMatrixtest.java

Fet: add median of matrix

---

src/main/java/com/thealgorithms/searches/RabinKarpAlgorithm.java
src/test/java/com/thealgorithms/searches/RabinKarpAlgorithmTest.java

code-clean-up

---

src/main/java/com/thealgorithms/maths/Armstrong.java
src/test/java/com/thealgorithms/maths/ArmstrongTest.java

I have already raised an Issue [here](https://github.com/TheAlgorithms/Java/issues/4617#issue-1925391015) 
The required changes were made to correct the logic and ,the description and comments have been added to ease the readability and understandability of the code.

Made changes to the code to correct the Logic of Armstrong Number

---

src/main/java/com/thealgorithms/misc/ColorContrastRatio.java

Fixed typo error in ColorContrastRatio
Fixes #4717

Fixed typo error for better readability

---

src/main/java/com/thealgorithms/bitmanipulation/IsEven.java

Correct documentation of `IsEven`

---

src/main/java/com/thealgorithms/misc/MapReduce.java
src/test/java/com/thealgorithms/misc/MapReduceTest.java

Added MapReduce Algorithm in Misc Folder.

---

src/main/java/com/thealgorithms/sorts/SelectionSort.java

refactor: use method `SortUtils.swap`

---

src/main/java/com/thealgorithms/divideandconquer/BinaryExponentiation.java

Optimized power calculation algorithm for efficiency and add comments for improved readability. Also added Wikipedia link for the mathematical explanation of the algorithm.

Enhance code density and readability

---

src/main/java/com/thealgorithms/others/BoyerMoore.java
src/test/java/com/thealgorithms/others/BoyerMooreTest.java

Cleanup `BoyerMoore`

---

src/main/java/com/thealgorithms/dynamicprogramming/Tribonacci.java
src/test/java/com/thealgorithms/dynamicprogramming/TribonacciTest.java

This PR introduces the `Tribonacci` class to the `dynamicprogramming` package. It implements an efficient method to compute the N-th number in the Tribonacci sequence as defined by the problem statement on LeetCode: https://leetcode.com/problems/n-th-tribonacci-number/description/.
Resolves #4646
- Added `Tribonacci.java` with a static `compute` method.
- Included tests in `TribonacciTest.java`.
The `compute` method calculates the N-th Tribonacci number using an iterative approach with O(n) time complexity and O(1) space complexity, which is optimal for the constraints given.

Tribonacci - #4646

---

.github/workflows/codeql.yml

I did some experiments with CodeQL and this repository. It turned out that [there are 4 issues](https://github.com/vil02/Java/security/code-scanning) - I will fix them in the upcoming days.
I think it makes sense to have the CodeQL scan by default.

Add `codeql.yml`

---

src/main/java/com/thealgorithms/maths/HarshadNumber.java

Fixes one of the issues detected by merging #4966. Similar to #4970, #4971 and #4972.

Make `sumOfDigits` `long` in `HarshadNumber.isHarshad`

---

src/main/java/com/thealgorithms/datastructures/graphs/BoruvkaAlgorithm.java
src/test/java/com/thealgorithms/datastructures/graphs/BoruvkaAlgorithmTest.java

This PR consists of an implementation for the Borůvka's algorithm (https://en.wikipedia.org/wiki/Bor%C5%AFvka%27s_algorithm) for finding a MST in graphs.

Added Boruvka's algorithm to find Minimum Spanning Tree

---

src/main/java/com/thealgorithms/stacks/NextGreaterElement.java

fixed typos in NextGraterElement.java

---

src/main/java/com/thealgorithms/maths/PerfectSquare.java
src/test/java/com/thealgorithms/maths/PerfectSquareTest.java

This PR:
- does some basic _cleanup_/_linting_ of the `PerfectSquare`,
- reduced code duplication in `PerfectSquareTest` by using _parameterized tests_.

Cleanup `PerfectSquare` and its tests

---

.github/workflows/stale.yml

ci: Use Discord channel in stale issue/PR message

---

.github/workflows/update_directory.yml

Same as TheAlgorithms/Rust#647.

fix: use `GITHUB_ACTOR` in `git config`

---

src/test/java/com/thealgorithms/strings/ReverseWordsInStringTest.java

`org.junit.jupiter.api.Test` is not used in this test.

style: remove unused import

---

src/test/java/com/thealgorithms/maths/PowerOfTwoOrNotTest.java

Remove unused import from `PowerOfTwoOrNotTest`

---

src/test/java/com/thealgorithms/maths/PerfectSquareTest.java

Remove unused imports from `PerfectSquareTest`

---

src/main/java/com/thealgorithms/greedyalgorithms/JobSequencing.java

Remove unused import from `JobSequencing`

---

src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMapCuckooHashing.java

Remove unused import from `HashMapCuckooHashing`

---

.github/CODEOWNERS

As I am not very active in this repository, I should step down from being a CodeOwner /cc @BamaCharanChhandogi @yanglbme @vie02

Remove debasishbsws from CODEOWNERS

---

.github/workflows/codeql.yml

Updates `actions/checkout` to `v4`. Sorry for missing it in #4966.

chore: update `actions/checkout` to `v4`

---

src/main/java/com/thealgorithms/backtracking/MColoring.java
src/main/java/com/thealgorithms/datastructures/dynamicarray/DynamicArray.java
src/main/java/com/thealgorithms/datastructures/lists/CircleLinkedList.java
src/main/java/com/thealgorithms/datastructures/lists/CursorLinkedList.java
src/main/java/com/thealgorithms/misc/ThreeSumProblem.java
src/main/java/com/thealgorithms/searches/UnionFind.java
src/main/java/com/thealgorithms/strings/WordLadder.java

In this PR, I have solved the problem in Java implementation that related to _parameterize references to generic types_ by adding types to generic containers references.

Parameterize references to generic types. 

---

.github/dependabot.yml

These changes will keep this line:
https://github.com/TheAlgorithms/Java/blob/71c5f27d85503c84449bdbe9232728a0a0a8bb95/.gitpod.dockerfile#L1
up to date.

chore: configure dependabot to update docker files

---

pom.xml

This PR updates the _maven dependencies_, basically it is a result of running 
```shell
mvn versions:display-dependency-updates
```

chore: update maven dependencies

---

.github/dependabot.yml

This PR will help to keep our [`pom.xml`](https://github.com/TheAlgorithms/Java/blob/4bb64559deb6722069678aaa910f7379645d5a7b/pom.xml) up to date.

chore: add `maven` to dependabot

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/ciphers/HillCipher.java

Continuation of #5122.
Note that both `encrypt` and `decrypt` call the `toUpperCase()`.

style: include `RV_RETURN_VALUE_IGNORED`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/maths/HarshadNumber.java

style: include `NAB_NEEDLESS_BOXING_PARSE`

---

checkstyle.xml

Continuation of #5179. @BamaCharanChhandogi please have a look.

style: enable `MissingSwitchDefault` in CheckStyle

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/crdt/LWWElementSet.java

style: include `ENMI_EQUALS_ON_ENUM`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/maths/StandardDeviation.java

style: include `IMC_IMMATURE_CLASS_VAR_NAME`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/graphs/KahnsAlgorithm.java
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/MajorityElement.java
src/main/java/com/thealgorithms/maths/Mode.java

style: include `WMI_WRONG_MAP_ITERATOR`

---

spotbugs-exclude.xml
src/test/java/com/thealgorithms/maths/GenericRootTest.java

Continuation of #5126. Should be done in #4276.

style: include `DMC_DUBIOUS_MAP_COLLECTION`

---

checkstyle.xml
src/main/java/com/thealgorithms/ciphers/AES.java

Related to [#5119](https://github.com/TheAlgorithms/Java/issues/5119).

style: enable `OperatorWrap` in checkstyle

---

checkstyle.xml
src/main/java/com/thealgorithms/datastructures/graphs/BellmanFord.java

style: enable `ParenPad` in checkstyle

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/graphs/ConnectedComponent.java

style: include `SUI_CONTAINS_BEFORE_ADD`

---

src/main/java/com/thealgorithms/sorts/StrandSort.java
src/test/java/com/thealgorithms/sorts/StrandSortTest.java

Refactor and enhance StrandSort to align with the SortAlgorithm approach. 
Generalize the algorithm to work with any type and replace LinkedList dependencies with common List interface.

Refactoring and code improving for StrandSort

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/devutils/nodes/LargeTreeNode.java
src/main/java/com/thealgorithms/searches/QuickSelect.java
src/main/java/com/thealgorithms/sorts/MergeSortRecursive.java

style: include `SPP_USE_ISEMPTY`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/stacks/DuplicateBrackets.java

Continuation of #5126. The removed `main` method does not add any value.

style: include `BED_BOGUS_EXCEPTION_DECLARATION`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArray.java

style: include `RV_ABSOLUTE_VALUE_OF_HASHCODE`

---

spotbugs-exclude.xml
src/test/java/com/thealgorithms/searches/BreadthFirstSearchTest.java
src/test/java/com/thealgorithms/searches/DepthFirstSearchTest.java

style: include `OI_OPTIONAL_ISSUES_USES_IMMEDIATE_EXECUTION`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/maths/Gaussian.java
src/test/java/com/thealgorithms/maths/GaussianTest.java

style: include `DLS_DEAD_LOCAL_STORE`

---

src/main/java/com/thealgorithms/sorts/CocktailShakerSort.java
src/test/java/com/thealgorithms/sorts/CocktailShakerSortTest.java

Improving code readability, simplify in some places
Adding general sorting test as it provides better coverage
Adding Java docs with description of methods

refactor: cleanup `CocktailShakerSort`

---

src/main/java/com/thealgorithms/sorts/DualPivotQuickSort.java
src/test/java/com/thealgorithms/sorts/DualPivotQuickSortTest.java

Improving code readability, simplify in some places
Adding general sorting test as it provides better coverage
Improving Java docs and comments

refactor: cleanup `DualPivotQuickSort`

---

src/main/java/com/thealgorithms/datastructures/bloomfilter/BloomFilter.java
src/test/java/com/thealgorithms/datastructures/bloomfilter/BloomFilterTest.java

Adding Javadocs.
Improving tests coverage.

refactor: `BloomFilter`

---

src/main/java/com/thealgorithms/sorts/InsertionSort.java

InsertionSort cleanup
Code readability improvements

refactor: cleanup `InsertionSort`

---

src/main/java/com/thealgorithms/conversions/DecimalToAnyBase.java
src/test/java/com/thealgorithms/conversions/DecimalToAnyBaseTest.java

Improving readability.
Adding tests.

refactor: `DecimalToAnyBase`

---

src/main/java/com/thealgorithms/conversions/OctalToHexadecimal.java
src/test/java/com/thealgorithms/conversions/OctalToHexadecimalTest.java

Improving readability.
Adding tests.

refactor: `OctalToHexadecimal`

---

src/main/java/com/thealgorithms/datastructures/dynamicarray/DynamicArray.java
src/test/java/com/thealgorithms/datastructures/dynamicarray/DynamicArrayTest.java

Improvements to the `DynamicArray` class:
Capacity Management:
Added checks to automatically resize the array if an element is added at an index beyond the current size.
Simplified the add and put methods to ensure they handle capacity correctly.
Boundary and Error Handling:
Added checks for invalid indices (negative values and out-of-bound values).
Enhanced type safety by suppressing warnings for unchecked casts.
Concurrent Modification:
Introduced a `modCount` field to track structural modifications and ensure that the iterator detects concurrent modifications.
Iterator Implementation:
Improved Iterator to correctly detect concurrent modifications and handle the remove operation safely.
Added tests.

refactor: `DynamicArray`

---

src/main/java/com/thealgorithms/datastructures/stacks/StackArrayList.java
src/test/java/com/thealgorithms/datastructures/stacks/StackArrayListTest.java

Cleanup StackArrayList.
Added tests.

refactor: `StackArrayList`

---

src/main/java/com/thealgorithms/datastructures/queues/GenericArrayListQueue.java
src/test/java/com/thealgorithms/datastructures/queues/GenericArrayListQueueTest.java

Cleanup GenericArrayListQueue.
Added tests.

refactor: `GenericArrayListQueue`

---

src/main/java/com/thealgorithms/datastructures/queues/LinkedQueue.java
src/test/java/com/thealgorithms/datastructures/queues/LinkedQueueTest.java

Make LinkedQueue generic.
Added tests.

refactor: `LinkedQueue`

---

src/main/java/com/thealgorithms/conversions/AnyBaseToDecimal.java
src/test/java/com/thealgorithms/conversions/AnyBaseToDecimalTest.java

refactor: `AnyBaseToDecimal`

---

src/main/java/com/thealgorithms/strings/LongestNonRepetitiveSubstring.java
src/test/java/com/thealgorithms/strings/LongestNonRepetitiveSubstringTest.java

refactor: fix typo in class name `LongestNonRepetitiveSubstring`

---

src/main/java/com/thealgorithms/maths/TwinPrime.java
src/main/java/com/thealgorithms/strings/StringCompression.java

There are two typos in javadocs in TwinPrime and StringCompression

refactor: fix typo

---

src/main/java/com/thealgorithms/maths/Pow.java
src/test/java/com/thealgorithms/maths/PowTest.java

Javadocs improvements.
Added tests.

refactor: `Pow`

---

src/main/java/com/thealgorithms/strings/PermuteString.java
src/test/java/com/thealgorithms/strings/PermuteStringTest.java

Javadoc improvements.
Added tests.

refactor: `PermuteString`

---

src/test/java/com/thealgorithms/strings/PalindromeTest.java

Refactoring `PalindromeTest` to a ParameterizedTest approach, as it provides more flexibility.
Also replace wrong `or` condition via `and` because each isPalindrome method should be correct.

test: refactor `PalindromeTest`

---

src/main/java/com/thealgorithms/maths/DeterminantOfMatrix.java
src/test/java/com/thealgorithms/maths/DeterminantOfMatrixTest.java

Adding javadoc.
Adding test for DeterminantOfMatrix.

test: `DeterminantOfMatrix`

---

src/main/java/com/thealgorithms/maths/FindKthNumber.java
src/test/java/com/thealgorithms/maths/FindKthNumberTest.java

Improving the code to make it more readable.
Adding additional tests to this algorithm.

refactor: `FindKthNumber`

---

src/main/java/com/thealgorithms/others/TwoPointers.java
src/test/java/com/thealgorithms/others/TwoPointersTest.java

refactor: `TwoPointers`

---

src/main/java/com/thealgorithms/dynamicprogramming/FordFulkerson.java
src/test/java/com/thealgorithms/dynamicprogramming/FordFulkersonTest.java

refactor: `FordFulkerson`

---

src/main/java/com/thealgorithms/stacks/DecimalToAnyUsingStack.java
src/test/java/com/thealgorithms/stacks/DecimalToAnyUsingStackTest.java

refactor: `DecimalToAnyUsingStack`

---

src/main/java/com/thealgorithms/strings/CheckVowels.java
src/test/java/com/thealgorithms/strings/CheckVowelsTest.java

refactor: `CheckVowels`

---

src/main/java/com/thealgorithms/dynamicprogramming/EditDistance.java
src/test/java/com/thealgorithms/dynamicprogramming/EditDistanceTest.java

test: `EditDistanceTest`

---

src/main/java/com/thealgorithms/strings/CharactersSame.java
src/test/java/com/thealgorithms/strings/CharacterSameTest.java

Class cleanup.
Refactor tests.

refactor: `CharactersSame`

---

src/main/java/com/thealgorithms/dynamicprogramming/ShortestCommonSupersequenceLength.java
src/test/java/com/thealgorithms/dynamicprogramming/ShortestCommonSuperSequenceLengthTest.java

refactor: `ShortestCommonSuperSequenceLength`

---

src/main/java/com/thealgorithms/strings/LongestNonRepetitiveSubstring.java
src/test/java/com/thealgorithms/strings/LongestNonRepetitiveSubstringTest.java

Class cleanup.
Readability and efficiency improvements.
Added tests.

refactor: `LongestNonRepetitiveSubstring`

---

src/main/java/com/thealgorithms/maths/LeastCommonMultiple.java
src/test/java/com/thealgorithms/maths/LeastCommonMultipleTest.java

refactor: `LeastCommonMultiple`

---

spotbugs-exclude.xml
src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java

style: include `NAB_NEEDLESS_BOX_TO_UNBOX`

---

pom.xml
src/main/java/com/thealgorithms/greedyalgorithms/ActivitySelection.java

Improve comments in ActivitySelection.java

---

src/main/java/com/thealgorithms/bitmanipulation/NumberAppearingOddTimes.java
src/test/java/com/thealgorithms/bitmanipulation/NumberAppearingOddTimesTest.java

Adds the Algorithm 1 as in #5628

Add `NumberAppearingOddTimes.java` new Algorithm

---

DIRECTORY.md
src/test/java/com/thealgorithms/dynamicprogramming/CountFriendsPairingTest.java

Add tests in `CountFriendsPairing.java`

---

checkstyle.xml

Related to https://github.com/TheAlgorithms/Java/issues/5119.
**Changes Made:**
- Enabled the **TodoComment** check in checkstyle.xml.
- Verified that there are no violations in the current codebase.

style: enable `TodoComment` in checkstyle

---

src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
src/test/java/com/thealgorithms/datastructures/graphs/KosarajuTest.java

refactor: Enhance docs, add more tests in `Kosaraju`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/scheduling/SJFScheduling.java

style: include `PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS`

---

src/test/java/com/thealgorithms/strings/IsomorphicTest.java

tests: properly test `Isomorphic`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/ciphers/AffineCipher.java

style: include `SLS_SUSPICIOUS_LOOP_SEARCH`

---

spotbugs-exclude.xml
src/main/java/com/thealgorithms/datastructures/caches/LFUCache.java

style: include `RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE`
